### ISSUE TITLE
Milion lint for projects running inside docker container and behind proxy

### ISSUE THREAD

**Issue by elliason** [aidenybai/million#1000]
### Describe the feature

Hi, 
I have troubles connecting to milion lint for a project that runs in a docker container and the web is behind proxy (i.e. not accessible on localhost:3000 ). Is this somehow possible, and if not, is this on your roadmap ?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Cielquan** [comment]
I have a similar issue. I am running the VSCode SSH extension to develop remotely on a VM. The VM runs nginx to make serve the site. So localhost:3000 is also not directly available.

**Comment by vafanassieff** [comment]
Can this issue be reopened, or can we have info on wich port should be open to allow million lint to share data from the browser to VS Code ?

**Comment by tobySolutions** [comment]
Thanks, @elliason, @Cielquan, @vafanassieff really sorry about this lack of information. Let me log this with the team and get your information across.

**Comment by CarlosVergikosk** [comment]
@tobySolutions @aidenybai  hey, any news on this?
