### ISSUE TITLE
Link issue with i18n on the Million website

### ISSUE THREAD

**Issue by yafkari** [aidenybai/million#1001]
### What version of `million` are you using?

x

### Are you using an SSR adapter? If so, which one?

x

### What package manager are you using?

x

### What operating system are you using?

x

### What browser are you using?

x

### Describe the Bug

If you are on the "https://million.dev/fr-FR" page and you click on the link to "Lint" in the navbar, it will try to access "https://million.dev/fr-FR/lint" which does not exists instead to fallback to "https://million.dev/lint"

### What's the expected result?

If the homepage is localized but the page we're trying to access is not, it should redirect to the English link or always target the default link and redirect to the localized version later on.

### Link to Minimal Reproducible Example

x

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thank you for this @yafkari, we're currently taking a look at this!
