### ISSUE TITLE
Million Lint Ignoring custom webpack config 

### ISSUE THREAD

**Issue by LPSebi** [aidenybai/million#1003]
### What version of `million` are you using?

3.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

Million Lint v0.0.73

![image](https://github.com/aidenybai/million/assets/52174534/6d0eea76-fdac-413a-96bc-8f76d4030ac6)
When updating the webpack config in next.config.mjs it will not get applied when using million lint and will therefore show this error:
![image](https://github.com/aidenybai/million/assets/52174534/b5ae66d9-5552-4da9-bed1-514656a58b82)

### What's the expected result?

Apply the webpack config changes correctly

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thank you for this, the team is actively working on this.

**Comment by Archimagus** [comment]
Just to add to this.  It also doesn't seem to support loaders correctly.  
```javascript
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(frag|vert|glsl)$/,
      type: 'asset/source',
    });
    return config;
  },
```

```bash
./src/materials/shaders/CustomDiffuse.frag
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #ifdef USE_MAP
|   vec4 col1 = texture2D( map, vMapUv );
|   if(diffuseColor.a < 0.5) 
```

It works correctly without million.

**Comment by Sliov** [comment]
Same issue here

**Comment by Archimagus** [comment]
No work on support for this?

**Comment by tobySolutions** [comment]
> No word on support for this?

Hey there @Archimagus, this is being worked on by the team and will be available in the next release. I'll confirm with the team to be sure as well.

**Comment by ImLunaHey** [comment]
bad bot

**Comment by LPSebi** [comment]
> > No word on support for this?
> 
> Hey there @Archimagus, this is being worked on by the team and will be available in the next release. I'll confirm with the team to be sure as well.

@tobySolutions any updates?
