### ISSUE TITLE
Million Lint Onboarding: Support Cursor as well as VSCode

### ISSUE THREAD

**Issue by DannyAziz** [aidenybai/million#1004]
### Describe the feature

Got stuck in a loop trying to login to million but currently the deeplink only goes over to VSCode

I got over this by using a devtools content override and changing the `window.open` call to the following: `window.open("cursor://million.million-lint/auth?token=".concat(n) + "&name=" + (null === (e = i.user) || void 0 === e ? void 0 : e.fullName), "_blank")`

A button on the UI would be awesome

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by DannyAziz** [comment]
I guess this is more than just the onboarding flow, even when using the Open feature inside the web app it tries to open the file inside vscode

![Screenshot 2024-03-20 at 12 17 52](https://github.com/aidenybai/million/assets/3679064/405d304e-1beb-4bbc-9a2d-06eb7336023f)

**Comment by tobySolutions** [comment]
Thank you for opening this @DannyAziz, I will inform the team of this.

**Comment by alexdanilowicz** [comment]
+1 on this

**Comment by nucks** [comment]
+1

**Comment by A-kamal** [comment]
+1 🙏

**Comment by Kosmoon** [comment]
+1

**Comment by stas-raranetskyi** [comment]
+1

**Comment by aziz-akera** [comment]
+1

**Comment by santiarr** [comment]
+1
