### ISSUE TITLE
Death by letter X

### ISSUE THREAD

**Issue by Alexander-Fransson** [aidenybai/million#1012]
### What version of `million` are you using?

2.6.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

Linux mint

### What browser are you using?

firefox

### Describe the Bug

Creates components that kills the app upon the usage of the letter x in p & h tags.

This code :  <h1>x</h1> Gives this message in the terminal:  <Mgrrnihblaf> now renders ~14% faster.

Similar issues appear when using p tags.

### What's the expected result?

The expected result is that it just renders the normal component and that the app does not die.

### Link to Minimal Reproducible Example

https://DidNotRealyUnderstandWhatToLinkHere.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hello there @Alexander-Fransson , can you please provide a Stackblitz / CodeSandbox reproduction of the issue you're getting so I can help out?

**Comment by Alexander-Fransson** [comment]
Hi, sorry for the inconvenience,

I believe I made a workaround yesterday and now I’m seemingly unable to
recreate the error.

Ill remove the issue for now, but I’ve noticed it a couple of times so
maybe Ill repost it once Im able to recreate it.

If there are other issues where the terminal states that some random string
component runs faster and the screen becomes black it is probably related.

Best wishes,
Alexander Fransson
