### ISSUE TITLE
Feedback for “Experimental”

### ISSUE THREAD

**Issue by priyanksavaliya21** [aidenybai/million#1014]
In Vite.js, I enabled auto mode, but even after adding the noslot code in my APP.jsx file, the slot tag persists when I use it. How can I resolve this issue?

The issue is affecting my UI and CSS styling. because of Slot tag

![Screenshot_2](https://github.com/aidenybai/million/assets/102215412/1121cf40-2f03-482a-8703-ca61965c6f8f)
![Screenshot_1](https://github.com/aidenybai/million/assets/102215412/73bc83e4-5954-4e9f-bf77-84a39da08a9a)

**Comment by tobySolutions** [comment]
> In Vite.js, I enabled auto mode, but even after adding the noslot code in my APP.jsx file, the slot tag persists when I use it. How can I resolve this issue?
> 
> The issue is affecting my UI and CSS styling. because of Slot tag
> 
> ![Screenshot_2](https://private-user-images.githubusercontent.com/102215412/319475241-1121cf40-2f03-482a-8703-ca61965c6f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjUyNjQsIm5iZiI6MTcxMjI2NDk2NCwicGF0aCI6Ii8xMDIyMTU0MTIvMzE5NDc1MjQxLTExMjFjZjQwLTJmMDMtNDgyYS04NzAzLWNhNjE5NjVjNmY4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMTA5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTFiMjQzOGI2YjNjZTM2NzQ4ZmRkZGViYTg3ZGQ2MTcwZTUzNzRmZDdlZGFlYTYxOGM3ZGZkNWU3YjY0ZTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NCR8xRi_YXCOflC1px8twUtRIrl8Evrc4gWY7XPVkcs) ![Screenshot_1](https://private-user-images.githubusercontent.com/102215412/319475250-73bc83e4-5954-4e9f-bf77-84a39da08a9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjUyNjQsIm5iZiI6MTcxMjI2NDk2NCwicGF0aCI6Ii8xMDIyMTU0MTIvMzE5NDc1MjUwLTczYmM4M2U0LTU5NTQtNGU5Zi1iZjc3LTg0YTM5ZGEwOGE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMTA5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmE1OTAzZWMwNDNkMjkxY2EwYjIwYWYxZDcyYjRiYjZjNmU0ZGRhMjRjZmE4NmQxZDk1M2IwYzU2ODViNmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MGbG22hTV4xK9ZGUeA5y8QjDGnknJyE5DOh1yfevQcI)

Hmm, at the moment the `experimental...` option is very tricky as it isn't completely stable. However, I would suggest 2 things:

- Move the experimental option to the root of the project in say your `index` file.
- Try using the [`million-ignore`](https://million.dev/docs/automatic#ignoring-components) in those files where you are experiencing this.
