### ISSUE TITLE
Feature: Million Lint silent mode if someone does not have the Million Lint VS Code extension installed

### ISSUE THREAD

**Issue by nickytonline** [aidenybai/million#1015]
### Describe the feature

I started using Million Lint yesterday and [plan to add it to our project](https://github.com/open-sauced/app/pull/3108), however, not everyone working on the project, external contributors or maybe even some core team members who aren't necessarily working in the React part of the project, might want to run the development environment without it.

At the moment, they receive this error message.

![CleanShot 2024-04-04 at 07 40 33](https://github.com/aidenybai/million/assets/833231/7cae6b49-b8e8-45f5-9ee3-ad3ec69bf488)

It's pretty clear in what you need to do, but again, someone who might be doing a styling fix or something else completely unrelated to potential performance improvements might find this as a friction point to contribute to the project.

I have workarounds that I could do, like an environment variable, but a silent error option to suppress the above would be ideal.

Happy to contribute towards this if this is something the team considers.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hmm, thank you very much for raising this @nickytonline! Really appreciate it. At the moment there isn't any in the compiler at the moment. I will inform the team of this so they can make decisions regarding this.

**Comment by nickytonline** [comment]
For the time being @tobySolutions, so we can use it in the project, I've gone with the environment variable approach I've mentioned in this issue. See https://github.com/open-sauced/app/pull/3108

**Comment by tobySolutions** [comment]
Hmm, thank you very much @nickytonline; I reported the issue and they are currently working on it. We have a release coming very soon later this month or the next and these should have been handled by then. Thank you very much!

**Comment by nickytonline** [comment]
Thanks for the update!
