### ISSUE TITLE
Million Lint with Next: Respecting functions that returns the config

### ISSUE THREAD

**Issue by AmrTamer23** [aidenybai/million#1016]
### What version of `million` are you using?

none
Million Lint: `^0.0.73`

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

After adding Million Lint to my next project it couldn't build, due to not respecting the withMDX function from `@next/mdx`, 
```js
module.exports = MillionLint.next({
  rsc: true
})(withMDX(nextConfig));
```
and this is the error 
![image](https://github.com/aidenybai/million/assets/122938074/a2dfebbf-9d74-41ee-b844-ddd2370ac245)

### What's the expected result?

I fixed it with calling the Million Lint function inside the withMDX function like this 
```js
module.exports = withMDX(
  MillionLint.next({
    rsc: true,
  })(nextConfig)
);
```

### Link to Minimal Reproducible Example

None

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thank you very much for reporting this here @AmrTamer23, I will report this to the team and they'll take a look at it.
