### ISSUE TITLE
Million Lint for WebStorm

### ISSUE THREAD

**Issue by TheOrdinaryWow** [aidenybai/million#1017]
### Describe the feature

Million Lint is currently exclusive to VSCode. Could there be possibility for WebStorm support in the future? This would be a great benefit for JetBrains users. Thanks!

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Awesome! Thank you for this @TheOrdinaryWowwe will look into this. Thank you very much!! 🙌

**Comment by pfe-nazaries** [comment]
Up

**Comment by alkanna** [comment]
@tobySolutions Is there any chance we can get this reopened ?

**Comment by asim-shrestha** [comment]
any progress here?

**Comment by ilarramendi** [comment]
+1

**Comment by Artucuno** [comment]
+1

**Comment by CarlosSenobio** [comment]
+1

**Comment by Mouerr** [comment]
` + 1`

**Comment by eglove** [comment]
+1

**Comment by MarcoColiaAtFiftyDeg** [comment]
up

**Comment by mark-avd** [comment]
up

**Comment by Yuozas** [comment]
⬆️
