### ISSUE TITLE
Lost MiniCssExtractPlugin, do not parse scss files

### ISSUE THREAD

**Issue by mykhailokonst** [aidenybai/million#1018]
### What version of `million` are you using?

0.0.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Versions:

`"webpack": "5.91.0",
    "webpack-bundle-analyzer": "4.10.1",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "5.0.4",
"mini-css-extract-plugin": "2.8.1",
"react": "18.2.0",
    "react-dom": "18.2.0",`

After adding Million Lint, npm run start failed. It tells that I forgot to add MiniCssExtractPlugin in plugins section in webpack, but it exists there, and it build well after removing millionlint plugin.

`plugins: [
      new ForkTsCheckerWebpackPlugin({
        typescript: {
          configFile: path.join(__dirname, '..', 'tsconfig.json'),
        },
      }),
      // Combine all generated styles into a single bundle.css file
      new MiniCssExtractPlugin({ filename: server ? '[name].css' : '[name].[contenthash].css' }),
      new HtmlWebpackPlugin({
        // Do not inject references to the webpack generatad js/css bundles. It will be done
        // manually in the template
        inject: false,

        // Add hashes to the bundle references to invalidate caching
        hash: true,

        // ejs template to use. Search following this order:
        // - a config/index.html.ejs file inside the project
        // - the framework's default template
        template: findFile('<root>/config/index.html.ejs', '<framework>/index.html.ejs'),

        // Name of the generated template file
        filename: 'index.html',

        // Initial application state set as global window variables. Only available in server mode.
        state: server ? requireFile('<root>/config/server/state.js', '<framework>/server/state.js') : {},
      }),

      // Generate a GO index.html.tmpl template for standalone deploys
      !server &&
        new HtmlWebpackPlugin({
          inject: false,
          hash: true,
          template: findFile('<root>/config/index.html.ejs', '<framework>/index.html.ejs'),
          filename: 'index.html.tmpl',
        }),

      // Tell webpack not to require jQuery. If a project uses jQuery it must include a
      // <script> tag in the template
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        // Node.js polyfills
        process: 'process/browser',
      }),

      // Prune from the bundle the unneeded validator-js locales.
      // Framework supported "es" and "en" locales are bundled by default
      new webpack.ContextReplacementPlugin(/validatorjs[\/\\]src[\/\\]lang/, /es|en/),

      // Output gzip version of the assets
      !server && new CompressionPlugin({}),
      new BundleAnalyzerPlugin(),
      MillionLint.webpack(),
    ],`

Errors:

`ERROR in ./shared/modules/status-history/status-history.scss
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
Error: You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started
    at Object.pitch (**/node_modules/mini-css-extract-plugin/dist/loader.js:77:14)
 @ ./modules.tsx 11:0-86 19:104-139
 @ ./main.tsx 25:0-36 42:238-245

webpack 5.91.0 compiled with 461 errors in 54839 ms`

### What's the expected result?

Webpack build should be successful.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hey there @mykhailokonst, do you think you can maybe provide a reproduction so I can help out? Thank you very much!

**Comment by mykhailokonst** [comment]
@tobySolutions , sure. You can comment/uncomment millio.webpack() line to check
[Codesandbox link](https://codesandbox.io/p/devbox/mt36vf?file=%2Fpackage.json%3A15%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clutjnfjz00063b6j9nakp1h5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clutjnfjz00023b6j0w3vpt9u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clutjnfjz00043b6j38w8qpx5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clutjnfjz00053b6jm5ozng6c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clutjnfjz00023b6j0w3vpt9u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clutjnfjy00013b6jop32yruc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A27%257D%255D%257D%255D%252C%2522id%2522%253A%2522clutjnfjz00023b6j0w3vpt9u%2522%252C%2522activeTabId%2522%253A%2522clutjnfjy00013b6jop32yruc%2522%257D%252C%2522clutjnfjz00053b6jm5ozng6c%2522%253A%257B%2522id%2522%253A%2522clutjnfjz00053b6jm5ozng6c%2522%252C%2522activeTabId%2522%253A%2522clutk87fs00wb3b6iq2qdl3xc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A8080%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clutk87fs00wb3b6iq2qdl3xc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clutjnfjz00043b6j38w8qpx5%2522%253A%257B%2522id%2522%253A%2522clutjnfjz00043b6j38w8qpx5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clutjnfjz00033b6jp9tefcx6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clutjngd4000adjf83jfs38vt%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clutjnx67005z3b6j7q9m4wuu%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clutjnx67005z3b6j7q9m4wuu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by mykhailokonst** [comment]
@tobySolutions, any updates here?

**Comment by tobySolutions** [comment]
> @tobySolutions, any updates here?

Taking a look now, thank you very much @mykhailokonst.

**Comment by tobySolutions** [comment]
I have taken a look and I think I need to inform the team of this issue so they can take a look. I'll pass on your reproduction to the team and I'll get back to you @mykhailokonst. Thank you.
