### ISSUE TITLE
Provide option to disable intro message in terminal

### ISSUE THREAD

**Issue by jkhaui** [aidenybai/million#1019]
### Describe the feature

Hey,

Million is the most ingenious drop-in solution to perf optimisation I've seen, so kudos for that!

I'm trying to build a (vite-based) meta-framework with first-class million integration.
I absolutely want to spread the word and support million; just not in a way that results in a branded terminal message being the first thing developers see every time they start a project.

I.e. I think it is actually in Million's interests to let itself be a hidden implementation detail and could help grow adoption long-term.

Hope you'll consider this for an upcoming release - thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Thank you very much for this! I actually reported this to the team a few days back and it's currently being worked on. Really appreciate it @jkhaui.

**Comment by jkhaui** [comment]
Awesome! Great to hear, thanks for the reply @tobySolutions
