### ISSUE TITLE
Error when installing: "ReadableStream is not defined" 

### ISSUE THREAD

**Issue by htorohn** [aidenybai/million#1021]
### What version of `million` are you using?

latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MAC OS SOnoma 14.4.1

### What browser are you using?

Chrome 

### Describe the Bug

When installing Million.js I get the error "ReadableStream is not defined".

This is the complete log of the **npx million@latest** comand:

htoro@The-Very-Best-MAC px-frontend % npx million@latest
/Users/htoro/.npm/_npx/37326a470e3eb3b8/node_modules/million/packages/cli/dist/index.js:12032
      ReadableStream
      ^

ReferenceError: ReadableStream is not defined
    at ../../node_modules/.pnpm/undici@6.3.0/node_modules/undici/lib/fetch/response.js (/Users/htoro/.npm/_npx/37326a470e3eb3b8/node_modules/million/packages/cli/dist/index.js:12032:7)
    at __require (/Users/htoro/.npm/_npx/37326a470e3eb3b8/node_modules/million/packages/cli/dist/index.js:27:50)
    at ../../node_modules/.pnpm/undici@6.3.0/node_modules/undici/index.js (/Users/htoro/.npm/_npx/37326a470e3eb3b8/node_modules/million/packages/cli/dist/index.js:16933:32)
    at __require (/Users/htoro/.npm/_npx/37326a470e3eb3b8/node_modules/million/packages/cli/dist/index.js:27:50)
    at Object.<anonymous> (/Users/htoro/.npm/_npx/37326a470e3eb3b8/node_modules/million/packages/cli/dist/index.js:23655:29)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

This is my package.json file: 

{
  "name": "is-frontend",
  "version": "1.3.21",
  "private": true,
  "dependencies": {
    "@date-io/moment": "^1.3.13",
    "@devexpress/dx-react-core": "^4.0.8",
    "@devexpress/dx-react-grid": "^4.0.8",
    "@devexpress/dx-react-grid-export": "^4.0.8",
    "@devexpress/dx-react-grid-material-ui": "^4.0.8",
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@fontsource/roboto": "^4.5.7",
    "@mui/icons-material": "^5.8.4",
    "@mui/lab": "^5.0.0-alpha.89",
    "@mui/material": "^5.8.7",
    "@mui/styles": "^5.8.7",
    "@mui/x-date-pickers": "^5.0.15",
    "@mui/x-date-pickers-latest": "npm:@mui/x-date-pickers@^7.2.0",
    "@react-google-maps/api": "^2.10.2",
    "@reduxjs/toolkit": "^1.9.5",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.7.3",
    "@uiw/react-watermark": "^1.0.0",
    "assert": "^2.0.0",
    "axios": "^1.6.8",
    "buffer": "^6.0.3",
    "caniuse-lite": "^1.0.30001504",
    "chart.js": "^3.7.0",
    "chartjs-plugin-datalabels": "^2.0.0",
    "clsx": "latest",
    "crypto-browserify": "^3.12.0",
    "file-saver": "^2.0.5",
    "flattenjs": "^2.1.2",
    "formik": "^2.4.5",
    "https-browserify": "^1.0.0",
    "jsonwebtoken": "^9.0.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "mui-chips-input": "^1.3.2",
    "mui-file-input": "^1.1.3",
    "mui-tel-input": "^1.4.1",
    "nanoid": "^3.1.20",
    "os-browserify": "^0.3.0",
    "process": "^0.11.10",
    "react": "^18.2.0",
    "react-app-rewired": "^2.2.1",
    "react-aria": "^3.23.1",
    "react-chartjs-2": "^4.0.0",
    "react-dom": "^18.2.0",
    "react-dropzone": "^14.2.3",
    "react-feather": "^2.0.9",
    "react-helmet": "^6.1.0",
    "react-imask": "^6.4.2",
    "react-lazy-load-image-component": "^1.6.0",
    "react-material-ui-carousel": "^3.4.2",
    "react-modal": "^3.16.1",
    "react-perfect-scrollbar": "^1.5.8",
    "react-redux": "^8.1.0",
    "react-router-dom": "^6.6.2",
    "react-swipeable-views": "^0.13.9",
    "react-to-print": "^2.12.3",
    "react-window": "^1.8.9",
    "redux": "^4.2.0",
    "socket.io-client": "^4.6.2",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "typescript": "^4.7.4",
    "url": "^0.11.0",
    "util": "^0.12.4",
    "uuid": "^8.3.2",
    "vite-plugin-package-version": "^1.0.2",
    "vite-plugin-svgr": "^2.2.0",
    "web-vitals": "^1.1.0",
    "xlsx": "^0.18.5",
    "yup": "^0.32.11"
  },
  "scripts": {
    "dev": "vite --host",
    "start": "vite",
    "build": "env-cmd -f ./.env.production.local vite build",
    "build:staging": "env-cmd -f ./.env.staging.local vite build",
    "eject": "react-scripts eject",
    "preinstall": "npx npm-force-resolutions",
    "preview": "vite preview"
  },
  "engines": {
    "node": ">=12.0.0"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^1.3.2",
    "@welldone-software/why-did-you-render": "^7.0.1",
    "react-error-overlay": "^6.0.11",
    "vite": "^2.9.14",
    "vite-preset-react": "^2.3.0"
  },
  "resolutions": {
    "react-error-overlay": "6.0.11"
  }
}

Can you point out if something is missing? 

thanks

### What's the expected result?

Millions Js is installed on my React application.

### Link to Minimal Reproducible Example

i get an error in stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hey there @htorohn, what is your codebase's setup> Vite, Webpack, Craco? I'd love to be able to reproduce this to clarify what the issue might be.

**Comment by htorohn** [comment]
Hello @tobySolutions , thanks for your communication.

Here is my **vite.config.ts** file:
// vite.config.ts
// import react from '@vitejs/plugin-react'
import { fileURLToPath, URL } from "url";
import { defineConfig } from 'vite';
import loadVersion from 'vite-plugin-package-version';
import svgr from 'vite-plugin-svgr';
import react from 'vite-preset-react';

export default defineConfig({
  plugins: [react({ removeDevtoolsInProd: true, injectReact: true }), svgr(), loadVersion()],
  resolve: {
    alias: {
      process: "process/browser",
      stream: "stream-browserify",
      zlib: "browserify-zlib",
      util: 'util',
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    }
  },
  build:{
    outDir: './build',
    minify: false
  }
})

let me know if more detail is needed, thanks.

**Comment by htorohn** [comment]
I didn't received any response.

**Comment by htorohn** [comment]
I'm still unable to use million on my apps.
