### ISSUE TITLE
Feedback for “Installation” - double up on items in right side bar

### ISSUE THREAD

**Issue by jakeymoreland** [aidenybai/million#1022]
![Screenshot 2024-04-17 at 10 59 48 PM](https://github.com/aidenybai/million/assets/21028934/c0c121f6-d4fa-42d8-b902-9648084b1255)
![Screenshot 2024-04-17 at 10 59 48 PM](https://github.com/aidenybai/million/assets/21028934/ff9a5c8a-f812-46d6-8c5c-0c01e16746c6)
sorry; just caught my eye whilst i was adding million to remix :P

**Comment by tobySolutions** [comment]
Hey there, @jakeymoreland; I am on the page that you were on with this feedback  and I don't have that issue at all.

<img width="1536" alt="Screenshot 2024-04-18 at 08 34 02" src="https://github.com/aidenybai/million/assets/96334363/7fc3a938-824a-4ac0-b21e-5c58a7d232bb">

**Comment by jakeymoreland** [comment]
right side is doubled up "On this page" underneath "Install manually"? is this the desired effect? one links to 
`#install-millionjs`

one links to `#install-millionjs-1`

**Comment by tobySolutions** [comment]
> right side is doubled up "On this page" underneath "Install manually"? is this the desired effect? one links to `#install-millionjs`
> 
> one links to `#install-millionjs-1`

Nope, there should only be one. I have one on my screen. I'm not completely sure why you have that. Can you maybe send a video or something?
