### ISSUE TITLE
🛠 Tooling: Stop auto-closing not-actually-stale issues

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [aidenybai/million#1026]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

#867 as an example: the GitHub stale bot is closing issues that don't have activity for a week. That includes issues still waiting for someone to look at them. That doesn't seem right to me.

**Comment by tobySolutions** [comment]
Thank you very much for this @JoshuaKGoldberg, I'll inform the team of this and have them take a look at this. I am sorry for any inconvenience caused.

**Comment by tobySolutions** [comment]
Thank you for this @JoshuaKGoldberg!! Really appreciate it 🙏. I will inform the team of this and will have it looked into or I can just make a PR as well.

**Comment by aidenybai** [comment]
@JoshuaKGoldberg so sorry, this took way too long. i've AXED the stale bot and it's gone forever

**Comment by JoshuaKGoldberg** [comment]
Woop, thanks!
