### ISSUE TITLE
📝 Documentation: Typo in the docs while doing manual installation

### ISSUE THREAD

**Issue by palashmon** [aidenybai/million#1038]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

## Description

In the step 2 inside the [Manual Installation](https://million.dev/docs#manual-installation) for Webpack, it is mentioned that:

```js
const million = require("@million/lint");
module.exports = {
  plugins: [MillionLint.webpack()],
};
```

## Expected Behavior:

The installation should proceed successfully without any errors.

## Actual Behavior:

An error message is displayed after running the dev server, stating "ReferenceError: MillionLint is not defined".

**Comment by aidenybai** [comment]
Thanks!
