### ISSUE TITLE
Doesn't correctly handle NextJS config function

### ISSUE THREAD

**Issue by sambauers** [aidenybai/million#1040]
### What version of `million` are you using?

1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

My NextJS config is setup as a function, as outlined here - https://nextjs.org/docs/app/api-reference/next-config-js

E.g.:
```js
const MillionLint = require('@million/lint')

const nextConfig = async (phase, { defaultConfig }) => {
  const config = {
    /* config options here */
  }
  return config
}

module.exports = MillionLint.next({ rsc: true })(nextConfig)
```

Looking at the source of Million, it appears that this is not a supported configuration option.

### What's the expected result?

I expected Million to accept the configuration.

### Link to Minimal Reproducible Example

http://example.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sambauers** [comment]
I quickly realised the workaround. Simply wrap the return for the function instead. E.g.:

```js
const MillionLint = require('@million/lint')

const nextConfig = async (phase, { defaultConfig }) => {
  const config = {
    /* config options here */
  }
  return MillionLint.next({ rsc: true })(config)
}

module.exports = nextConfig
```

It would be good to document this.

**Comment by johnjyang** [comment]
Noted. Thanks for providing the snippet!
