### ISSUE TITLE
📝 Documentation: Can I disable logging `[Million Lint] Ingested ${n} events` in browser console?

### ISSUE THREAD

**Issue by alissa-tung** [aidenybai/million#1047]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Thank you for developing this. Seems that the current document is leak of information about "Can I disable logging `[Million Lint] Ingested ${n} events` in browser console?"

**Comment by charlieforward9** [comment]
Please get to this soon, seems extremely simple.

**Comment by NisargIO** [comment]
Hey @charlieforward9 @alissa-tung, we removed this log in the latest version! Can you try running the setup script `npx million@latest`. Once it's done, please restart your VSCode/Cursor. Let me know if that works for you!

**Comment by alissa-tung** [comment]
> Hey @charlieforward9 @alissa-tung, we removed this log in the latest version! Can you try running the setup script `npx million@latest`. Once it's done, please restart your VSCode/Cursor. Let me know if that works for you!

Thank you
