### ISSUE TITLE
million failed to get started

### ISSUE THREAD

**Issue by vgseven** [aidenybai/million#1053]
### What version of `million` are you using?

-

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Windows 11

### What browser are you using?

Arc

### Describe the Bug

![Screenshot 2024-06-04 130138](https://github.com/aidenybai/million/assets/81641747/45b50aaf-aded-48ab-9c21-9b36d4018786)

### What's the expected result?

install app

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
@vgseven pushed a patch, try again?

**Comment by vgseven** [comment]
it's working now @aidenybai thx, but why it's now work with `pnpm dlx million@latest` or `bunx million@latest` why only `npx million@latest` ?
