### ISSUE TITLE
Failed to ingest events

### ISSUE THREAD

**Issue by jackbsteinberg** [aidenybai/million#1057]
# Failed to ingest events .catch()

Machine ID: `677a682a-8ec3-4104-8822-81b2e901a821`

> [!NOTE]
> [Book a call](https://cal.com/aiden)

| key | value |
| --- | ----- |
| id | juwue6h7cgq1717531973766 |
| url | http://localhost:3000/home/015a64e1-9aa5-4fd6-ab30-4603f9173f07 |
| wifi | 4g |
| cpu | 11 |
| mem | 8 |
| gpu | ANGLE (Apple, ANGLE Metal Renderer: Apple M3 Pro, Unspecified Version) |
| time | 1717531981872 |
| items | 0 |
| bytes | 0 |

**Comment by aidenybai** [comment]
Fixed :) Thanks Jack
