### ISSUE TITLE
bug: NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by dev15Aditya** [aidenybai/million#1058]
I want to integrate million.js compiler in Next.js application. I have added "const millionConfig = { auto: true,}" When I run the application I see the list of the component which have become fast and by How much percent, but when I open browser I get  
Unhandled run time error.
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
I have done what is said in docs. And also if I want to use Manual Mode and when I wrap component around block hook, I am getting issue while passing the props

**Comment by Campin10** [comment]
@dev15Aditya are you able to solve the issue with million.js ? Thanks

**Comment by dev15Aditya** [comment]
yes I found the solution.
