### ISSUE TITLE
Failed to connect to VSCode

### ISSUE THREAD

**Issue by sardorazimov** [aidenybai/million#1082]
# Failed to connect to VSCode !data.ok

Machine ID: `b9a9f87a-ddad-468b-be8f-32efa90c3096`

> [!NOTE]
> [Book a call](https://cal.com/aiden)

| key | value |
| --- | ----- |
| id | w4gjlyf7o21721418186738 |
| url | http://localhost:3000/ |
| wifi | 4g |
| cpu | 8 |
| mem | 8 |
| gpu | ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11) |
| time | 1721418189799 |
| items | 163 |
| bytes | 561 |

**Comment by aidenybai** [comment]
duplicate
