### ISSUE TITLE
onMouseEnter and onMouseLeave not working

### ISSUE THREAD

**Issue by TalhaAksoy** [aidenybai/million#1116]
### What version of `million` are you using?

3.1.11

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn , npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

when i activate million in my project 

`
<div
          onMouseEnter={() => { setMouseEnter(true); }}
          onMouseLeave={() => { setMouseEnter(false); }}
          className="flex flex-col justify-center relative dark:bg-agteks-blue-mainsecondary bg-agteks-light-bg-200 rounded-xl"
        >

`

this mouse enter and leave event not work

### What's the expected result?

work onMouseEnter like dom events

### Link to Minimal Reproducible Example

i cant share 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
please provide a minimally reproducable example. I can't reproduce this problem
