### ISSUE TITLE
Failed to ingest events

### ISSUE THREAD

**Issue by envindavsorg** [aidenybai/million#1121]
# Failed to ingest events .catch() Timeout

Machine ID: `f21ad435-30ac-41b0-8058-dff6801e528b`

> [!NOTE]
> [Book a call](https://cal.com/aiden)

| key | value |
| --- | ----- |
| id | YIZuvpeCTcQLtw5Zdh2bp |
| url | http://localhost:2702/ |
| wifi | 4g |
| cpu | 8 |
| mem | 8 |
| gpu | ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version) |
| time | 1726321906661 |
| items | 8942 |
| bytes | 15138 |

- 77dad7df-041b-4a6e-a171-18df209852f71726256479714 (localhost:52921 - true)
- 77dad7df-041b-4a6e-a171-18df209852f71726256479714 (0.0.0.0:52921 - true)

**Comment by aidenybai** [comment]
Hi @envindavsorg , we've just deployed a fix for you. Can you try running the setup script npx million@latest. Once it's done, please restart your VSCode/Cursor. Let me know if that works for you!

**Comment by envindavsorg** [comment]
Everything works !

**Comment by aidenybai** [comment]
Awesome!
