### ISSUE TITLE
Request: support setting data/aria attributes

### ISSUE THREAD

**Issue by rk** [aidenybai/million#113]
**Is your feature request related to a problem? Please describe.**

So, I've been trying to figure out how to associate nodes created by million with data in the rest of the script. Note that for this use-case I'm creating a menu builder using dragula to allow drag and drop ordering/nesting. As such, it's simpler to leverage the DOM to maintain the tree than in-memory within the script. Just query the parent wrapper, then walk down the nodes/children to reassemble the data. Because there are multiple layers and attributes to track, it's simplest to keep this data in a data-attribute.

```html
<div class="menu-node" data-config='{"title":"foo","url":"/bar/","publish":true}'>
  <div class="menu-item">
    <span class="menu-item-title">foo</span>
    <span class="menu-item-url">/bar</span>
    <span class="menu-item-publish icon icon-eye"></span>
  </div>
  <!-- child nodes go here -->
</div>
```

Technically, setting a property like "data-config" works but I'm unsure how it'll be persisted. But this is a symptom of a another problem:

  - What if I added a link and need `data-toggle="modal" data-target="#editModal"` to be set on each item for a Bootstrap modal dialog? (I know I can set a `.js-edit-modal` class and an href of `#editModal` with a tiny bit of script to alleviate this.) I'm sure there are other 3rd party libraries which need data attributes that we cannot work around.
  - There is no way to assign arbitrary attributes because `element.attributes` is read-only. This also means that we cannot set `aria-` attributes for accessibility!

**Describe the solution you'd like**
I'm pretty sure we need a way to set arbitrary attributes at least, which would also handle data attributes.

**Describe alternatives you've considered**
For my own use-case I've considered using a WeakMap to maintain the data. But with `patch()`, but making it work with both an HTMLElement and a VNode is more complex. So I've thought about generating a random key to pass into patch, and using that string to associate it with a Map (it loses the automatic deletion of a WeakMap however).

No matter what alternative I'm considering, it's still more complex than a data attribute.

**Comment by aidenybai** [comment]
I think the use case in this specific case when paired with Dragula may not be the best use case for Million - in terms of dragging a dropping, a "Virtual DOM" way of doing it is modifying the placement based on the state. DOM modifications without using the designated `patch` function is generally an antipattern.

I've really never used `data-` attributes in any meaningful capacity, so let me know if I'm missing something. I think you can just set the props of the new vnode to `{ data-toggle: ..., data-target: ... }` and it should work out fine.

Again let me know if I'm misunderstanding.

**Comment by rk** [comment]
I understand if supporting state in the DOM (like drag and drop) isn't in Million's use-case.

However, note that the library just doesn't work when setting `data-` or `aria-` attributes. I tested this before reporting. Just open the inspector here and selected a node, then `$0["data-test"] = "foo"` in the console. It'll write the property, but not to a data attribute. That same behavior goes to an aria attribute. Attributes !== properties!

Here's a JSBin example, you can inspect the target node: https://jsbin.com/ticodocoti/edit?html,css,js,output

These are features that should be supported, so that other libraries can interact with data attributes for additional behaviors, and so that the generated content can be more accessible with aria attributes.

**Comment by aidenybai** [comment]
Thanks! I am able to repro this issue and I implemented a solution in https://github.com/aidenybai/million/commit/c9902dbe78be21589eb8d96a2dbe42ad74fd8ea7. It'll be pushed in the next minor version. Thanks so much for reporting!
