### ISSUE TITLE
Failed to ingest events

### ISSUE THREAD

**Issue by quiint** [aidenybai/million#1136]
# Failed to ingest events .catch() Failed to fetch

Machine ID: `mil-7970a985-b514-4f61-b843-66bf2fbc2979`

> [!NOTE]
> [Book a call](https://cal.com/aiden)

| key | value |
| --- | ----- |
| id | pq_mdNqM62DZ2tSh5CbKV |
| url | https://filmedapp.local/dashboard |
| wifi | 4g |
| cpu | 8 |
| mem | 8 |
| gpu | ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version) |
| time | 1727805287285 |
| items | 0 |

**Comment by aidenybai** [comment]
Hey, looks like your URL is on a different host than `localhost`, this can cause issues. Happy to book a call to fix it for you: https://cal.com/aiden

**Comment by quiint** [comment]
oh, it's just because its not on localhost? not that big of an issue, but that's interesting and I wonder why that doesn't work
thanks!
