### ISSUE TITLE
Failed to ingest events

### ISSUE THREAD

**Issue by ruslanvasylev** [aidenybai/million#1139]
# Failed to ingest events .catch() Timeout

Machine ID: `mil-6f4e6f12-0c3e-45ce-9d0e-d7b4c86bb37b`

> [!NOTE]
> [Book a call](https://cal.com/aiden)

| key | value |
| --- | ----- |
| id | 5jC275kj77GXV0Fn0mfy3 |
| url | http://localhost:3000/quickstart |
| wifi | 4g |
| cpu | 16 |
| mem | 8 |
| gpu | ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11) |
| time | 1727889961522 |
| items | 0 |

**Comment by aidenybai** [comment]
@ruslanvasylev  hey, looks like the compiler server isn't responding correctly. Can you book a 15m call with me? https://cal.com/aiden

**Comment by ruslanvasylev** [comment]
Awesome, it's fixed! Thanks so much, Aiden!

**Comment by yonycalsin** [comment]
@ruslanvasylev what was the problem? and how did you fix it?

**Comment by iamyegor** [comment]
Ruslanchik, can you please share how you fixed it?
