### ISSUE TITLE
Failed to ingest events

### ISSUE THREAD

**Issue by tavernkeep** [aidenybai/million#1140]
# Failed to ingest events .catch() Failed to fetch

Machine ID: `mil-1da6f7ff-aa2b-4370-ba86-e245fc22f80d`

> [!NOTE]
> [Book a call](https://cal.com/aiden)

| key | value |
| --- | ----- |
| id | N23be18WNaq2-uMW4h8Di |
| url | https://10.117.140.187:3000/inbox/active |
| wifi | 4g |
| cpu | 4 |
| mem | 8 |
| gpu | ANGLE (VMware Inc., llvmpipe (LLVM 6.0 256 bits), OpenGL 2.1) |
| time | 1727914942939 |
| items | 19 |

**Comment by iamyegor** [comment]
@tavernkeep How did you fix it???
