### ISSUE TITLE
Update to new @million/lint 1.0.5 using pnpm

### ISSUE THREAD

**Issue by nasraldin** [aidenybai/million#1141]
### What version of `million` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

V

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

When updated to 1.0.5 i can not install pkgs if i removed the node_modules or upgrade pkgs due to

 pnpm i
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@million/shared@workspace:*" is in the dependencies but no package named "@million/shared" is present in the workspace

This error happened while installing the dependencies of @million/lint@1.0.5

### What's the expected result?

Should i can install pkgs with pnpm i

### Link to Minimal Reproducible Example

$

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mikesprague** [comment]
Seeing the same thing for `1.0.6` (using `npm`). Stack trace from `npm` logs below:

```
17 silly packumentCache full:https://registry.npmjs.org/@million%2flint cache-miss
18 http fetch GET 200 https://registry.npmjs.org/@million%2flint 14ms (cache hit)
19 silly packumentCache full:https://registry.npmjs.org/@million%2flint set size:1154250 disposed:false
20 silly placeDep ROOT @million/lint@1.0.6 REPLACE for: project-name@0.39.3 want: 1.0.6
21 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
21 verbose stack     at unsupportedURLType (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/npm-package-arg/lib/npa.js:310:15)
21 verbose stack     at fromURL (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/npm-package-arg/lib/npa.js:367:13)
21 verbose stack     at Function.resolve (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/npm-package-arg/lib/npa.js:83:12)
21 verbose stack     at /Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1008:39
21 verbose stack     at run (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
21 verbose stack     at /Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
21 verbose stack     at new Promise (<anonymous>)
21 verbose stack     at callLimit (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
21 verbose stack     at #buildDepStep (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1022:11)
21 verbose stack     at async Arborist.buildIdealTree (/Users/ms388/.volta/tools/image/npm/10.8.3/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
22 error code EUNSUPPORTEDPROTOCOL
23 error Unsupported URL Type "workspace:": workspace:*
```

**Comment by shibli21** [comment]
i am facing same issue ! have you got any solution ?

**Comment by aidenybai** [comment]
@shibli21 @mikesprague @nasraldin fixed in latest version! `npx million@latest`. If that continues to fail, then please book a call with me https://cal.com/aiden/support

**Comment by mikesprague** [comment]
@shibli21 Working for me now. Thanks for the quick fix!

**Comment by nasraldin** [comment]
@aidenybai  thank you for your support. Is working as expected now.
