### ISSUE TITLE
"Enable production mode to use Million Lint in production. This is potentially dangerous" error message even after enabling it

### ISSUE THREAD

**Issue by anaclumos** [aidenybai/million#1144]
### What version of `million` are you using?

1.0.9

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

```diff
import MillionLint from "@million/lint";
import withBundleAnalyzer from "@next/bundle-analyzer";

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  logging: {
    fetches: {
      fullUrl: true,
    },
  },
};

const bundleAnalyzer = withBundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});

export default MillionLint.next({
+ production: true,
  rsc: true,
})(bundleAnalyzer(nextConfig));
```

Still gives me 

```
Enable production mode to use Million Lint in production. This is potentially dangerous (contact: aiden@million.dev)
```

### What's the expected result?

The error should go away.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-oivvfn?file=next.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
Hi, production mode is not supported at this time. This seems to be an unintuitive error message, we'll fix it in the next release!
