### ISSUE TITLE
Jetbrains Intellij IDEA Support

### ISSUE THREAD

**Issue by Charismara** [aidenybai/million#1146]
### Describe the feature

Million looks like a really handy tool and we would love to use it but we're mostly using Intellij instead of VSCode as IDE. Is there any chance that Million will support Intellij?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by alkanna** [comment]
Duplicate of https://github.com/aidenybai/million/issues/1044, you might want to close this @Charismara
