### ISSUE TITLE
Feature: patch return new dom element

### ISSUE THREAD

**Issue by hyrious** [aidenybai/million#119]
### Is your feature request related to a problem? Please describe.

```markdown
If we patch a vnode to some element with different tag name,
the original element will be removed and be replaced with a new element.
The new element can not be accessed unless we do a `querySelector`.
```

### Describe the solution you'd like

```markdown
Let `patch()` returns the new element, so that we can keep a reference
to the real dom.
```

### Describe alternatives you've considered

```markdown
None.
```

**Comment by aidenybai** [comment]
Prototype implementation in #120, feel free to check it out. I'll merge it later if there are no issues. Thanks for the feature request
