### ISSUE TITLE
Bug: SVG not created with correct namespaceURI

### ISSUE THREAD

**Issue by rk** [aidenybai/million#127]
### Describe the bug

We use Icomoon (icomoon.io) for the icons in the app I'm working on, specifically with the SVG spritesheet option. Icons use markup like:

```html
<svg class="icon icon-bell">
  <use xlink:href="/fonts/icomoon/symbol-defs.svg#icon-bell" />
</svg>
```

From what I'm reading of the documentation, the million version should look like:

```javascript
function icon(iconName) {
    return svg(m('svg', {
        className: `icon icon-${iconName}`
    }, [
        // SVG 2 support means that HREF should be enough now;
        // otherwise we may need an xlinkHref setter for setAttributeNS
        m('use', { href: `/fonts/icomoon/symbol-defs.svg#icon-${iconName}` })
    ]));
}
```

From my research into JSX that should look like:

```jsx
function icon(iconName) {
    return (
        <svg className={`icon icon-${iconName}`}
             xmlns="http://www.w3.org/2000/svg"
             xmlnsXlink="http://www.w3.org/1999/xlink">
            <use xlinkHref={`/fonts/icomoon/symbol-defs.svg#icon-${iconName}`} />
        </svg>
    );
}
```

However, the icon does not display. The created element's `$0.namespaceURI` is incorrect.

### To Reproduce

Use one of the functions above and inspect the resulting node. I noticed that `$0.namespaceURI` in the console returns `http://www.w3.org/1999/xhtml`.

### Expected behavior

The created nodes should have the correct SVG namespace. Functionally, the output should be roughly equivalent to this plain JS function:

```javascript
function icon(iconName) {
    let svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    let use = document.createElementNS('http://www.w3.org/2000/svg', 'use');

    svg.setAttribute('xmlns:xlink','http://www.w3.org/1999/xlink');
    svg.setAttribute('class', ['icon', 'icon-' + iconName].join(' '));
    use.setAttributeNS('http://www.w3.org/1999/xlink', 'href', '/fonts/icomoon/symbol-defs.svg#icon-' + iconName);
    svg.appendChild(use);

    return svg;
}
```

I'm not super worried about `setAttributeNS` support for the JSX style `xlinkHref` attribute, because SVG2 support is pretty broad. Browsers should support `<use href="" />` across the board now.

### Screenshots

I'll attach a screen shot in a comment, since drag/drop doesn't work on this field.

<img width="164" alt="Screen Shot 2021-09-29 at 8 39 13 AM" src="https://user-images.githubusercontent.com/58199/135281097-d8174b3c-3929-40e9-87f3-de34c480c3ea.png">

### Operating System

MacOS Catalina 10.15.7 (19H1419)

### Browser

Chrome 94; FireFox 92

### Additional context

I'm actually working on adding a new feature with heavy front-end reactivity using million, so I have a lot of things to test in a real world scenario. I'll probably find a variety of things as I implement the feature. It was Vue3 or Million, and I decided to give million a try. 😄

**Comment by aidenybai** [comment]
Should be working in the commit that is referenced. This is really good to know! Million hasn't really been seriously pressure tested, so these issues mean a ton!

**Comment by rk** [comment]
So far, my Renderer for the page's data is 426 lines long. Of that, 256 lines are JSX/million. I'm even using million's onchange/onclick event handler binding, which was a little tricky at first. I'm completely impressed by how fast million is with reflecting changes to the VDOM.

I have a sort of `ViewModel <- (message bus) -> Million` architecture set up. In fact, sorting and then `patch()`-ing the DOM only took (in Chrome, across 563 DOM elements):

- 29ms scripting
- 10 ms rendering
- 3 ms painting

Given that I am currently rebuilding the entire VDOM representation freshly (no joke!) with each update/render, the 29ms is so fast to swap that it feels instantaneous. We'll see how it goes during real world testing, once the feature is complete enough to run through QA processes.

Even as early as million is in development, it feels very stable. Very well done aidenybai!

**Comment by aidenybai** [comment]
Should be fixed in https://github.com/aidenybai/million/releases/tag/v0.6.3!
