### ISSUE TITLE
Bug: inconsistent performance when adding this extra header to page

### ISSUE THREAD

**Issue by rk** [aidenybai/million#137]
### Describe the bug

In the timesheet entries, I have the system set up to render the rows and it all works great. DOM operations for insert/delete/update are roughly 30ms total. Then in some contexts I need to add a header that summarizes the data for the timesheet. It's really just status and totals, because the totals may update when changes are made and that feedback can be helpful to the user.

Please note that generating the VNode tree takes approximately 1ms both with and without the following header info. When the header is generated it adds 90ms - 400ms to the DOM operations, dependent on how its rendered. Upgrading to v0.6.4 has dropped the times from about 300ms - 550ms originally, so it _is_ better than before.

Also note that all interpolated areas/values in the following JSX code are already converted to strings. No additional VNodes are created, just these text nodes.

#### Original form (180ms average increase in time):

```jsx
<div className="row mb-4">
    <div className="col-auto">
        <strong>User</strong>
        <br />
        {sheet.user.name}
    </div>
    <div className="col-auto">
        <strong>Time Sheet Period</strong>
        <br />
        {sheet.week_start.format()} - {sheet.week_end.format()}
    </div>
    <div className="col-auto">
        <strong>Total Points</strong>
        <br />
        {total_points} Points
    </div>
    <div className="col-auto">
        <strong>Total Hours</strong>
        <br />
        {total_hours} Hours
    </div>
    <div className="col-auto">
        <strong>Status</strong>
        <br />
        <span className={statusClasses}>{sheet.status}</span>
    </div>
</div>
```

#### "Optimized" form (90ms average increase in time):

```jsx
<div className="row mb-4">
    <div className="col-auto">
        <div className="text-bold">User</div>
        <div>{sheet.user.name}</div>
    </div>
    <div className="col-auto">
        <div className="text-bold">Time Sheet Period</div>
        <div>{sheet.week_start.format()} - {sheet.week_end.format()}</div>
    </div>
    <div className="col-auto">
        <div className="text-bold">Total Points</div>
        <div>{total_points} Points</div>
    </div>
    <div className="col-auto">
        <div className="text-bold">Total Hours</div>
        <div>{total_hours} Hours</div>
    </div>
    <div className="col-auto">
        <div className="text-bold">Status</div>
        <div><span className={statusClasses}>{sheet.status}</span></div>
    </div>
</div>
```

I think the issue relates to checking text nodes, as well as empty nodes like `<br/>` tags.

I have also noticed a performance hit in a different area, related to updating select and option tags. (Inserting/updating a select with 1000 items can take 1 second.) But I can do a little checking and file a separate issue for that.

### To Reproduce

The VNode tree looks a bit like this:

- Wrapper element (never changes)
  - "Sheet Header" (see above)
  - "Card" element
    - Header (never changes)
    - [ multiple rows here ]
    - Footer (never changes)
      - Add Type 1 (button)
      - Add Type 2 (button)

As you'd guess, the bulk of the changes are in the "multiple rows" area. When the "Sheet Header" is included in the context, performance immediately degrades from a stable average of 30ms.

### Expected behavior

I expected only a minor performance hit, if at all.

### Screenshots

Not really visually related.

### Operating System

MacOS Catalina 10.15.7 (19H1419)

### Browser

Chrome 94; FireFox 93

### Additional context

If it would help, I could try recording flame graphs.

Performance hits between contexts that I understand and expect for the moment:

- Select and Option tags have varied values and counts for each; I think it can account for up-to 10ms loss right now. (Now that I have accounted for the 1k element select per row issue.)

**Comment by aidenybai** [comment]
Looking through the code you provided, I can't pinpoint any glaringly obvious things that could reduce performance of the renderer. This just might be an underlying issue with the Virtual DOM model in general, and I recommend you try out the `key` prop ([this](https://million.js.org/functions/m#optimization-via-keys) and [that](https://million.js.org/functions/m#:~:text=VFlags.ONLY_KEYED_CHILDREN%3A%202).

I'll try to repro this issue tonight and I'll get back to you if I can find a bug and a fix.

**Comment by aidenybai** [comment]
> Would it be possible to add a new `VDeltaOperationTypes` item of `IGNORE`? I do know certain things like what rows won't change. And I can make it so that only the newest rows are INSERT and the changed ones UPDATE, and skip the ones which haven't changed. Just an idea for optimizing larger/longer UIs.

You can manually add an ignore=true prop to an element to completely skip rendering on it.
