### ISSUE TITLE
Bug: why does using keys produce seemingly random duplicates?

### ISSUE THREAD

**Issue by rk** [aidenybai/million#141]
### Describe the bug

The deeper you go, the more likely you are to hit this issue. For instance, a top-level wrapper with `ONLY_KEYED_CHILDREN` and unique keys appears to work fine. But nest it within another element as a wrapper, and duplicates start appearing after adding maybe 3 items.

Reproducing this in a basic page like this was a nightmare. 🥵 I still haven't actually reproduced the issue I was originally troubleshooting, which was adding 6-8 duplicate items when inserting one (deleting it from the context/state deleted all 6-8 dupes of the row).

Here's an example: 

```html
<!DOCTYPE html>
<body>
<div id="app"></div>

<script type="module">
  import {
    m,
    patch,
    VFlags
    /* or any other exports you want to access */
  } from 'https://unpkg.com/million?module';

  const format = new Intl.DateTimeFormat('en-us', { dateStyle: 'short', timeStyle: 'medium' });
  let dates = [];

  function render() {
    dates.push(new Date());

    let vdom = m(
      'div',
      { id: "app" },
      [
        m('div', undefined, dates.map(dt => m('div', { key: dt.getTime().toString() }, [format.format(dt)])), VFlags.ONLY_KEYED_CHILDREN)
      ]
    );

    console.log('render', vdom);

    patch(document.getElementById('app'), vdom);
  }

  setInterval(render, 1000);
  render();
</script>
</body>
```

To "fix" this behavior, just remove the `VFlags.ONLY_KEYED_CHILDREN` and the default diffing works fine. Even more strange: remove the `.wrapper` element and make the date entries direct children of the `#app` element and it works again.

### To Reproduce

This behavior appears to be part of the diffing when using keys with ONLY_KEYED_CHILDREN. What confuses me is why it only happens _after_ it's nested below the top-level. I've spent time trying to review the children driver for diffing, and haven't noticed anything obvious.

To reproduce this:

* Nest the children one level deeper than the top, or more.
* Add keys on each element.
* Add `VFlags.ONLY_KEYED_CHILDREN` on the parent/wrapper node.

### Expected behavior

Yeah, only 1 item should be added per keyed item.

### Screenshots

<img width="249" alt="Screen Shot 2021-10-22 at 12 10 11 PM" src="https://user-images.githubusercontent.com/58199/138495995-aa70190a-ee30-4ad4-9058-b9054c2e436f.png">

### Operating System

MacOS Catalina 10.15.7 (19H1419)

### Browser

Chrome 94; FireFox 93

**Comment by aidenybai** [comment]
Fixed in `0.6.7`
