### ISSUE TITLE
bug: Something strange on https://millionjs.org/ in Firefox

### ISSUE THREAD

**Issue by stoivo** [aidenybai/million#176]
**Describe the bug**
Something strange with scrollbar on homepage
![Million 2022-04-07 10-06-38](https://user-images.githubusercontent.com/3492040/162151902-47c8f3fa-9685-45d9-be8b-9b166d27baf6.png)

**To Reproduce**
1. Open Firefox 98.0.2 om MacOS
11. Go to 'https://millionjs.org/'

**Comment by aidenybai** [comment]
For some reason I cannot repro this error on Firefox 98.0.2 on MacOS, do you have any extensions installed that may be affecting the visuals?

**Comment by Posandu** [comment]
![image](https://user-images.githubusercontent.com/76736580/162575033-7b3c2ce6-a5eb-4a59-bc33-e6745189836d.png)
can reproduce in the latest Firefox in windows

**Comment by aidenybai** [comment]
I've removed the grid lines on the doc, could you try and see if the issue persists? @Posandu @stoivo

**Comment by stoivo** [comment]
issue seems resolved
