### ISSUE TITLE
feat: Router to highjack forms as well as anchors

### ISSUE THREAD

**Issue by dperrymorrow** [aidenybai/million#178]
**Is your feature request related to a problem? Please describe.**
would be super helpful if router handled form submissions as well. I think this would make it feel much more "SPA like" than just doing anchor links. Many times this is what folks resort to a SPA for dealing with form validation ect...

**Describe the solution you'd like**
Similar to how it handles clicks on the window, if it handled submit. 
```javascript
window.addEventListener("submit", async (event) => {
  event.stopPropagation()
  ev.preventDefault()

  const body = Array.from(new FormData($form)).reduce((acc, [key, val]) => {
    acc[key] = val
    return acc
  }, {})

  const opts = {
    method: $form.method,
    headers,
    redirect: 'follow'
  }

  let url = $form.action

  if ($form.method.toLowerCase() === 'get') url += '?' + new URLSearchParams(body)
  else opts.body = JSON.stringify(body)

  const request = new Request(url, opts)
  const res = await fetch(request)
  // parse the response and patch the DOM....
})

**Comment by dperrymorrow** [comment]
Im happy to help with a PR if this is something you are interested in pursuing. Great library BTW!! There are not many "modern" takes on Virtual DOM out there currently

**Comment by Borrus-sudo** [comment]
@dperrymorrow we will work on it in issue #177, it would be cool if we could take that discussion there. Plus we would like if you could suggest some more points!

**Comment by Borrus-sudo** [comment]
Happy to receive the PR for this!

**Comment by Borrus-sudo** [comment]
This would be a perfect fit for the greater vision of million/router for making subsequent navigations to page in MPA in SPA!

**Comment by aidenybai** [comment]
Agreed with @Borrus-sudo! I like the ideas presented here. Closing in favor of merging to #177
