### ISSUE TITLE
bug: How to tranform raw HTML to VElement

### ISSUE THREAD

**Issue by HerbertHe** [aidenybai/million#181]
**Describe the bug**
I am developing a markdown renderer with vdom. As we all know, `highlight.js` is used to help us to highlight the source code. So I want to use it in the renderer, I try to use the following codes to meet my goal:

```ts
import { html } from "million/html"

export const fromStringToVNode = (content: string): VNode[] => {
    const h = html`${content}`
    if (Array.isArray(h)) {
        return h
    }

    return [h]
}
```

> But I have not got the correct VNode but HTML string

Or,

```ts
import { fromStringToDomNode, fromDomNodeToVNode } from "million/ssr"

export const fromStringToVNode = (content: string): VNode => {
  return fromDomNodeToVNode(fromStringToDomNode(content))
}
```

> But I have got the error `Uncaught (in promise) TypeError: Cannot read properties of null (reading '__m_old_vnode')`

So I want to know about how to transform raw HTML string (Maybe with `\n`) to VElement?

**To Reproduce**
1. import `highlight.js`
2. transform any TypeScript codes via `highlight.js`
3. input the codes before
4. Run

**Expected behavior**
Return correct VElement array

**Device (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Edge Chromium
 - Version [e.g. 22] Latest

**Additional context**

**Comment by aidenybai** [comment]
I'm not able to repro the `Uncaught (in promise) TypeError: Cannot read properties of null (reading '__m_old_vnode')`. Could you try bumping to the latest version of Million to see if the issue persists?

Here is my repro code:

```js
const code = hljs.highlight('<h1>Hello World!</h1>', { language: 'xml' }).value;
const vnode = fromDomNodeToVNode(fromStringToDomNode(`<div>${code}</div>`));

console.log(code);
console.log(vnode);

render(document.body, vnode);
```

<details>
<summary>Click to view console log</summary>

<pre><code>

<span class="hljs-tag">&lt;<span class="hljs-name">h1</span>&gt;</span>Hello World!<span class="hljs-tag">&lt;/<span class="hljs-name">h1</span>&gt;</span>

{
    "tag": "div",
    "props": {},
    "children": [
        {
            "tag": "span",
            "props": {
                "class": "hljs-tag"
            },
            "children": [
                "<",
                {
                    "tag": "span",
                    "props": {
                        "class": "hljs-name"
                    },
                    "children": [
                        "h1"
                    ],
                    "flag": 5
                },
                ">"
            ],
            "flag": 1
        },
        "Hello World!",
        {
            "tag": "span",
            "props": {
                "class": "hljs-tag"
            },
            "children": [
                "</",
                {
                    "tag": "span",
                    "props": {
                        "class": "hljs-name"
                    },
                    "children": [
                        "h1"
                    ],
                    "flag": 5
                },
                ">"
            ],
            "flag": 1
        }
    ],
    "flag": 1
}
</code></pre>

</details>

<details>
<summary>Click to view document body</summary>

<pre><code>
<div><span class="hljs-tag">&lt;<span class="hljs-name">h1</span>&gt;</span>Hello World!<span class="hljs-tag">&lt;/<span class="hljs-name">h1</span>&gt;</span></div>
</code></pre>

</details>

**Comment by aidenybai** [comment]
So `htm` is just a helper function to create vnodes. `htm` may support fragment because it is generalized for all Virtual DOM-based libraries (e.g. react, preact, etc.), but Million does not at the top-level node.

For instance, `htm` may generate:

```js
html`<div></div><div></div>`
// [divVNode, divVNode]
```

And you can interpolate that within Million children, but not at top level:

```js
const fragment =  [divVNode, divVNode];
render(document.body, fragment); // DOESN'T WORK

render(document.body, html`<div>${fragment}</div>`) // works, fragment is not at top level

**Comment by HerbertHe** [comment]
Thanks for your explanation, I got it! I will try to fix this issue in my code~
