### ISSUE TITLE
feat: `diff` function to support exporting the difference between the two vnodes

### ISSUE THREAD

**Issue by HerbertHe** [aidenybai/million#187]
**Describe the solution you'd like**
I found that nearly all of the vdom frameworks support effecting the dom directly, but don't support exporting the difference between the two vnodes. I thought maybe it would be useful when we want to get difference between the two vnodes and render them to the website for visualization by the custom styles, just like the git diff styles that help us to diff the two versions of our code.

I thought that we can set the `diff` of `props` for all vnodes, and export the two diffed vnodes tree as result. Maybe it would be very interesting and help us know where we have updated.

**Comment by aidenybai** [comment]
There is existing functionality for exporting diffs with the `diff` function: 

You can access effects with `data.effects`. An effect looks like:

```ts
export interface Effect {
  type: EffectTypes;
  el: DOMNode;
  flush: () => void;
}
```

I'm not exactly sure how the diff functionality for the highlighting will work. I think it would be easier to provide the `newVNode` and `oldVNode` in the effect, that way the developer can implement the highlight diff

**Comment by aidenybai** [comment]
Hey! I seen you've made some issues to the Million repo, If you'd be willing I'm extending an invitation for you to become a collaborator :)

Link: [aidenybai/million/invitations](https://github.com/aidenybai/million/invitations)
