### ISSUE TITLE
feat: something like Svelte actions

### ISSUE THREAD

**Issue by gustavopch** [aidenybai/million#190]
**Is your feature request related to a problem? Please describe.**
Not applicable.

**Describe the solution you'd like**
I'd like to use something like Svelte actions in Million, e.g.:
```js
// This is an action
const tooltip = (node, { text }) => {
  // Mount the tooltip (i.e. create)

  return {
    update: ({ text }) => {
      // Update the tooltip with its new text
    },
    destroy: () => {
      // Unmount the tooltip
    },
  }
}

// This is the action being used
html`<button ${tooltip({ text: 'Some explanation' })}>Do something</button>`
```

**Describe alternatives you've considered**
Maybe it can be implemented with a driver? Not sure yet, I discovered Million less than 24h ago.

**Additional context**
https://svelte.dev/docs#template-syntax-element-directives-use-action

**Comment by aidenybai** [comment]
Yes! So there is no completed hook system at the moment, but there is a hook field that runs prior to diff. What hooks do you think would be useful? At the moment, I can only think of `create`, `update`, `destroy`

**Comment by gustavopch** [comment]
@aidenybai I guess those 3 are enough to mimic Svelte actions.
- `create` is the action function itself
- `update` and `delete` are returned by the function and run later

**Comment by aidenybai** [comment]
Added in latest merge. Will be released in a new patch shortly

**Comment by gustavopch** [comment]
@aidenybai Great! It seems the commit didn't touch the docs yet. Can you post here an example of how to use it to achieve the same as the initial pseudo-code that I suggested?

**Comment by gustavopch** [comment]
@aidenybai Thanks! One more question: can I pass an array of hooks instead of just one? For example:
```js
import { confetti } from './hooks/confetti';
import { analytics } from './hooks/analytics';

<button
  hook={[
    // This hook will throw confetti around the page when the button is clicked
    confetti(),
    // This hook will log an analytics event when the button is clicked
    analytics({ event: 'purchase' }),
  ]}
>Submit</button>;
```

If not, it would be nice to add support to it.

**Comment by aidenybai** [comment]
I'm wondering whether it would be more practical to shift this responsibility to userland. For instance the hook below can just run all the functions instead of having an array abstraction:

```jsx
import { confetti } from "./hooks/confetti";
import { analytics } from "./hooks/analytics";

<button
  hook={{
    diff: () => {
      // This hook will throw confetti around the page when the button is clicked
      confetti();
      // This hook will log an analytics event when the button is clicked
      analytics({ event: "purchase" });
    },
  }}
>
  Submit
</button>;

```

**Comment by aidenybai** [comment]
I like this idea! Implemented in ee824f9934595845fff37ba4e577b36c24ca2d5b

**Comment by gustavopch** [comment]
@aidenybai You're fast! 😄 What about the `node` parameter? Can we have that too, or is there already another elegant way for the hook to get a reference to the node?

**Comment by aidenybai** [comment]
Thank you! Every hook provides the node, newVNode, and oldVNode:

```js
create: (node, newVNode, oldVNode) => ...
```

**Comment by aidenybai** [comment]
Hey! I seen you've made some issues to the Million repo, If you'd be willing I'm extending an invitation for you to become a collaborator :)

Link: [aidenybai/million/invitations](https://github.com/aidenybai/million/invitations)
