### ISSUE TITLE
bug: `Cannot set property form of #<HTMLButtonElement> which has only a getter`

### ISSUE THREAD

**Issue by gustavopch** [aidenybai/million#191]
**Describe the bug**
When trying to create a button element with the `form` attribute, the following error happens:
```
Uncaught TypeError: Cannot set property form of #<HTMLButtonElement> which has only a getter
```

**To Reproduce**
1. Open https://stackblitz.com/edit/mega-millions-ryy3r5?file=index.html
2. See the error in the console

**Expected behavior**
It should be possible to create a button element with the `form` attribute just as it's possible to do this:
```
document.body.innerHTML = '<button form="some-form">OK</button>'
```

Maybe the `form` attribute (and possibly others too) can only be set with `setAttribute()`?

**Screenshots**
![image](https://user-images.githubusercontent.com/10941958/173918610-0b314edb-ba95-450c-ae23-1e3596e81fbb.png)

**Device (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 102

**Additional context**
https://github.com/aidenybai/million/blob/74d50391113abad6c89d98eb3e93b748840ab51a/src/million/createElement.ts#L35-L37

**Comment by aidenybai** [comment]
Fixed in #192
