### ISSUE TITLE
feat: give monorepo a hug

### ISSUE THREAD

**Issue by cbbfcd** [aidenybai/million#202]
**Is your feature request related to a problem? Please describe.**
just a discuss, is there any plan about [monorepo](https://pnpm.io/workspaces)? 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aidenybai** [comment]
I would love to do something like this! Possibly with [Turborepo](https://turborepo.org) as well!

**Comment by cbbfcd** [comment]
👀, let me do some search for [Turborepo](https://turborepo.org/).

**Comment by aidenybai** [comment]
TODO: merge in https://github.com/aidenybai/million-site under /docs

**Comment by aidenybai** [comment]
Implemented in [3182fa8](https://github.com/aidenybai/million/commit/3182fa8f87ccffc9c50f213ac5cb70d8c93713fd)
