### ISSUE TITLE
bug: Wouter compat

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#203]
**Describe the bug**
Wouter errors when integrated into a Million/React environment

**To Reproduce**

```js
import { createRoot, useState } from 'million/react';
import { Link, Route } from 'wouter';

function App() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <button onClick={() => setCount(count + 1)}>{count}</button>

      <Link href="/users/1">
        <a className="link">Profile</a>
      </Link>

      <Route path="/about">About Us</Route>
      <Route path="/users/:name">{(params) => <div>Hello, {params.name}!</div>}</Route>
    </div>
  );
}

createRoot(document.body).render(<App />);
```

Gives something like this:

```
wouter.js?v=b667f2ca:1129 Uncaught TypeError: Cannot read properties of null (reading 'i')
    at useRef (wouter.js?v=b667f2ca:1129:14)
    at useNavigate (wouter.js?v=b667f2ca:1636:18)
    at Link (wouter.js?v=b667f2ca:1659:18)
    at compat.ts:15:17
    at hook2 (hooks.ts:37:17)
    at Object.createComponent [as handleFunction] (compat.ts:39:4)
    at Object.h (h.ts:45:14)
    at App (script.tsx:15:19)
    at compat.ts:15:17
    at hook2 (hooks.ts:37:17)
``` 

**Expected behavior**

Should behave as [Wouter](https://github.com/molefrog/wouter) intends it to

**Comment by aidenybai** [comment]
@cbbfcd wondering if you have any insight into this issue

**Comment by cbbfcd** [comment]
> @cbbfcd wondering if you have any insight into this issue

ok~

**Comment by cbbfcd** [comment]
After some experiments, I found some problems, and I will make PRs one by one to improve.

**Comment by cbbfcd** [comment]
@aidenybai i found some problems(in version `1.11.2`) have been fixed, like [this](https://github.com/aidenybai/million/blob/main/src/react/compat.ts#L16). can u publish a new version?

**Comment by aidenybai** [comment]
Gotcha, thank you for your help. If you need any input from me don't hesitate to ask

**Comment by cbbfcd** [comment]
now, wouter is run successfully.

**Comment by aidenybai** [comment]
Hmm.. I'm not able to get Wouter working on my side... Could you provide the repro of working Wouter? Thank you in advance!

**Comment by cbbfcd** [comment]
because I modified the source code in `.pnpm`, I will take screenshots to illustrate.

1. a simple `wouter` controlled routing page
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/20987775/175883592-038ad218-f764-4a26-b833-859edd1fef4d.png">

2. change one
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/20987775/175884364-e23606e4-f61f-4e6d-8336-615a26fbbb6d.png">

3. change two
<img width="898" alt="image" src="https://user-images.githubusercontent.com/20987775/175885093-6d7818b4-ccd8-4a3c-a30b-6fc11ba0e415.png">

4. change three
<img width="836" alt="image" src="https://user-images.githubusercontent.com/20987775/175885566-220ed940-c3d7-4c2a-9290-1a275b5fb9db.png">

finally ,you can see
<img width="485" alt="image" src="https://user-images.githubusercontent.com/20987775/175885652-50a0add6-49c9-4c66-b1cd-55fdf9809592.png">

**Comment by aidenybai** [comment]
Great doc, would you be willing to create a github repo with the setup you have there so I can play with it a bit?

**Comment by cbbfcd** [comment]
ok, i will create a github repo.

**Comment by cbbfcd** [comment]
https://github.com/cbbfcd/million-wouter-compat-demo

@aidenybai here~

**Comment by aidenybai** [comment]
Hmm... okay, after some investigation this seems to be an issue with contexts. I'll update you when I get contexts working 👍

**Comment by cbbfcd** [comment]
i found this pr, I should dig deeper into the problem and now i probably understand the reason

**Comment by wulinsheng123** [comment]
has this problem been fixed ?

**Comment by aidenybai** [comment]
Happy to say we're one step closer to fixing this issue: https://github.com/aidenybai/million/commit/1bcedb5549b5a5c9194920ef42529ce4a7de4a57

**Comment by cbbfcd** [comment]
has been fixed?

**Comment by aidenybai** [comment]
Not yet. Have been somewhat busy, currently still investigating

**Comment by subhasishdas159** [comment]
Similar problem encountered with hook-router

**Comment by cbbfcd** [comment]
> Not yet. Have been somewhat busy, currently still investigating

if anythin i can do, pls let me know.

**Comment by aidenybai** [comment]
> > Not yet. Have been somewhat busy, currently still investigating
> 
> if anything i can do, pls let me know.

Currently, I'm trying to figure out why Million cannot handle ref when passed into a context:

```js
import {
  createRoot,
  createContext,
  useState,
  useContext,
  useRef,
  useEffect,
} from 'packages/react';

const ctx = createContext({});

const Child = () => {
  const ref = useContext(ctx);

  console.log('comp', ref.current);

  return <div ref={ref}>{!!ref.current}</div>;
};

const App = () => {
  const ref = useRef(0);

  console.log('app');

  return (
    <ctx.Provider value={ref}>
      <div>
        <Child />
      </div>
    </ctx.Provider>
  );
};

createRoot(document.getElementById('root')!).render(<App />);
```

**Comment by cbbfcd** [comment]
ok, work is less busy now 😂, I'll try to find out why

**Comment by QuiiBz** [comment]
Reopening this issue since #258 doesn't completely fix the bugs - but fixes some of them.

**Comment by aidenybai** [comment]
closed via v2
