### ISSUE TITLE
bug: rendered `_` in the dom tree.

### ISSUE THREAD

**Issue by cbbfcd** [aidenybai/million#208]
**Describe the bug**
<img width="972" alt="image" src="https://user-images.githubusercontent.com/20987775/175771617-11f29302-90ef-41d6-90e0-12e747b08491.png">

maybe caused by here:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/20987775/175771678-fad94fb3-2d23-4473-b482-ff6d39fc57dc.png">

**To Reproduce**

**Expected behavior**

should render `span` or other text node in the dom tree?
**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by aidenybai** [comment]
This is intentional because root fragments are currently unsupported (or at least I'm not sure how it can be supported).

The `_` tag acts like a "passthrough" element with `display: contents`, allowing it to behave like a root fragment.

**Comment by cbbfcd** [comment]
gotcha

**Comment by aidenybai** [comment]
Closing until this becomes an issue
