### ISSUE TITLE
feat: feature list

### ISSUE THREAD

**Issue by cbbfcd** [aidenybai/million#213]
**Is your feature request related to a problem? Please describe.**

if possible, can provide a `featurelist` so that everyone can participate and build `million`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aidenybai** [comment]
Could you elaborate on more of what this would look like?

**Comment by SukkaW** [comment]
I am also a bit confused about the wording here.

Is it about `good first issue`?

**Comment by cbbfcd** [comment]
It is more like a to-do list, listing some future features of million, so that more people can participate and choose what they are good at or interested in.

like this:

- [ ] monorepo support
- [ ] Preact compat?
- [ ] chinese doc(i18n)
...

**Comment by aidenybai** [comment]
Good idea! I'll look into options GitHub provides to add something like this.

**Comment by aidenybai** [comment]
I've made a Roadmap project in GitHub. Is this what you're imagining?

**Comment by cbbfcd** [comment]
🎉～
