### ISSUE TITLE
feat: improve `pnpm welcome`

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#215]
**Is your feature request related to a problem? Please describe.**
Currently, the `pnpm welcome` command is lackluster -- it just shows you how to install packages ([ref](https://github.com/aidenybai/million/blob/main/scripts/welcome.mjs)). 

**Describe the solution you'd like**
It would be nice to have more setup steps (how to use dev environment, filesystem walkthrough, script walkthrough, etc.). Feel free to ask for feedback on what to add

**Comment by wulinsheng123** [comment]
hello how to contribute ?

**Comment by aidenybai** [comment]
Here are the general contribution guidelines: https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md. For this issue, I recommend you look at this file when making changes: https://github.com/aidenybai/million/blob/main/scripts/welcome.mjs

**Comment by wulinsheng123** [comment]
> Here are the general contribution guidelines: https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md. For this issue, I recommend you look at this file when making changes: https://github.com/aidenybai/million/blob/main/scripts/welcome.mjs

Ok thank you let me check

**Comment by wulinsheng123** [comment]
i got empty website when i ran "pnpm dev". 
and could you tell me more about that(how to use dev environment, filesystem walkthrough, script walkthrough, etc.)

**Comment by aidenybai** [comment]
pnpm dev will run a vite server a root (you'll need to open localhost:3000/dev/index.html to access.

More info on scripts would be useful! Adding a new issue for that.

**Comment by wulinsheng123** [comment]
ok , I will try on lete.
and then if you have any detial idea, you can contact me anytime

**Comment by aidenybai** [comment]
Implemented in [42977d4](https://github.com/aidenybai/million/commit/42977d43b0c34cc031965f12c8ab0377e846a890)
