### ISSUE TITLE
bug: router doesn't support non text types

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#223]
**Describe the bug**
Router doesn't support non-text hrefs, and attempt to fetch and replace.

**To Reproduce**

```html
<a href="/link/to/example.pdf">doesn't work</a>
```

**Comment by staszewski** [comment]
Hey, I wanted to help. I tried to reproduce, but the example from "To Reproduce" seems to work. There is a text in href. I tried the code on top of template from https://github.com/aidenybai/million-react Can you share some context?

**Comment by aidenybai** [comment]
Hey @staszewski, thanks for the interest. If you look here (https://github.com/aidenybai/million/blob/35d51e1fd925381bead132107f41d485d6ad051e/packages/router/router.ts#L60) any data format, when fetched, is accepted, even if it isn't text.
