### ISSUE TITLE
bug: Documentation search bar doesn't work

### ISSUE THREAD

**Issue by ryanjmack** [aidenybai/million#235]
**Describe the bug**
Trying to search something in the million documentation causes an endless spinner

**To Reproduce**
1. Go to 'https://millionjs.org/'
2. Click on the search bar
3. Type in the search bar, notice the endless spinner
4. console has this error: "Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0"
5. Hit enter key, still has endless spinner
6. an additional console error bubbles up: "Uncaught TypeError: Cannot read properties of undefined (reading 'route')"

**Expected behavior**
I'd expect the search function to work

**Screenshots**
<img width="1789" alt="Screen Shot 2022-08-02 at 4 39 02 PM" src="https://user-images.githubusercontent.com/17010097/182494962-fc8796c2-d589-4778-98db-240ef789b5c7.png">

**Device (please complete the following information):**
 - OS: iOS (Big Sur v11.6)
 - Browser: Chrome v103
 - Version: latest million release

**Comment by noobyogi0010** [comment]
Hey, @ryanjmack 
I would like to work on this issue if no one else is working on it.
Thanks!

**Comment by aidenybai** [comment]
Hey @noobyogi0010, any update on this? Do you need any help with this issue so far?

**Comment by noobyogi0010** [comment]
Hey @aidenybai 
I am still working on this issue.
Sorry, I didn't get much time to focus on it completely. Will try to wrap it up by end of this week.
Thanks!

**Comment by aidenybai** [comment]
No worries, take your time. If you need any help, feel free to comment any questions here or in the Discord :)

**Comment by noobyogi0010** [comment]
@aidenybai I am not able to reproduce this issue. Neither on my local system nor on the million's documentation.

**Comment by aidenybai** [comment]
@ryanjmack, could you test this issue again? Possibly a recent commit to docs fixed this issue

**Comment by ryanjmack** [comment]
@aidenybai the issue seems to be resolved, so I'm closing it!
