### ISSUE TITLE
bug: wrong word in landing

### ISSUE THREAD

**Issue by EndyKaufman** [aidenybai/million#237]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4127109/182568210-c4f40464-56e8-48fd-89c6-f025e120eecf.png)

**Device (please complete the following information):**

**Additional context**

**Comment by QuiiBz** [comment]
Thanks for the bug report! I've created a PR to resolve it: https://github.com/aidenybai/million/pull/239
