### ISSUE TITLE
bug: unable to use million/jsx-runtime with next.js

### ISSUE THREAD

**Issue by DaniAkash** [aidenybai/million#259]
**Describe the bug**
I'm trying to use million on Next.js using [babel automatic runtime](https://millionjs.org/docs/tooling/using-jsx#automatic-runtime-recommended) but i'm not able to get the next dev server to start.

Getting the following error:
<img width="784" alt="Screenshot 2022-08-14 at 1 54 03 PM" src="https://user-images.githubusercontent.com/6841445/184528711-263a5532-c169-4e1f-bc53-91f6eff81a7d.png">

**To Reproduce**
CodeSandbox: https://codesandbox.io/s/next-million-js-o4jlki?file=/.babelrc

**Expected behavior**
Next.js should be able to run...

**Device (please complete the following information):**
 - Node 16
 - React 18.2
 - Next latest

**Comment by aidenybai** [comment]
Hi@DaniAkash, Next.js is currently not compatible with Million.js. We are planning to work on a next plugin to allow for this in the future.

**Comment by DaniAkash** [comment]
That would be awesome! If you can share more details... I'm also happy to contribute 👍

**Comment by aidenybai** [comment]
Sure! We're currently working towards some compatability with routers currently in order to support Next.js router in #203. Next steps are hydration, prerendering, etc. Feel free to join our Discord to discuss further
