### ISSUE TITLE
feat: Add Recoil integration

### ISSUE THREAD

**Issue by yakubori** [aidenybai/million#262]
I had tried to run an existing react/recoil app using Million, but it failed with one of either two errors:

1. `Uncaught Error: This component must be used inside a <RecoilRoot> component.`

The code for which was the following:

```javascript
import React from 'react';
import ReactDOM from 'react-dom/client';
import { RecoilRoot } from 'recoil';

import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <RecoilRoot>
      <App />
    </RecoilRoot>
  </React.StrictMode>,
  
  document.getElementById('root')
);
```

-- OR --

2. `Uncaught TypeError: Cannot read properties of null (reading 'useContext')`

The latter occurred with my Vite config like so:

```javascript
import { defineConfig } from 'vite';
import { million } from 'million/vite-plugin-million';

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        million(),
    ],
});
```

While the former used the `{react: true}` option.

I would love to see Recoil working with Million because I am excited about both projects!

I have considered just sticking with a traditional React/Recoil app for now; perhaps trying Preact at a later time.

**Comment by SukkaW** [comment]
I have seen this kind of error before (on a preact project). It seems that it has something to do with package resolution (react is actually being used when the million should be imported). Probably caused by failing to alias the package.

**Comment by yakubori** [comment]
@SukkaW that's interesting to see you say that. I was thinking it might be something along those lines when I was looking at the Million compiler code a little while ago. I noticed something about a source option, but it defaulted to 'million' so I thought it would be ok to run it as it was. I will look more into it this evening. I wonder if I need to update some more code or configs as well...

**Comment by aidenybai** [comment]
works in v2
