### ISSUE TITLE
bug: VNode from HTML string fails on unclosed input tags

### ISSUE THREAD

**Issue by seanhess** [aidenybai/million#276]
**Describe the bug**
When I generate a VNode from a string using `fromStringToDomNode` and `fromDomNodeToVNode`, if it contains an `<input>` tag, the library fails with: 

```
This page contains the following errors:
error on line 1 at column 96: Opening and ending tag mismatch: input line 1 and div
```

According to the HTML spec, input tags are represented like this:
```
<div>
  <input type="text">
</div>
```

It appears the the parser or the patch function thinks that the input tag should be closed. If I manually manipulate the string to be the following, it works:

```
<div>
  <input type="text"></input>
</div>
```

That's not correct though, and if you take any input in the dom and get its html (via outerHTML, or innerHTML, for example), it will not be closed in the resulting string. 

**To Reproduce**
```
window.addEventListener("load", function() {
  let input = "<div><input type='text'></div>" 
  let dom = fromStringToDomNode(input)
  let vnode = fromDomNodeToVNode(dom)
  patch(document.body, vnode)
})
```

**Expected behavior**
I would expect this to render without errors

**Device (please complete the following information):**
 - MacOS
 - Chrome
 - latest

**Comment by aidenybai** [comment]
Looking into this 👍

**Comment by aidenybai** [comment]
PR in  #277

**Comment by seanhess** [comment]
Thanks so much! I haven't been in JS-land in a while, have these changes been published? How can I pick them up in my project?

**Comment by aidenybai** [comment]
@seanhess sorry about the wait! let me publish a new version for you :)
