### ISSUE TITLE
bug: modern ECMAScript syntax not supported by `recast`

### ISSUE THREAD

**Issue by gustavopch** [aidenybai/million#283]
Recast [uses Esprima by default](https://github.com/benjamn/recast#using-a-different-parser) as its parser. As you can see in https://npm.im/esprima, its last version was published 4 years ago. It doesn't support modern ECMAScript syntax like optional chaining and nullish coalescing operators.

Because of that, I was getting the error `Error during compilation! Set skipOptimize to true to fix this problem.` in a bunch of files in my project.

I was able to fix it by patching `vite-plugin-million` (with https://npm.im/patch-package) at https://github.com/aidenybai/million/blob/main/packages/vite-plugin-million/plugin.ts#L60 to use Espree (which does support modern ECMAScript syntax) instead of Esprima:
```diff
-          const ast = parse(code);
+          const ast = parse(code, {
+            parser: {
+              parse(source, options) {
+                return espree.parse(source, {
+                  ...options,
+                  ecmaVersion: "latest"
+                });
+              }
+            }
+          });
```

PS: I'm not following the issue template because I'm in a hurry, but I hope my explanation is enough.

**Comment by aidenybai** [comment]
Interesting find! Would you like to PR this fix? If not, no worries :)

**Comment by gustavopch** [comment]
Unfortunately not, very busy here with work already.
