### ISSUE TITLE
bug: React.memo works incorrectly

### ISSUE THREAD

**Issue by atellmer** [aidenybai/million#285]
**Describe the bug**
Hey. I'm trying to test the compatibility layer with react. I came across a bug when using the memo function. This function is not properly passing props. I think the point is that memo function is implemented by passing props through `Object.values(props) `which produces an array instead of an object. As a result, the memoizable component receives an array of arguments as input, instead of a single props argument.

**To Reproduce**
Wrap any component in memo and pass some props to it.

**Expected behavior**
Props must be passed as a single argument.

**Comment by aidenybai** [comment]
fixed in v2
