### ISSUE TITLE
feat: nextjs plugin for autoblocking

### ISSUE THREAD

**Issue by Milo123459** [aidenybai/million#294]
**Is your feature request related to a problem? Please describe.**
Sometimes, using Million can require complex code changes in a Next app.

**Describe the solution you'd like**
A next plugin could solve this by automatically using Million blocks without having to do any code changes.

**Describe alternatives you've considered**

**Additional context**

**Comment by cytronicoder** [comment]
Would this involve the [Next.js compiler?](https://nextjs.org/docs/advanced-features/compiler)
I think this can follow a structure similar to what y'all used for Vite.

**Comment by aidenybai** [comment]
FYI, this is next up. Already have some ideas around how hooks / callbacks can be implemented

**Comment by cytronicoder** [comment]
Nice!

**Comment by yazaldefilimonepinto** [comment]
Hi, @aidenybai  let me try to add this feature.

**Comment by aidenybai** [comment]
Next up is to solve the SSR story of Million to start development of this plugin

**Comment by tobySolutions** [comment]
> Next up is to solve the SSR story of Million to start development of this plugin

Pun intended? 🥹🥹. Next is up next.

**Comment by aidenybai** [comment]
#316

**Comment by aidenybai** [comment]
https://twitter.com/aidenybai/status/1650406345517199361?s=20

**Comment by Milo123459** [comment]
it's great news that full support for next is out, but the plugin technically speaking isn't. i asked in the discord and you said you were working on it.

**Comment by aidenybai** [comment]
ah good catch. let's reopen this issue

**Comment by aidenybai** [comment]
Our current direction is focused on primitives that allow developers to opt-in to block rendering. When we get to a point where blocks are _very_ stable and support SSR/RSC, and there is a use case from a project, then we can reconsider this issue.

**Comment by aidenybai** [comment]
just kidding i lied @Milo123459 

very, VERY soon :)

**Comment by Milo123459** [comment]
awesome! we've got a vite plug-in, so I guess the logic could be carried over to a next plugin?

**Comment by aidenybai** [comment]
@Milo123459 it should automatically work in both vite & next out of the box

**Comment by Milo123459** [comment]
wtf that's awesome well Dane
