### ISSUE TITLE
Feedback for “What is Million.js?”

### ISSUE THREAD

**Issue by leimonio** [aidenybai/million#295]
Hi great work on this. A few questions and considerations:

- Where can I find the codebase that was used for the benchmarks?
- No state can be used inside the block components
  - `block` seems similar to the react memoized components. How does it compare in terms of performance?
  - This promotes pushing state higher and prop drilling I guess. Is there any plan to support state & hooks inside these components?

**Comment by aidenybai** [comment]
Thanks for the feedback, marked issue as to-do. To address your questions:

**Where can I find the codebase that was used for the benchmarks?**

The benchmark is a fork of JSFB: https://github.com/aidenybai/js-framework-benchmark. We have an [open PR](https://github.com/krausest/js-framework-benchmark/pull/1204) to add it to the main repo.

**block seems similar to the react memoized components. How does it compare in terms of performance?**

They are completely different, although may look deceivingly similar. `block` is a component that mounts the Million.js virtual DOM (kind of like an island)

This promotes pushing state higher and prop drilling I guess. Is there any plan to support state & hooks inside these components?

Yes. It's on the TODO list and is high priority.

**Comment by aidenybai** [comment]
FYI, this is next up. Already have some ideas around how hooks / callbacks can be implemented

**Comment by tobySolutions** [comment]
> FYI, this is next up. Already have some ideas around how hooks / callbacks can be implemented

Awesome! This sounds like a fun issue!

**Comment by cytronicoder** [comment]
Make a meme video about the speed

**Comment by tobySolutions** [comment]
Thanks @cytronicoder. 🙂🙂🙂

**Comment by hb1998** [comment]
> FYI, this is next up. Already have some ideas around how hooks / callbacks can be implemented

@aidenybai since you are working on supporting callbacks, which are basically objects I'm assuming this will also include support for non primitives ?

**Comment by aidenybai** [comment]
Landed in 2.2.1
