### ISSUE TITLE
bug: docs stackblitz counter example illegal constructor

### ISSUE THREAD

**Issue by InternetRamen** [aidenybai/million#297]
**Describe the bug**
When visiting https://millionjs.org/docs, the counting example shows `illegal constructor`

**To Reproduce**
1. Go to https://millionjs.org/docs
3. Scroll down to React vs. Million.js

**Expected behavior**
Counting example 

**Screenshots**
![image](https://user-images.githubusercontent.com/66806100/225603211-81194544-0851-44fd-a3c6-1c3f3290300b.png)

**Device (please complete the following information):**
 - iOS
 - Safari
 - 16.1

**Additional context**

**Comment by aidenybai** [comment]
Not sure what's happening here. I reduced the number of nodes loaded, can you try again?

**Comment by InternetRamen** [comment]
I think the error is still there

**Comment by aidenybai** [comment]
fixed!
