### ISSUE TITLE
bug: types are broken for million/*

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#299]
Try importing `million/react`, can't resolve declaration file

**Comment by QuiiBz** [comment]
I think we can trigger a new release to make sure the issue is fixed (it should!)

**Comment by aidenybai** [comment]
sounds good. is there a way to create a github action automation to allow npm release on release create?

**Comment by QuiiBz** [comment]
We could use something like [changesets](https://github.com/changesets/changesets), which can trigger releases both manually and automatically (e.g on each merge on main)

**Comment by aidenybai** [comment]
we should def set that up if possible. i can look into it tomorrow, although the action should have been installed, feel free to try running `pnpm bump` then create a release

**Comment by QuiiBz** [comment]
Main branch is protected so I can't use `pnpm bump` directly :(

**Comment by aidenybai** [comment]
Removed the rule, should be possible to bump now!

**Comment by QuiiBz** [comment]
Done, thanks!
