### ISSUE TITLE
bug: Hero section is hiding behind fixed navbar. not able to see text properly

### ISSUE THREAD

**Issue by bharat5604** [aidenybai/million#302]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]

**Additional context**
![image](https://user-images.githubusercontent.com/46484617/229052613-7d4fd103-2aeb-42b8-b46a-292c9bb4327e.png)

**Comment by aidenybai** [comment]
fixed in latest commit
