### ISSUE TITLE
feat: Remove React DOM dependency and devDependency

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#310]
**Is your feature request related to a problem? Please describe.**
I feel that the elements of the React DOM in the "react" directory from the "package" has no need for the "react-dom" dependency and ""@types/react-dom"" in the devDependencies

**Describe the solution you'd like**
Delete both lines of code so that the "pnpm install" command doesn't install unnecessary dependencies such as the above

**Describe alternatives you've considered**

**Additional context**
![Screenshot from 2023-04-12 17-46-25](https://user-images.githubusercontent.com/96334363/231531769-a012368c-52eb-4fda-bf0f-a0ac5230a505.png)

**Comment by aidenybai** [comment]
Assigned

**Comment by tobySolutions** [comment]
> Assigned

Thanks Aiden!

**Comment by tobySolutions** [comment]
issue resolved by #311
