### ISSUE TITLE
feat: Add contributing guidelines

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#314]
**Is your feature request related to a problem? Please describe.**
I think a Contributing Guideline should be available to help new contributors that are new to the project and ecosystem and that really want to contribute to the project.

**Describe the solution you'd like**
A step-by-step contributing guideline markdown should be available in the codebase to help onboard and guide new contributors with the codebase.

**Additional context**
For example, https://github.com/FrancescoXX/4c-site/blob/main/CONTRIBUTING.md is kind of an example of something this project can add as well.

**Comment by Noibisjunior** [comment]
Hello Tobi, I would love to join you to contribute on creating a well explanatory guide to help other contributors understand the project

**Comment by tobySolutions** [comment]
Hey @Noibisjunior! Definitely, I'll make sure to do that.

**Comment by tobySolutions** [comment]
Issue resolved by #318
