### ISSUE TITLE
Feature: Redesigning the dark/light/system mode button.

### ISSUE THREAD

**Issue by Noibisjunior** [aidenybai/million#317]
**Issue**
I found the dark/light/system mode button difficult to  Navigate

**Solution**
I would be glad to provide solution by repositioning the dark/light/system mode button to the top of the page.

**Comment by tobySolutions** [comment]
What do you think about this @aidenybai?

**Comment by aidenybai** [comment]
I don't actually understand what this issue is about. Can you explain + elaborate @Noibisjunior?

**Comment by tobySolutions** [comment]
Any updates @Noibisjunior?

**Comment by Noibisjunior** [comment]
@aidenybai Here is a visual presentation of the feature I want to improve.

Changing the initial design of the dark mode button from

![Screenshot_20230418-225424](https://user-images.githubusercontent.com/104741218/232915961-5715ea10-31c0-4f09-804d-66210c1c10e4.png)

To a more improved design

![IMG_20230418_230342](https://user-images.githubusercontent.com/104741218/232916199-3174feb6-3976-4db7-8856-91e147901dde.jpg)

I hope my explanation is clear enough.

Thanks

**Comment by Noibisjunior** [comment]
OK,Thanks

**Comment by tobySolutions** [comment]
Any updates @Noibisjunior?

**Comment by tobySolutions** [comment]
@Noibisjunior??

**Comment by ramzibouzaiene** [comment]
Hi guys I'm trying to run the project in my local machine but i get this error @aidenybai @tobySolutions 
![image](https://github.com/aidenybai/million/assets/74255678/984d9503-377b-4137-8266-737f234e7917)

**Comment by tobySolutions** [comment]
> Hi guys I'm trying to run the project in my local machine but i get this error @aidenybai @tobySolutions 
> ![image](https://github.com/aidenybai/million/assets/74255678/984d9503-377b-4137-8266-737f234e7917)
> 

Did you do "pnpm install" after cloning the repo?

**Comment by tobySolutions** [comment]
If so, try deleting your node modules and try again.

**Comment by ramzibouzaiene** [comment]
Yes, I deleted the node module and did pnpm install again and still the same problem

**Comment by tobySolutions** [comment]
Can you cd into the website and run "pnpm install"?

**Comment by RutamBhagat** [comment]
@tobySolutions I would like to work on this issue if no one is currently working on it.

**Comment by ramzibouzaiene** [comment]
> Can you cd into the website and run "pnpm install"?

i did that and it didn't work i'm still looking for the problem

**Comment by tobySolutions** [comment]
> > Can you cd into the website and run "pnpm install"?
> 
> i did that and it didn't work i'm still looking for the problem

Delete both your node modules and package-lock.json.

Then do pnpm install. The error is a tricky one.

**Comment by tobySolutions** [comment]
> @tobySolutions I would like to work on this issue if no one is currently working on it.
> 

@ramzibouzaiene is currently working on it. 👀👀

**Comment by ramzibouzaiene** [comment]
@tobySolutions maybe the problem my node version ? what node version should i use for the project ?

**Comment by tobySolutions** [comment]
> @tobySolutions maybe the problem my node version ? what node version should i use for the project ?

I'm on a 16.6.6, what's yours?

**Comment by ramzibouzaiene** [comment]
in the first i used 14.21 and then 20.3.0 and didn't work

**Comment by RutamBhagat** [comment]
Ok, I had the site running on my localhost, let me know if I can work on this. I tried to find the Dark mode button in /components/home/index.tsx but couldn't find it anywhere.

**Comment by ramzibouzaiene** [comment]
@RutamBhagat i'm still trying to fix the problem, but i think you can find the theme configuration under website/theme.config.tsx

**Comment by tobySolutions** [comment]
Thank you @ramzibouzaiene. Have you found it yet @RutamBhagat?

Also, were you able to get the project to run locally?

**Comment by RutamBhagat** [comment]
@tobySolutions I am able to run the project locally and I found the theme.config.tsx file but I am unable to understand where the jsx of Dark mode toggle button is coming from. Can you please help me a bit to solve this issue?

**Comment by tobySolutions** [comment]
> @tobySolutions I am able to run the project locally and I found the theme.config.tsx file but I am unable to understand where the jsx of Dark mode toggle button is coming from. Can you please help me a bit to solve this issue?

Hey! Thanks for reaching out. Are you sure? Did you try inspecting with DevTools? It's kind of on he footer though.

No worries, I'll check it out and let you know.

**Comment by aidenybai** [comment]
Not a big need here... if anyone stumbled upon this issue, and you for some reason want to implement this, take a look at [Drizzle's implementation](https://orm.drizzle.team/)

Reference:
1. https://github.com/drizzle-team/drizzle-orm-docs/blob/42054d510022be9399f068cc6a34838c88cee314/theme.config.tsx#L56
2. https://github.com/drizzle-team/drizzle-orm-docs/blob/master/components/ThemeToggle/ThemeToggle.tsx
