### ISSUE TITLE
docs: google indexed https://millionjs.org/docs/next but it returns 404

### ISSUE THREAD

**Issue by Davasny** [aidenybai/million#328]
**Describe the bug**

Google returns page https://millionjs.org/docs/next but it returns 404

**To Reproduce**
Google "millionjs nextjs"

**Screenshots**
![image](https://user-images.githubusercontent.com/25726866/235191622-d09cb83d-c27a-4917-ad48-179f096004c2.png)

**Comment by tobySolutions** [comment]
Can you check this out @aidenybai?

**Comment by tobySolutions** [comment]
No update on this? This issue is weird even, cos how did that link come about?

**Comment by IAmTamal** [comment]
> No update on this? This issue is weird even, cos how did that link come about?

The page `/docs/next` used to exist probably until it got removed in this [commit](https://github.com/aidenybai/million/commit/84b96d9dba89f0bc4273729781289fc243f8d964#diff-81147b4cd20ba7f336b0b81b1d5b55bf2cf7f245b9529279ddc28d978e672a85).

**Comment by aidenybai** [comment]
I think we just have to wait for google to unindex that page. Maybe we can request google to remove?

**Comment by tobySolutions** [comment]
> I think we just have to wait for google to unindex that page. Maybe we can request google to remove?

Can we do that? Let me look it up?

**Comment by tobySolutions** [comment]
Any updates on this @aidenybai?

**Comment by thisisrick25** [comment]
It's unindexed already.

site:https://million.dev/docs/next and cache:https://million.dev/docs/next dosent exist.

**Comment by tobySolutions** [comment]
> It's unindexed already.
> 
> site:https://million.dev/docs/next and cache:https://million.dev/docs/next dosent exist.

Yo! That's awesome. I guess it's safe to close this issue then.

**Comment by tobySolutions** [comment]
> It's unindexed already.
> 
> site:https://million.dev/docs/next and cache:https://million.dev/docs/next dosent exist.

No, not yet; It still returns the 404 page

![image](https://github.com/aidenybai/million/assets/96334363/5ada983b-4387-4280-b9f2-1598e1dacc1c)

**Comment by thisisrick25** [comment]
> No, not yet; It still returns the 404 page

Yes because the page doesn't exist, as it was deleted (mentioned in this [comment](https://github.com/aidenybai/million/issues/328#issuecomment-1533532893)), which is why Google removed it from its index.
When you google search "millionjs nextjs" as the [original issue](https://github.com/aidenybai/million/issues/328#issue-1688765644) states, the old result doesn't show up, hence the link and cache were removed.

**Comment by tobySolutions** [comment]
> > No, not yet; It still returns the 404 page
> 
> Yes because the page doesn't exist, as it was deleted (mentioned in this [comment](https://github.com/aidenybai/million/issues/328#issuecomment-1533532893)), which is why Google removed it from its index. When you google search "millionjs nextjs" as the [original issue](https://github.com/aidenybai/million/issues/328#issue-1688765644) states, the old result doesn't show up, hence the link and cache were removed.

Oh, you're right! It's about time we closed this issue.
