### ISSUE TITLE
bug: Update all links to referencing the old React docs to https://react.dev

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#333]
**Describe the bug**
Most of the links to the React docs from Million point to [https://reactjs.org](https://reactjs.org) instead of [https://react.dev](https://react.dev)

**Expected behavior**
All links should point to the updated React documentation

**Screenshots**
![Screenshot from 2023-05-02 12-55-04](https://user-images.githubusercontent.com/96334363/235659248-1da8882d-a2d0-45da-b31a-3ccd9f48139b.png)

**Additional context**
There might be a problem with the Higher Order Component part of the documentation as the new React docs doesn't include it. It still exists in the Legacy React documentation though

**Comment by tobySolutions** [comment]
Can I work on this?

**Comment by tobySolutions** [comment]
My PR will include changes to the width of the image on the latest blog article.
![Screenshot from 2023-05-02 12-14-54](https://user-images.githubusercontent.com/96334363/235659898-65510701-f29c-4daf-838b-620119fdf758.png)
![Screenshot from 2023-05-02 12-14-47](https://user-images.githubusercontent.com/96334363/235659903-ff0cfc33-2059-4820-b7c9-1422af0db1cf.png)

**Comment by aidenybai** [comment]
LGTM

**Comment by tobySolutions** [comment]
Closed by #334
