### ISSUE TITLE
Searchbar should have a different placeholder within the blog

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#335]
The placeholder for the search bar within the blog should be "Search blog..." instead of "Search documentation..."

Having the placeholder of the search bar within the blog be "Search blog..." will really help a lot.

Check out the newest article on the website's blog to see how this is: [Virtual DOM: Back in Block](https://millionjs.org/blog/virtual-dom)

![Screenshot from 2023-05-04 15-10-38](https://user-images.githubusercontent.com/96334363/236233381-dc04e021-53bb-4c2c-95ba-e1f2e0879b27.png)

**Comment by nzaih1999** [comment]
hello guys im intrested in working on this can you assign me

**Comment by aidenybai** [comment]
@nzaih1999 assigned. this might be a upstream issue for [nextra](https://nextra.site/), so take a look at that first

**Comment by akshithio** [comment]
took a very quick peek, likely has to do with the fact that `/blog` and `/docs` both use the same theme. Could potentially be fixed by using `nextra-theme-blog` for `/blog` and creating a separate theme but seems like this theme and its documentation is currently a WIP from nextra's end.

**Comment by aidenybai** [comment]
Will be fixed in a PR soon.
