### ISSUE TITLE
bug: "Open demo" button should open demo when any part of the button is pressed.

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#336]
**Describe the bug**
Other parts of the open demo button are not clickable unless you hover over the "Open Demo" button.

**To Reproduce**
1. Go to 'Documentation'
2. Scroll down to "Open demo" button
3. Click on 'Open demo' button.

**Expected behavior**
When any part of the button is clicked and hovered on. The pointer cursor should appear and those parts should be clickable as well.

**Additional context**
[Screencast from 05-04-2023 03:20:05 PM.webm](https://user-images.githubusercontent.com/96334363/236238339-a55b3b44-f257-42c8-9a63-89b2cae18f3c.webm)

**Comment by giri-madhan** [comment]
Hi @tobySolutions, I can work on this issue. Could you please assign it to me? Thank you!
