### ISSUE TITLE
[RFC] Educating developers on the `block` pattern

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#342]
Currently, our project is positioned where the actual `block` function and `For` component work well enough in the cases it does work. But when it doesn't work, shit hits the fan... really quick. This is the biggest barrier for adoption for our project.

> Example of shit hitting the fan:
> ![image](https://user-images.githubusercontent.com/38025074/236704201-0b6955ef-7ef1-4fd3-be8f-f69a81610be4.png)

This is a threefold problem: 

1. We do not have great error messages.

We need to invest a lot more time in invest into error messages. `<For />`example, we do not support non-deterministic / early returns. We should have both an error message in the client and server for this problem. It should not only show an error, but identify the exact line of the problem, and furthermore, give reasoning and documentation for the error.

Right now, it either is just a "rule of hooks is broken" error or a `document is not defined` error, both of which are non-descriptive and very unhelpful.

We should also suggest how to restructure components. Blocks are not always a clean function wrap, they require restructuring of components in order to work properly. Furthermore, we can remind developers to use the `<For />` component when `.map` is used on a block.

2. We have not defined the proper use cases of `block()`

We still do not know where block **should** be used. We need to define rigid use cases where block is actually helpful. General guidelines like "more static than dynamic" is not really helpful to most React developers. 

This specific point can also help us with the 1st problem mentioned. By defining the proper use cases, we can remind developers when not and when to use blocks.

3. We do not educate developers on how to use the "magic" of block

Our docs are lacking a lot of content for new developers to understand and use. This goes along with 2 and 3.

> For any efforts happening right now around Million.js, they will be paused for fixing this critical issue first.

**Comment by aidenybai** [comment]
@SukkaW @QuiiBz @tobySolutions would love feedback if you all have any

**Comment by tobySolutions** [comment]
> @SukkaW @QuiiBz @tobySolutions would love feedback if you all have any

Totally! I think a more explanatory and relatable documentation like the tailwindCSS docs is what I would recommend as a good stuff to emulate.

It takes into account that you might want to use tailwind in different cases and it provides rich information for each use case without putting emphasis on one over the other. 

In my opinion if we can achieve that we've managed to help out developers like me that want to use good tools like Million. 🙏🙏🙏🙏

**Comment by tobySolutions** [comment]
> Currently, our project is positioned where the actual `block` function and `For` component work well enough in the cases it does work. But when it doesn't work, shit hits the fan... really quick. This is the biggest barrier for adoption for our project.
> 
> > Example of shit hitting the fan:
> > ![image](https://user-images.githubusercontent.com/38025074/236704201-0b6955ef-7ef1-4fd3-be8f-f69a81610be4.png)
> 
> This is a threefold problem: 
> 
> 1. We do not have great error messages.
> 
> We need to invest a lot more time in invest into error messages. `<For />`example, we do not support non-deterministic / early returns. We should have both an error message in the client and server for this problem. It should not only show an error, but identify the exact line of the problem, and furthermore, give reasoning and documentation for the error.
> 
> Right now, it either is just a "rule of hooks is broken" error or a `document is not defined` error, both of which are non-descriptive and very unhelpful.
> 
> We should also suggest how to restructure components. Blocks are not always a clean function wrap, they require restructuring of components in order to work properly. Furthermore, we can remind developers to use the `<For />` component when `.map` is used on a block.
> 
> 2. We have not defined the proper use cases of `block()`
> 
> We still do not know where block **should** be used. We need to define rigid use cases where block is actually helpful. General guidelines like "more static than dynamic" is not really helpful to most React developers. 
> 
> This specific point can also help us with the 1st problem mentioned. By defining the proper use cases, we can remind developers when not and when to use blocks.
> 
> 3. We do not educate developers on how to use the "magic" of block
> 
> Our docs are lacking a lot of content for new developers to understand and use. This goes along with 2 and 3.
> 
> > For any efforts happening right now around Million.js, they will be paused for fixing this critical issue first.

Thanks for the "Shit hitting the fan" image. 😅😅😅

**Comment by SukkaW** [comment]
We need to establish a "best practices list" for million. We can also implement an eslint plugin to help developers identify the common issues.

**Comment by tobySolutions** [comment]
> We need to establish a "best practices list" for million. We can also implement an eslint plugin to help developers identify the common issues.

Yep! I agree with this.

**Comment by QuiiBz** [comment]
When the compiler fails due to an error on a component, I don't think we should throw an error and exit the process immediately. We should instead print a detailed warning about which component, at which line, caused an error and was **skipped** by the compiler. We could also print the component's code itself to properly highlight the error.

**Comment by aidenybai** [comment]
@QuiiBz  Yeah I agree with this suggestion. But sometimes they will just have block() wrappers that if it passes to runtime it will cause unexpected behavior. Maybe by "skip" it will basically remove the block(Component) wrapper itself?

**Comment by tobySolutions** [comment]
> @QuiiBz Yeah I agree with this suggestion. But sometimes they will just have block() wrappers that if it passes to runtime it will cause unexpected behavior. Maybe by "skip" it will basically remove the block(Component) wrapper itself?

Do you know that thing that React does at times where they provide links to their documentation in error messages or warnings? I think we would need something like that. I have no idea how to whip something like that up, but, we can figure it out.

**Comment by aidenybai** [comment]
#344

**Comment by tobySolutions** [comment]
> @aidenybai I have been helping `forgetti` fix `Invalid Hook Call` issue, see [lxsmnsyc/forgetti#15](https://github.com/lxsmnsyc/forgetti/pull/15) and [lxsmnsyc/forgetti#18](https://github.com/lxsmnsyc/forgetti/pull/18).
> 
> I belive we can introduce forgetti back to million very soon.

Oh awesome!

**Comment by aidenybai** [comment]
@SukkaW Yeah, the reason I removed forgetti in the first place was because it didn't make sense in the context of the project. But if it can help us fix invalid hook calls, then it is a HUGE bonus for the project

**Comment by tobySolutions** [comment]
I think this issue can be closed now @aidenybai??

**Comment by tobySolutions** [comment]
Fixed by #353
