### ISSUE TITLE
My question about your demo

### ISSUE THREAD

**Issue by lovetingyuan** [aidenybai/million#345]
It is not a bug, it is just my personal doubt.

I notice in demo code, there are many empty div node in the dom tree,

```html
 <div>
        {Array(100)
          .fill(0)
          .map(() => (
            <div>
              <div>
                <div></div>
              </div>
            </div>
          ))}
      </div>
```

But million version does not render them at all! This does not make sense at all, looks like cheating...

If I comment this empty divs, react version can also achieve good rendering frame rates.

**Comment by aidenybai** [comment]
To render 100 divs is intentional, it is part of the demo (under the Notes section in the demo). Although I'm 99% sure you just found a bug, because Million is supposed to render those 100 empty divs, but it does not for some reason.

**Comment by aidenybai** [comment]
Found the issue. In the demo, it is using `<div>` which is automatically stripped by `el.cloneNode(true)`, as it is not HTML-spec compliant. By replacing the nodes with `<td>`, it can be put into a table.

Should be fixed in latest version

**Comment by lovetingyuan** [comment]
<tr key={String(random * count)}>
You force React to recreate the DOM(vnode) every time it renders, which doesn't make sense; at least it doesn't represent real-world development scenarios.
I know your library skips such process, but you cannot force React to recreate every node.

**Comment by aidenybai** [comment]
ah i see. I will correct the mistake now
