### ISSUE TITLE
feat: migrate + optimize the React transform in `packages/compiler`

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#348]
**Is your feature request related to a problem? Please describe.**

Currently, we have a babel-based compilation project under [`packages/compiler`](https://github.com/aidenybai/million/tree/main/packages/compiler). This works at the moment, but it can result in slow compilation times, as it is unoptimized and written with babel.

**Describe the solution you'd like**

We should work on a new SWC-based compiler that solves this problem. We should also look into optimizing the compiler to compile very fast. This would just apply to the [react transform](https://github.com/aidenybai/million/blob/main/packages/compiler/react.ts) and not the [optimizing compiler](https://github.com/aidenybai/million/blob/main/packages/compiler/optimize.ts).

The React transform's job is to "split" block components into two parts: the component that is rendered and the internal "block." For example this:

```jsx
function Button({ initial }) {
  const [count, setCount] = useState(initial);

  return <button onClick={() => setCount(count + 1)}>{count}</button>;
}

const ButtonBlock = block(Button);
``` 

would be roughly compiled to this:

```jsx
function Button({ initial }) {
  const [count, setCount] = useState(initial);

  return <button onClick={() => setCount(count + 1)}>{count}</button>;
}

function _component$({ initial }) {
  const [count, setCount] = useState(initial);
  return useBlock_component$({
    _$: () => setCount(count + 1),
    count,
  });
}

function _block$({ _$, count }) {
  return <button onClick={_$}>{count}</button>;
}

const ButtonBlock = _component$;
const useBlock_component$ = block(_block$);
```

The idea is to "extract" out the dynamics into a separate parent component. So here, `_component$` acts as a "controller" component for the `useBlock_component$` block component

**Describe alternatives you've considered**

We could continue optimizing the compiler, but because we have several contributors that know how to use Rust, getting performance benefits from a rewrite would be best.

**Comment by tobySolutions** [comment]
How's this going folks? :smiley:

**Comment by aidenybai** [comment]
Andrew is getting started on friday

**Comment by tobySolutions** [comment]
> Andrew is getting started on friday

Ok, awesome!

**Comment by tobySolutions** [comment]
How's this going folks? I hope y'all are doing well by the way?
