### ISSUE TITLE
feat: blocks can consume elements during hydration

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#351]
**Is your feature request related to a problem? Please describe.**

This is how our `packages/react-server` setup works:

Take some arbitrary component:

```jsx
function Component() {
	return <div>foo</div>
}
```

1. During SSR, allow react to render the HTML ([ref](https://github.com/aidenybai/million/blob/0ba00df02d91ab84df7c5f37c003f2a7cb248a7c/packages/react-server/index.ts#L66))

	Internally, this is passed into `React.renderToString`, which is sent to the client
	
2. During hydration, the element from SSR is replaced with a block ([ref](https://github.com/aidenybai/million/blob/0ba00df02d91ab84df7c5f37c003f2a7cb248a7c/packages/react-server/index.ts#L64))

	This is a full DOM element replacement.
	
This is obviously inefficient, we are basically replacing a lot of the DOM for no reason here.

**Describe the solution you'd like**

We need something that will set `this.l` of a block instance for hydration. Essentially we need to set a hydration id to the [loader component](https://github.com/aidenybai/million/blob/0ba00df02d91ab84df7c5f37c003f2a7cb248a7c/packages/react-server/index.ts#L10) with [`useId`](https://react.dev/reference/react/useId) during SSR. Then, during client render, we can grab the element via `document.querySelector` and set the `this.l` of a block instance.

You may hit some issues. We may need to make a ["hydration" mount](https://github.com/aidenybai/million/blob/0ba00df02d91ab84df7c5f37c003f2a7cb248a7c/packages/million/block.ts#L121) to get the cache correctly. 

This allows for efficient hydration without the need to replace the element.

**Comment by tobySolutions** [comment]
Curious to see what happens with this. I'll see if I can try this after the current issue I'm working on.
