### ISSUE TITLE
Where is the navbar?

### ISSUE THREAD

**Issue by thomaswcy** [aidenybai/million#356]

**Comment by thomaswcy** [comment]
I want to find the location of the navbar component of the million.dev website.

**Comment by tobySolutions** [comment]
Hey @thomaswcy! I don't understand what you mean by this. 

You don't know where the Navbar is?

**Comment by thomaswcy** [comment]
![image](https://github.com/aidenybai/million/assets/62056970/de72e1bf-f39a-4ee9-bf65-9536228fa7cd)
This one
I want to know where is the code for this

**Comment by thomaswcy** [comment]
@tobySolutions

**Comment by rschristian** [comment]
It's just configured [Nextra](https://nextra.site/), there's no component necessarily in this repo. The config is [here though](https://github.com/aidenybai/million/blob/main/website/theme.config.tsx)

**Comment by tobySolutions** [comment]
Thank you @rschristian! I hope this helps you @thomaswcy.

**Comment by tobySolutions** [comment]
I'll close this now.
