### ISSUE TITLE
Vite React TypeScript Support

### ISSUE THREAD

**Issue by GuiBibeau** [aidenybai/million#368]
**Description:**

Extend support for Vite React framework with TypeScript in the playground. The application should allow users to write and test Vite React code using TypeScript.

**Acceptance Criteria:**

- [ ] User can select Vite React (TypeScript) from the framework switcher.

- [ ] User can select Vite React (TypeScript) from the framework switcher.G

**Comment by aidenybai** [comment]
this is a comment from dimension!
