### ISSUE TITLE
Preact TypeScript Support

### ISSUE THREAD

**Issue by GuiBibeau** [aidenybai/million#369]
**Description:**

Extend support for Preact framework with TypeScript in the playground. The application should allow users to write and test Preact code using TypeScript.

**Acceptance Criteria:**

- [ ] User can select Preact (TypeScript) from the framework switcher.
- [ ] The playground supports Preact syntax and features when used with TypeScript.

**Comment by destroyer22719** [comment]
There is an issue on Preact's side, every single function overload, even if they take a generic of prop types, always return `VNode<any>` unlike React. I made an issue about it here:

https://github.com/preactjs/preact/issues/4040

For now, TypeScript Preact support will be halted

**Comment by destroyer22719** [comment]
I figured a way to still get TypeScript support with `VNode<any>` being set for all function overloads. This has been partially addressed with PR #385

**Comment by JoviDeCroock** [comment]
Sorry for the delay in fixing this, however in 10.16.0 this should be addressed

**Comment by tobySolutions** [comment]
> Sorry for the delay in fixing this, however in 10.16.0 this should be addressed

That'll be very helpful! Thank you very much.

**Comment by RANJEETJ06** [comment]
@tobySolutions  i think the issue has been resolved ,is plz close it

**Comment by tobySolutions** [comment]
Awesome! Thanks @RANJEETJ06!

**Comment by tobySolutions** [comment]
Thank you @JoviDeCroock!
