### ISSUE TITLE
Add Million.js to js-framework-benchmark

### ISSUE THREAD

**Issue by stan-kondrat** [aidenybai/million#37]
**Is your feature request related to a problem? Please describe.**
Local benchmark on my machine is 3 times slower relatively to others, _million_ results similar to _virtual-dom_.

**Describe the solution you'd like**
Add cpu/memory/os and browser version to benchmark page 

**Describe alternatives you've considered**
Use external service for benchmarking or allow user to post here results and then collect them to benchmark page, for example:

```
MacBook Air M1, 8 GB, Safari v14.1.1:

million x 26,400 ops/sec ±0.69% (24 runs sampled)
virtual-dom x 21,543 ops/sec ±0.54% (65 runs sampled)
vanilla x 3,865 ops/sec ±0.94% (24 runs sampled)
baseline x 81,198 ops/sec ±2.52% (16 runs sampled)
Fastest is baseline

```

**Comment by aidenybai** [comment]
It seems like this is not an difference with your machine, a newer update of million has made it slower. In regards to the external service - I'm not sure of anything that could provide some functionality like this. Investigating now

**Comment by stan-kondrat** [comment]
Results for google chrome looks good

```
https://million-benchmarks.netlify.app/

MacBook Air M1, 8 GB, Google Chrome v91.0.4472.106:

list-render:
million x 24,017 ops/sec ±9.10% (22 runs sampled)
virtual-dom x 18,777 ops/sec ±11.24% (47 runs sampled)
vanilla x 8,669 ops/sec ±0.74% (48 runs sampled)
baseline x 19,539 ops/sec ±0.48% (20 runs sampled)
Fastest is million
```

**Comment by aidenybai** [comment]
Interesting - I might be mistaken then.

**Comment by stan-kondrat** [comment]
It would be very helpful if you had time to add _million.js_ to [js-framework-benchmark](https://github.com/krausest/js-framework-benchmark) 
https://krausest.github.io/js-framework-benchmark/current.html

**Comment by willdoescode** [comment]
@aidenybai ill do this when I get home

**Comment by willdoescode** [comment]
CPU should not be needed as the CPU would proportionally effect all other frameworks and libraries we are benchmarking against but I will look into getting millionjs onto external benchmarking sites as well as benchmarking different browsers.

**Comment by anddddrew** [comment]
i'll be taking this on 👍

**Comment by aidenybai** [comment]
@anddddrew Just as a guideline for this issue, you'll need to fork https://github.com/krausest/js-framework-benchmark.

They have some specific rules you need to follow, let me know if you need any help with the benchmarks :)

**Comment by aidenybai** [comment]
Hey @anddddrew, just pinging to see if there are any updates or if you need any help with this task. If you're not available, no worries, I can take over this issue

**Comment by ryansolid** [comment]
If anyone has any questions about the rules or details on what works well in the benchmark I'm open to answering them. I'm very familiar with this benchmark.

**Comment by jasonappah** [comment]
Spoke to @anddddrew yesterday - he wasn't able to get around to this, but I started working on it yesterday (see [here](https://github.com/jasonappah/js-framework-benchmark/tree/feat/million)) and plan on finishing tonight. Will post here/dm if I have any questions!

**Comment by aidenybai** [comment]
Update: we're close! Expect a PR from @jasonappah sometime in the next 24h!

**Comment by jasonappah** [comment]
Just created https://github.com/krausest/js-framework-benchmark/pull/1074 :)

**Comment by frederikhors** [comment]
https://github.com/krausest/js-framework-benchmark/pull/1074 is still a draft, right?

**Comment by aidenybai** [comment]
Yes, still a draft

**Comment by aidenybai** [comment]
If keyed isn't working it may be an implementation issue in million vdom I suspect. I think it's okay to go with non-keyed for now so we at least have some initial benchmarks @jasonappah.

**Comment by aidenybai** [comment]
we did it!!
