### ISSUE TITLE
Create New Files

### ISSUE THREAD

**Issue by GuiBibeau** [aidenybai/million#370]
**Description:**

Implement a feature that allows users to create new files within the playground. This feature should be intuitive and easy to use.

**Acceptance Criteria:**

- [ ] User can create a new file through a clearly marked interface.
- [ ] The new file is added to the file system and is editable by the user.

**Comment by blyncnov** [comment]
Can I take on this issue? would love to work on this

**Comment by ethanniser** [comment]
#410
