### ISSUE TITLE
Bug: Compiler route isn't loading.

### ISSUE THREAD

**Issue by dreyfus92** [aidenybai/million#383]
**Describe the bug**
Is this supposed to be a normal behavior?

**To Reproduce**
1. Go to [million.dev/docs/compiler](https://million.dev/docs/compiler)

**Expected behavior**

**Screenshots**
![image](https://github.com/aidenybai/million/assets/85648028/19df0fcc-23d9-4a56-a893-ce0f2ba5d1f5)

**Device (please complete the following information):**
- MacOS
- Google Chrome

**Comment by tobySolutions** [comment]
Yep! I was just about to raise this. Thank you for raising it.

**Comment by aidenybai** [comment]
/docs/compiler was removed and merged into /docs/install
