### ISSUE TITLE
Integrate with `craco` (Create-React-App-Config-override)

### ISSUE THREAD

**Issue by atefBB** [aidenybai/million#388]
**Problem**
I'm using [craco](https://craco.js.org/) to override `webpack` config in my `cra` app, how to use `million` ?

**Solution**
To config `million` with `craco`, just add the line below to your `craco.js|ts` config file:
```js
// ...
webpack: {
        plugins: [million.webpack()],
}
//...
```
See this [link](https://craco.js.org/docs/configuration/webpack/).

**Comment by tobySolutions** [comment]
According to what I see here, I don't think you're following it correctly. I haven't tested yet, but, I assume with craco, it should be:

```js
module.exports = {
  // ...
  webpack: {
  // ...
    plugins: {
      add: [million.webpack()] ],
    },
 //  ...
};
```

Also, you have to import Million there.

**Comment by tobySolutions** [comment]
> **Problem** I'm using [craco](https://craco.js.org/) to override `webpack` config in my `cra` app, how to use `million` ?
> 
> **Solution** To config `million` with `craco`, just add the line below to your `craco.js|ts` config file:
> 
> ```js
> // ...
> webpack: {
>         plugins: [million.webpack()],
> }
> //...
> ```
> 
> See this [link](https://craco.js.org/docs/configuration/webpack/).

It might be helpful if we can see the entire config file. I think it's a minor issue with how you were following Craco's rules.

**Comment by atefBB** [comment]
> 

Yep ! I forgot to mention this:
`const million = require("million/compiler");`
it works for me with just :
`webpack: {
        plugins: [million.webpack()],
    }` !

**Comment by atefBB** [comment]
> 

I've just followed `craco docs` as mentioned in the [link](https://craco.js.org/docs/configuration/webpack/)!

**Comment by tobySolutions** [comment]
> > 
> 
> I've just followed `craco docs` as mentioned in the [link](https://craco.js.org/docs/configuration/webpack/)!

Does it work now?

**Comment by atefBB** [comment]
> > > 
> > 
> > 
> > I've just followed `craco docs` as mentioned in the [link](https://craco.js.org/docs/configuration/webpack/)!
> 
> Does it work now?

work as a charm !

**Comment by tobySolutions** [comment]
> > > > 
> > > 
> > > 
> > > I've just followed `craco docs` as mentioned in the [link](https://craco.js.org/docs/configuration/webpack/)!
> > 
> > 
> > Does it work now?
> 
> work as a charm !

Perfect! You can close the issue now!

**Comment by atefBB** [comment]
> According to what I see here, I don't think you're following it correctly. I haven't tested yet, but, I assume with craco, it should be:
> 
> ```js
> module.exports = {
>   // ...
>   webpack: {
>   // ...
>     plugins: {
>       add: [million.webpack()] ],
>     },
>  //  ...
> };
> ```
> 
> Also, you have to import Million there.

I make a mistake here, the correct config is: `plugins: {
      add: [million.webpack()] ],
    },` !

**Comment by SukkaW** [comment]
@tobySolutions Maybe you can mention it in our docs as well! We can add a few lines of code in a code block.

**Comment by atefBB** [comment]
> @tobySolutions Maybe you can mention it in our docs as well! We can add a few lines of code in a code block.

yes it should be mentioned in the docs !

**Comment by tobySolutions** [comment]
> > @tobySolutions Maybe you can mention it in our docs as well! We can add a few lines of code in a code block.
> 
> yes it should be mentioned in the docs !

I'll see what I can do Atef. Thanks for the issue.

**Comment by aidenybai** [comment]
Just added in the docs
