### ISSUE TITLE
bug: Uncaught TypeError in console

### ISSUE THREAD

**Issue by dotarjun** [aidenybai/million#389]
**Describe the bug**

**To Reproduce**
1. Go to 'https://million.dev/'
2. Open console

**Expected behavior**
Nothing in console

**Screenshots**
![image](https://github.com/aidenybai/million/assets/71163609/b4eedbc3-ec79-4f37-aace-f3c6573e5c84)

**Device (please complete the following information):**
 - OS: Arch Linux with i3 (😤)
 - Browser: Edge
 - Version: Version 112.0.1722.64

**Additional context**

**Comment by dotarjun** [comment]
Can I try to contribute?

**Comment by aidenybai** [comment]
you sure can. can you reply with the code sample of the problem code

**Comment by aidenybai** [comment]
Closing because issue does not have reproduction + due to inactivity. Please open another issue with a valid reproduction if you still have this issue.

https://antfu.me/posts/why-reproductions-are-required
