### ISSUE TITLE
[$100] feat: create linter

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#394]
We currently use [compiler](https://github.com/aidenybai/million/blob/04975c3ccfb2592cfb32661cf220e0f8906ede8a/packages/compiler/react/transform.ts#L397) [warnings](https://github.com/aidenybai/million/blob/04975c3ccfb2592cfb32661cf220e0f8906ede8a/packages/compiler/react/transform.ts#L561) to mark deoptimizations / limitations. What if we created a ESLint plugin for better developing experience?

**Comment by tobySolutions** [comment]
> We currently use [compiler](https://github.com/aidenybai/million/blob/04975c3ccfb2592cfb32661cf220e0f8906ede8a/packages/compiler/react/transform.ts#L397) [warnings](https://github.com/aidenybai/million/blob/04975c3ccfb2592cfb32661cf220e0f8906ede8a/packages/compiler/react/transform.ts#L561) to mark deoptimizations / limitations. What if we created a ESLint plugin for better developing experience?

This will be a life-saver!!

**Comment by adetoye-dev** [comment]
Hi @aidenybai 👋

Would love to take on this, is there a deadline for completion??

**Comment by tobySolutions** [comment]
Nope, there isn't. Go on ahead and take it @adetoye-dev!

**Comment by adetoye-dev** [comment]
> Nope, there isn't. Go on ahead and take it @adetoye-dev!

Thanks Tobi 😊

**Comment by ehizman** [comment]
I will take it

**Comment by tobySolutions** [comment]
Go ahead @ehizman!

**Comment by ashutosh887** [comment]
/attempt
Let me work on this if still not resolved

**Comment by tobySolutions** [comment]
I think it's safe to close this now @aidenybai. You have merged @Drex72's issue, right?

**Comment by sambhavgupta0705** [comment]
@aidenybai can I take this up?

**Comment by hussainsaify17** [comment]
Hey this issue is closed ? 
I'm interested in working in this. And I do have some question.
1. We need to publish eslint configs to npm and then use those custom eslint-rules.
2. I can make skeleton with some predefined rules and then we can add those rules after discussion what react pattern are we targeting which needs user attention.
/attempt #394

**Comment by adilkadivala** [comment]
Is this issue Still alive ??? if yes Then I wanna work for it..
