### ISSUE TITLE
bug: Compilation error on react 16

### ISSUE THREAD

**Issue by manoharc1999** [aidenybai/million#395]
**Describe the bug**
Compilation error while running on react 16

"react": "^16.13.0",
"react-dom": "^16.13.0",
"million": "2.4.4",
node: 14.21.3
npm: 6.14.18
webpack: 5

**To Reproduce**
1. Use React v16
2. Use For on any list
3. Compilation error

**Expected behavior**
project should compile

**Screenshots**
<img width="806" alt="image" src="https://github.com/aidenybai/million/assets/81562886/97b70d2c-a883-4771-8465-095eb8fe0185">

**Device (please complete the following information):**
 - OS linux
 - Browse chrome

**Additional context**

**Comment by manoharc1999** [comment]
@aidenybai  what is the minimum react version required?

**Comment by tobySolutions** [comment]
> **Describe the bug** Compilation error while running on react 16
> 
> "react": "^16.13.0", "react-dom": "^16.13.0", "million": "2.4.4", node: 14.21.3 npm: 6.14.18 webpack: 5
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use React v16
> 2. Use For on any list
> 3. Compilation error
> 
> **Expected behavior** project should compile
> 
> **Screenshots** <img alt="image" width="806" src="https://user-images.githubusercontent.com/81562886/244918195-97b70d2c-a883-4771-8465-095eb8fe0185.png">
> 
> **Device (please complete the following information):**
> 
> * OS linux
> * Browse chrome
> 
> **Additional context** Add any other context about the problem here.

I don't really see what the error is here, I'll definitely need more information so I can help out. Did you properly set up the compiler? Also, can I see your code?

**Comment by aidenybai** [comment]
should be fixed in latest version

**Comment by tobySolutions** [comment]
Oh! Interesting. 🤔🤔. So, it works now @manoharc1999?

**Comment by aidenybai** [comment]
Try upgrading to the latest beta, should work now possibly. Thanks for the patience so far @manoharc1999

**Comment by aidenybai** [comment]
This is very interesting, does this work on React 18? Or is it just React 16?

**Comment by manoharc1999** [comment]
@tobySolutions , @aidenybai 
Can it be bcz of this change https://github.com/aidenybai/million/pull/311/files

**Comment by manoharc1999** [comment]
> Try upgrading to the latest beta, should work now possibly. Thanks for the patience so far @manoharc1999

Still not working in latest beta :(

**Comment by aidenybai** [comment]
Update on this: We are not actively supporting any React version under React 18 until future notice.

**Comment by manoharc1999** [comment]
Cannot resolve react-dom/client

> > **Describe the bug** Compilation error while running on react 16
> > "react": "^16.13.0", "react-dom": "^16.13.0", "million": "2.4.4", node: 14.21.3 npm: 6.14.18 webpack: 5
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Use React v16
> > 2. Use For on any list
> > 3. Compilation error
> > 
> > **Expected behavior** project should compile
> > **Screenshots** <img alt="image" width="806" src="https://user-images.githubusercontent.com/81562886/244918195-97b70d2c-a883-4771-8465-095eb8fe0185.png">
> > **Device (please complete the following information):**
> > 
> > * OS linux
> > * Browse chrome
> > 
> > **Additional context** Add any other context about the problem here.
> 
> I don't really see what the error is here, I'll definitely need more information so I can help out. Did you properly set up the compiler? Also, can I see your code?



> **Describe the bug** Compilation error while running on react 16
> 
> "react": "^16.13.0", "react-dom": "^16.13.0", "million": "2.4.4", node: 14.21.3 npm: 6.14.18 webpack: 5
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use React v16
> 2. Use For on any list
> 3. Compilation error
> 
> **Expected behavior** project should compile
> 
> **Screenshots** <img alt="image" width="806" src="https://user-images.githubusercontent.com/81562886/244918195-97b70d2c-a883-4771-8465-095eb8fe0185.png">
> 
> **Device (please complete the following information):**
> 
> * OS linux
> * Browse chrome
> 
> **Additional context** Add any other context about the problem here.
