### ISSUE TITLE
bug: with Nextjs

### ISSUE THREAD

**Issue by kamalkech** [aidenybai/million#402]
![image](https://github.com/aidenybai/million/assets/1313428/5ab6f053-8fd4-4ef1-8864-ece401030fab)

??

**Comment by kamalkech** [comment]
@willdoescode  closed ?!!!

**Comment by ls-devs** [comment]
@ssibrahimbas You must import from "million/react" and just 
```js
export default block(HeadSection);
```

**Comment by ssibrahimbas** [comment]
ouv is ok, when I did it like this, 2 errors disappeared. Thanks

**Comment by brunoeduardodev** [comment]
I've reproduced it on codesandbox, it seems like a Type error to me...
[Check it](https://codesandbox.io/p/sandbox/hungry-roentgen-h66nm8?file=%2Fapp%2Fpage.tsx%3A6%2C29)

<img width="1368" alt="image" src="https://github.com/aidenybai/million/assets/50559336/a2736fc4-7a13-4874-9deb-7d61d17cfeab">

**Comment by aidenybai** [comment]
Seems to be fixed.
