### ISSUE TITLE
feat: passing JSX as props

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#403]
What if we could do something like this?

```jsx
const Block = block(function({ children }) {
	return ...
})

<Block><div>bonk</div></Block>
```

**Comment by tobySolutions** [comment]
> What if we could do something like this?
> 
> ```jsx
> const Block = block(function({ children }) {
> 	return ...
> })
> 
> <Block><div>bonk</div></Block>
> ```

Hmm, this is crazy. Changes the DX significantly. 


I'd like something like this, but, what if I wasn't using React? I'd use `block()`?

**Comment by aidenybai** [comment]
works
