### ISSUE TITLE
bug: React hook "useContext" cannot be destructured

### ISSUE THREAD

**Issue by TaylorBruening** [aidenybai/million#408]
**Describe the bug**
The React hook "useContext" does not appear to be currently supported.
When using the built in React hook "useContext" to control global variables in conjuction with  import {block} for components, it fails to destructure contexts that are initialized as null then later updated.

**To Reproduce**
simple React code with contexts that cannot be destructured:
`
import React, { createContext, useState, useContext } from 'react';
import { block } from 'million/react';

// Create Context
export const StoreContext = createContext(null);

// Create Provider as Higher Order Component
export const StoreProvider = ({children}) => {
  const [store, setStore] = useState({
    name: 'Test',
    age: 30,
  });

  // Wrap component with block() for better performance
  const WrappedComponent = block(function WrappedComponent() {
    return <StoreContext.Provider value={store}>{children}</StoreContext.Provider>
  });

  return <WrappedComponent />
}

// Usage
function ExampleComponent() {
  const store = useContext(StoreContext);
  // Now you can use store.name and store.age
}
`

`
function App() {
  return (
    <StoreProvider>
      <ExampleComponent />
      {/* ...other components */}
    </StoreProvider>
  );
}

export default App;
`

**Expected behavior**
should be able to use React hook "useContext"

**Screenshots**
![image](https://github.com/aidenybai/million/assets/31892579/7ff5120d-3f23-445b-afb5-87ea9bfd809d)

**Comment by TaylorBruening** [comment]
this is a basic example, not my application. Even when the store is not wrapped with block, and the lowest level components are wrapped in block, it does not support useContext that is initialized to null.

This was the latest attempt to see if it would work by providing whatever injection block provides at the highest level, which that doesnt work either.

**Comment by tobySolutions** [comment]
> If you can provide a working code snippet that provides a block component that is also bringing in a context that is initialized to null, then later updated, I would appreciate it, and it would also provide a good copy/paste for anyone else encountering this problem in the future

For sure, let me try to reach out to Aiden so we can come up with something.

Thank you for this issue.

**Comment by aidenybai** [comment]
@TaylorBruening note that you need to declare block on the top level scope. Using block within a store provider is not allowed:


Not allowed: 

```js
// Create Provider as Higher Order Component
export const StoreProvider = ({ children }) => {
  const [store, setStore] = useState({
    name: 'Test',
    age: 30,
  });

  // Wrap component with block() for better performance
  const WrappedComponent = block(function WrappedComponent() {
    return (
      <StoreContext.Provider value={store}>{children}</StoreContext.Provider>
    );
  });

  return;
};
```

Allowed:

```js
 // Wrap component with block() for better performance
  const WrappedComponent = block(function WrappedComponent() {
    return (
      <StoreContext.Provider value={store}>{children}</StoreContext.Provider>
    );
  });

// Create Provider as Higher Order Component
export const StoreProvider = ({ children }) => {
  const [store, setStore] = useState({
    name: 'Test',
    age: 30,
  });

  return;
};
```

**Comment by nojiritakeshi** [comment]
@aidenybai
Excuse me for cutting in.
Let me ask you a question.

> note that you need to declare block on the top level scope. Using block within a store provider is not allowed:

Is it correct that this principle exists because `block` is a custom hook?
I think it would be better to start with `use` like the naming convention of React hooks, so that it can be recognized as Hooks at a glance.

Sorry if I'm misguided or if you've already taken that into consideration.

**Comment by aidenybai** [comment]
@nojiritakeshi block is a function that creates a Higher Order Component. We use a compiler to scan for that function, and we assume that block is used at the global scope.
