### ISSUE TITLE
bug: SVG support

### ISSUE THREAD

**Issue by vital487** [aidenybai/million#412]
**Describe the bug**
Components are not rendered when wrapped with "block()".

**To Reproduce**
I am using SVG, so I'm using "g", "text" and "rect" elements. They are not showing up for some reason.

**Expected behavior**
They should be visible. 😀

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Firefox
 - Million Version: 2.4.6-beta.0
 - React Version: ^18.2.0
 - React DOM Version: ^18.2.0

**Comment by vital487** [comment]
Hi @aidenybai,

Do you have an idea on when you will have a fix version for this?

Thank you in advance!

**Comment by aidenybai** [comment]
can you send the SVG you are using @vital487?

**Comment by vital487** [comment]
@aidenybai, this is work related so I cannot send it, but I will create a sandbox for this with an example.

**Comment by vital487** [comment]
@aidenybai, here is a link https://codesandbox.io/s/peaceful-varahamihira-nhs8jl?file=/src/App.js

You can change in the App component the `BarBlock` for the `Bar` and see it working.

**Comment by aidenybai** [comment]
thanks for the repro! on it :) @vital487

**Comment by aidenybai** [comment]
This is unfortunately intentional, since we insert `<slot>` tags to insert blocks. The output is as so:

```js
<div class="App">
  <h1>SVG Example</h1>
  <svg width="300px" height="300px">
    <g class="content">
      <slot>
        <g>
          <rect
            width="100"
            y="100"
            height="20"
            ry="2"
            rx="4"
            fill="black"
          ></rect>
          <rect width="20" y="100" height="20" ry="2" rx="4" fill="#ddd"></rect>
        </g>
      </slot>
    </g>
  </svg>
</div>;
```

However, I am open to making this work. What are your thoughts on defining a `type` for the wrapper element?

```js
const something = block(() => {
	...
}, { type: 'g' });
```

**Comment by vital487** [comment]
@aidenybai, for me it seems ok.

**Comment by aidenybai** [comment]
@vital487 update: fixed in latest release. should automatically detect svgs

**Comment by vital487** [comment]
@aidenybai thank you for your work on this issue and for the whole package. 😁

**Comment by aidenybai** [comment]
for sure :) thank you for the repro and help!! @vital487

**Comment by vital487** [comment]
Hi @aidenybai,

Today I was trying to implement your fix, but I received an error. I think I am doing something wrong. Can you please check this link? https://codesandbox.io/s/peaceful-varahamihira-nhs8jl?file=/src/App.js

If you comment the `<BarBlock1 /> <BarBlock2 />` it works fine.

Thank you.

**Comment by vital487** [comment]
@aidenybai, any updates on this? Thank you.
