### ISSUE TITLE
feat: Passing a Set object to the For component.

### ISSUE THREAD

**Issue by nojiritakeshi** [aidenybai/million#413]
**Is your feature request related to a problem? Please describe.**
Currently, only arrays can be passed to the For component, but it may be more useful to be able to pass Set objects as well.

**Describe the solution you'd like**
Make "each" in the For component a union type or create a new argument.

**Describe alternatives you've considered**
**Additional context**
`<For each={new Set(["apple", "orange", "banana"])}>{(item, index) => Block}</For>`
or 
`<For hoge={new Set(["apple", "orange", "banana"])}>{(item, index) => Block}</For>`

Sorry if this is not a very meaningful suggestion.
If it's a feature that makes sense, I'm happy to help.

**Comment by tobySolutions** [comment]
Hmm, not sure @nojiritakeshi. I mean, for is a component that is made for optimized array rendering. 


Not sure, how this ties in with what it does 🤔🤔🤔

**Comment by brunoeduardodev** [comment]
`Set` might be used for improving performance on calculations with a very big number of items on some scenarios, so it might be cool to also accept it

https://stackoverflow.com/a/39010462

**Comment by aidenybai** [comment]
This is cool, but couldn't you just:

```
<For each={[...new Set([1,2,3])]}>
```

AFAIK, this is idiomatic in React as well, as it requires an array spread anyway

**Comment by nojiritakeshi** [comment]
> this is idiomatic in React as well, as it requires an array spread anyway

Certainly, many use cases may be met that way!
Thanks, @aidenybai !!

**Comment by tobySolutions** [comment]
Alright @nojiritakeshi! Thank you very much for this.

**Comment by nojiritakeshi** [comment]
I thought it would be interesting to have a For option to not show duplicate data.
But this might be a snake oil....

**Comment by aidenybai** [comment]
Closing this :)
