### ISSUE TITLE
bug: Server Error while generating pages

### ISSUE THREAD

**Issue by iyay** [aidenybai/million#419]
Hi, 

i got this error while generating pages

<img width="981" alt="Screenshot 2023-06-14 at 15 27 09" src="https://github.com/aidenybai/million/assets/44457/147841c0-facf-44b1-9950-e289b8a0c9bc">

i have million compiler imported

I am using:

Next: 12.1.0
React: 18.2.0
Node: 18.16.0

**Comment by Acejii** [comment]
me too

**Comment by brunoeduardodev** [comment]
did you setup the compiler on next.config.js?

**Comment by aidenybai** [comment]
@iyay what version Million.js are you using? Can you send the next.config.js?

**Comment by tobySolutions** [comment]
Any updates @iyay?

**Comment by aidenybai** [comment]
Closing because issue does not have reproduction + due to inactivity. Please open another issue with a valid reproduction if you still have this issue.

https://antfu.me/posts/why-reproductions-are-required
