### ISSUE TITLE
bug: Cannot show the component name correctly in React Developer Tools

### ISSUE THREAD

**Issue by glenncai** [aidenybai/million#421]
**Describe the bug**
When I use the `block()` API, it causes the component name cannot show on the `React Developer Tools` (Chrome) correctly, and it only shows the name is _anonymous$. The expected result is `QuestionCard`.

**Screenshots**
![bug_picture](https://github.com/aidenybai/million/assets/60476708/b7de70ad-221e-4600-a371-42edc56d330f)

**Code**
```typescript
import { block } from 'million/react';

type QuestionCardProps = {
  id: string;
  title: string;
  isPublished: boolean;
};

const QuestionCard = block<QuestionCardProps>(props => {
  const { id, title, isPublished } = props;

  function edit(id: string) {
    console.log(id);
  }

  return (
    <div key={id}>
      <strong>{title}</strong>
      &nbsp;
      {isPublished ? (
        <span style={{ color: 'green' }}>Already published</span>
      ) : (
        <span>Not published</span>
      )}
      &nbsp;
      <button onClick={() => edit(id)}>Edit Question</button>
    </div>
  );
});

export default QuestionCard;

```

**Comment by tobySolutions** [comment]
> **Describe the bug**
> When I use the `block()` API, it causes the component name cannot show on the `React Developer Tools` (Chrome) correctly, and it only shows the name is _anonymous$. The expected result is `QuestionCard`.
> 
> **Screenshots**
> ![bug_picture](https://github.com/aidenybai/million/assets/60476708/b7de70ad-221e-4600-a371-42edc56d330f)
> 
> **Code**
> ```typescript
> import { block } from 'million/react';
> 
> type QuestionCardProps = {
>   id: string;
>   title: string;
>   isPublished: boolean;
> };
> 
> const QuestionCard = block<QuestionCardProps>(props => {
>   const { id, title, isPublished } = props;
> 
>   function edit(id: string) {
>     console.log(id);
>   }
> 
>   return (
>     <div key={id}>
>       <strong>{title}</strong>
>       &nbsp;
>       {isPublished ? (
>         <span style={{ color: 'green' }}>Already published</span>
>       ) : (
>         <span>Not published</span>
>       )}
>       &nbsp;
>       <button onClick={() => edit(id)}>Edit Question</button>
>     </div>
>   );
> });
> 
> export default QuestionCard;
> 
> ``` 
> 
> 

Oh really? Thank you for the issue @glenncai!! 😁😁

**Comment by aidenybai** [comment]
This is because we hoist the Component function out and we need to name it something. Notes for the future PR: Detect if it is a function declaration / expression and name it something. Otherwise, fallback to _anonymous$

**Comment by tobySolutions** [comment]
> This is because we hoist the Component function out and we need to name it something. Notes for the future PR: Detect if it is a function declaration / expression and name it something. Otherwise, fallback to _anonymous$

Thank you for this Aiden. 😁😁
