### ISSUE TITLE
bug: About the return value of an increment

### ISSUE THREAD

**Issue by nojiritakeshi** [aidenybai/million#422]
**Describe the bug**
In the following processing of the while statement in million/array.ts, the first processing when oldHeadChild is Falsy is wasted.
```ts
 let oldHead = 0;
~~
let oldHeadChild = oldChildren[0];
~~
while (oldHead <= oldTail && newHead <= newTail) {
      if (!oldHeadChild) {
        oldHeadChild = oldChildren[++oldHead];
        continue;
      }
```
The return value of the incremented (++) value will be the value before the increment.
In other words, I think it would be the following.
```ts
 let oldHead = 0;
oldChildren[++oldHead] == oldChildren[0]
```
Actually, it may not be a bug, though, since the second time it is processed, it is referenced by the incremented value.
**To Reproduce**

**Expected behavior**
**Screenshots**
**Device (please complete the following information):**
**Additional context**
The following modifications can be considered.
```ts
if (!oldHeadChild) {
        ++oldHead
        oldHeadChild = oldChildren[oldHead];
        continue;
}
```
I have not checked all of them, but it seems to me that there are other areas that could be similarly corrected.

If my suggestion is correct, I can help you revise it.

**Comment by aidenybai** [comment]
I think this may be intentional? This is a port of the blockdom implementation: https://github.com/ged-odoo/blockdom/blob/main/src/list.ts

**Comment by tobySolutions** [comment]
So, should we close this @aidenybai?

**Comment by nojiritakeshi** [comment]
My apologies. I made a very elementary mistake. Maybe I was sleepwalking.
My face is hot with embarrassment.
CLOSED.

**Comment by aidenybai** [comment]
1. this was a very valid concern and we should probably refactor this and it was not a bad question at all so you're totally fine
2. this is the most unique way someone has closed an issue
