### ISSUE TITLE
Turn off terminal warning

### ISSUE THREAD

**Issue by francisashley** [aidenybai/million#424]
Hello, can we switch off the "Components will cause degraded performance. Ideally, you should use DOM elements instead." warning in the terminal some how?

**Comment by aidenybai** [comment]
Added in commit e635ea3, will be released in next patch

**Comment by francisashley** [comment]
Thank you! 🙌

**Comment by tobySolutions** [comment]
> Added in commit [e635ea3](https://github.com/aidenybai/million/commit/e635ea3635e5eeb6cb3dd53d793f9c6c3eeafa53), will be released in next patch

Great!

**Comment by aidenybai** [comment]
Fixed in 2.4.6
