### ISSUE TITLE
feat: webpack.config.js example for millionjs which works with the official webpack doc?

### ISSUE THREAD

**Issue by blurymind** [aidenybai/million#425]
**Is your feature request related to a problem? Please describe.**
When you go to 
https://webpack.js.org/configuration/plugins/
An example webpack.config.js file looks like this
```
module.exports = {
  //...
  plugins: [
    new webpack.DefinePlugin({
      // Definitions...
    }),
  ],
};
```
plugins are constructed. This is how it is in all of my projects too

When you go to 
https://million.dev/docs/install

example of the same config if you want to use million:
```
webpack.config.js
import million from 'million/compiler';
 
export default {
  plugins: [million.webpack()],
};
```

So now try to fit million in my project and it's instantly incompatible.
- million for me needs to be imported with require, cant use import
- million.webpack() is not a constructor, I can not do new million.webpack()
- even putting million in the plugin array, it fails to run
```
myProject\node_modules\million\node_modules\@babel\core\lib\config\full.js:266
    throw new _configError.default([`Preset ${formattedPresetName} requires a filename to be set when babel is called directly,`, `\`\`\``, `babel.transformSync(code, { filename: 'file.ts', presets: [${formattedPresetName}] });`
, `\`\`\``, `See https://babeljs.io/docs/en/options#filename for more information.`].join("\n"));
          ^
```

**Describe the solution you'd like**
I would like to use million in my project, but cant find a single project or config example where its used with react+typescript+webpack+babel
Can someone enlighten me? Can this work combined with those things and if so - how do I set it up?
How would a functional complete webpack.config.js file look like in a real demo project?

I am really confused as to how to setup million in the context of webpack with the documentation at the moment. Can we clarify if a standard webpack config would work and if so how? If thats not the case - can we get a single demo project that uses webpack? Guess my request here is just better documentation/example, but really the hope for me is I can fit it in my existing project to evaluate performance gains

**Comment by aidenybai** [comment]
Million.js uses [unplugin](https://github.com/unjs/unplugin#webpack) to support multiple build tools, including the [webpack usage](https://github.com/unjs/unplugin#webpack). It looks like we are not showing the correct usage, and we need to correct it. Can you try something like this?

```js
module.exports = {
  plugins: [
    require('million/compiler').webpack({ /* options */ }),
  ],
}
```

**Comment by tobySolutions** [comment]
Did you try it yer @blurymind?

**Comment by blurymind** [comment]
Ah yes I tried this and ran into the other issue that I have, which can also be seen with vite. Maybe it wasn't me improperly using it causing it

**Comment by blurymind** [comment]
I would still appreciate it if the documentation is updated to be more inline with what webpack's doc shows for examples.

It made me believe that I wasn't using it correctly

**Comment by aidenybai** [comment]
we can definitely consider adding a note about usage

**Comment by AndreiMaga** [comment]
I want to use millionjs in one of my projects and came across this exact problem.

Looking at the error it mentions filename and looking at the babel docs it states this:

- Options like ["test"](https://babeljs.io/docs/options#test), ["exclude"](https://babeljs.io/docs/options#exclude), and ["ignore"](https://babeljs.io/docs/options#ignore) require the filename for string/RegExp matching.

Looking at the code it seems like the filename is not passed as a parameter https://github.com/aidenybai/million/blob/d367240cb4e1a59e0cfb58a614e6df30b5f6b1ea/packages/compiler/plugin.ts#L36 

I changed this line in my `node_modules/million/dist/compiler.cjs` to (see code below) and it seems like it does the trick, can you please take a look into fixing this ?
```ts
      const result = await core.transformAsync(code, { plugins, filename: id });

```

**Comment by aidenybai** [comment]
Hey @AndreiMaga, will be shipped in a new PR + release. Thank you for notifying us :D
