### ISSUE TITLE
bug: [vite] Internal server error: [BABEL] unknown file: Preset /* your preset */ requires a filename to be set when babel is called 

### ISSUE THREAD

**Issue by blurymind** [aidenybai/million#426]
When I try to run the project after adding the million.vite() plugin to vite.config.ts, I get this error:

```
16:33:39 [vite] Internal server error: [BABEL] unknown file: Preset /* your preset */ requires a filename to be set when babel is called directly,
babel.transformSync(code, { filename: 'file.ts', presets: [/* your preset */] });
See https://babeljs.io/docs/en/options#filename for more information.
  Plugin: million
```

**Comment by aidenybai** [comment]
Can you send your full config file?

**Comment by tobySolutions** [comment]
Hello @blurymind, how are you?! Any updates on this?

**Comment by blurymind** [comment]
Hi so I am on holiday for the next week so might take some time to get back to you on this, but its worth noting that the error occurs inside the node modules dependencies of million, inside babel if I remember right

**Comment by tobySolutions** [comment]
> Hi so I am on holiday for the next week so might take some time to get back to you on this, but its worth noting that the error occurs inside the node modules dependencies of million, inside babel if I remember right

Noted @blurymind!! 💯💯

**Comment by blurymind** [comment]
worth noting that I get the same error when trying it with webpack. I care more about the webpack version of my project that blows up

**Comment by aidenybai** [comment]
Will be fixed in the next release :)
