### ISSUE TITLE
Playground: Persist current playground locally

### ISSUE THREAD

**Issue by brunoeduardodev** [aidenybai/million#430]
**Description:**

It would be a nice experience to the user if we persist their code after they close the browser / open again, so we can prevent them loosing their progress when testing million.

We probably can start by storing the files on local storage as JSON.

**Acceptance Criteria:**

- [ ] The current code on the playground should be persisted between sessions.

**Comment by aidenybai** [comment]
I believe Moon.js can persist this via url hash. Thoughts on this strategy as well?

**Comment by brunoeduardodev** [comment]
this would work, even for #372, it’s an easy win but I think the urls ends up very ugly, but functional
