### ISSUE TITLE
bug: 2nd CTA button "millionjs in 100 seconds" is slightly too low contrast

### ISSUE THREAD

**Issue by CBID2** [aidenybai/million#431]
**Describe the bug**
The color of the second button clashes with the color of its text, which according to WAVE's accessibility checker (see information in screenshot below) makes it difficult for users with low vision to read.  

**Possible Solution**
Wave recommends the following:
"Increase the contrast between the foreground (text) color and the background color. Large text (larger than 18 point or 14 point bold) does not require as much contrast as smaller text."
Perhaps we can find a color that's similar to the current colors and accessible. 

**Expected behavior**
N/A
**Screenshots**
![low contrast](https://github.com/aidenybai/million/assets/105683440/817635de-3068-4fba-af63-ad0b7c04b5d9)

**Device (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 114

**Additional context**

**Comment by aidenybai** [comment]
Will be fixed in a bundled PR soon.
