### ISSUE TITLE
bug: Read more links on blog creates inaccessibility 

### ISSUE THREAD

**Issue by CBID2** [aidenybai/million#432]
**Describe the bug**
According to WAVE, the read more buttons "results in additional navigation and repetition for keyboard and screen reader users", which can be annoying. 

**Possible Solution**
Remove them.  

**Expected behavior**

**Screenshots**

![read more issue](https://github.com/aidenybai/million/assets/105683440/9371d01f-093f-416b-8461-7f17250bc74c)

**Device (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 114

**Additional context**

**Comment by olaoluwaayanbola** [comment]
hello @CBID2 can this issue be assigned to me

**Comment by CBID2** [comment]
> hello @CBID2 can this issue be assigned to me 

I'm not a maintainer sorry @olaoluwaayanbola

**Comment by olaoluwaayanbola** [comment]
oh alright @tobySolutions

**Comment by aidenybai** [comment]
@olaoluwaayanbola any updates?

**Comment by berabappaditya** [comment]
i want to solve this issue

**Comment by Timonwa** [comment]
Hi @berabappadity. Thank you for your interest in this issue. But someone is currently working on this. Is there any other open issues that interest you?
