### ISSUE TITLE
bug: Docs page needs improvement

### ISSUE THREAD

**Issue by CBID2** [aidenybai/million#433]
**Describe the bug**
On the Docs page, there are 3 links that say "react", 

**Possible Solution**
There should only be 1 link to React in such a short time, so remove two of them.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]

**Additional context**

**Comment by olaoluwaayanbola** [comment]
Hey, can I be assigned this issue

**Comment by oliverloops** [comment]
Hi @CBID2, I don't believe is necessary to categorize this multiple external react's website reference observation as a bug, I think this is useful and added for accessibility reasons because of screen readers. 

Thanks for your comprehension.

**Comment by CBID2** [comment]
> Hi @CBID2, I don't believe is necessary to categorize this multiple external react's website reference observation as a bug, I think this is useful and added for accessibility reasons because of screen readers. 
> 
> 
> 
> Thanks for your comprehension.

Thanks for your response @oliverloops! :) This was an issue that was mentioned in a Twitch stream

**Comment by aidenybai** [comment]
Fixed
