### ISSUE TITLE
bug: mobile menu is inaccessible 

### ISSUE THREAD

**Issue by CBID2** [aidenybai/million#434]
**Describe the bug**
On mobile, the menu items are still able to be focused even when the menu is closed.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]

**Additional context**

**Comment by olaoluwaayanbola** [comment]
Hey, can i take on the task of resolving this bug?

**Comment by tobySolutions** [comment]
> Hey, can i take on the task of resolving this bug?

All yours @olaoluwaayanbola!! 🚀🚀🚀🚀

**Comment by olaoluwaayanbola** [comment]
Hey @CBID2 Could you please share a screenshot or describe how the error can be recreated? This will help me better understand the issue

**Comment by tobySolutions** [comment]
> Hey @CBID2 Could you please share a screenshot or describe how the error can be recreated? This will help me better understand the issue

That'll be really helpful if you could share that Chrissy @CBID2.

**Comment by tobySolutions** [comment]
Any updates on this @CBID2?

**Comment by CBID2** [comment]
> > Hey @CBID2 Could you please share a screenshot or describe how the error can be recreated? This will help me better understand the issue
> 
> 
> 
> That'll be really helpful if you could share that Chrissy @CBID2.

Hey @tobySolutions. I was just raising this and the other issues Emma and Graham were talking about on Twitch, so I recommend using that to get more context

**Comment by aidenybai** [comment]
@olaoluwaaayanbola any updates?
