### ISSUE TITLE
About the type of getComponent, the second argument of the createChildren function

### ISSUE THREAD

**Issue by nojiritakeshi** [aidenybai/million#437]
This is neither a bug nor a feature request, so I will ask in a blank issue.

Is it intended that the getComponent of the createChidren function in 'package/react' and 'package/preact' be of type any?

In the MillionArrayProps interface, `children` are defined as follows
```
children: (value: T, i: number) => ReactNode;.
```
And isn't the second argument of the createChildren function only passed the above `children`?
Sorry if it is ANY type that was intended.

**Comment by aidenybai** [comment]
@destroyer22719

**Comment by destroyer22719** [comment]
Hello, good timing. I'm currently a new contributor with the goal of improving the type safety of the million codebase, currently I am working on refactoring the code to remove the usage `any` type as it's bad practice, when I am done with my work the usage of the `any` will be minimal.

**Comment by nojiritakeshi** [comment]
> I'm currently a new contributor with the goal of improving the type safety of the million codebase, currently I am working on refactoring the code to remove the usage any type as it's bad practice, when I am done with my work the usage of the any will be minimal.

Oh! That's great!
Is there anything I can do?

**Comment by tobySolutions** [comment]
> > I'm currently a new contributor with the goal of improving the type safety of the million codebase, currently I am working on refactoring the code to remove the usage any type as it's bad practice, when I am done with my work the usage of the any will be minimal.
> 
> @destroyer22719 Oh! That's great!
> Is there anything I can do?

Yeah, sure! You can join the server and come have fun with us.

million.dev/chat

**Comment by destroyer22719** [comment]
Hello,

I created a PR that addressed your concerns #464

**Comment by nojiritakeshi** [comment]
@destroyer22719 
good job!
Thanks to #464, this issue will be resolved and closed.
