### ISSUE TITLE
bug: There's no type declarations for the path "million/preact"

### ISSUE THREAD

**Issue by Nyaacinth** [aidenybai/million#438]
**Describe the bug**
There's no type declarations for the path "million/preact", there's only "react.d.ts" for "million/react" at the root of package "million", and according to the doc, we need to import from "million/preact" to use it with preact. But it will just work as intended if you ignore the type error.

**To Reproduce**
1. Run command `pnpm add million` in your project folder
2. Create a file and try to `import { block } from "million/preact"`
3. See the ts-error

**Expected behavior**
Able to import with no error

**Screenshots**
![screenshot.png](https://i.ibb.co/z76c4D6/2023-06-18-16-59-44.png)

**Device (please complete the following information):**
 - Your Computer?

**Additional context**
Nope

**Comment by tobySolutions** [comment]
Yo @aidenybai, can you check this out?

**Comment by tobySolutions** [comment]
Hello @Nyaacinth, did you set up your compiler in Preact?

In the documentation, we have the steps follow when setting up Million in Preact


https://million.dev/docs/install can help you out.

**Comment by Nyaacinth** [comment]
> Hello @Nyaacinth, did you set up your compiler in Preact?
> 
> In the documentation, we have the steps follow when setting up Million in Preact
> 
> https://million.dev/docs/install can help you out.

Yes, set vite with `million.vite({ mode: "preact"})`, i think the problem is not about the compiler, because the code can run with correct behavior, there's only type errors

**Comment by tobySolutions** [comment]
> > Hello @Nyaacinth, did you set up your compiler in Preact?
> > 
> > In the documentation, we have the steps follow when setting up Million in Preact
> > 
> > https://million.dev/docs/install can help you out.
> 
> Yes, set vite with `million.vite({ mode: "preact" })`, i think the problem is not about the compiler, because the code can run with correct behavior, there're only type errors

Hmmm, thank you. Let me raise this up with the team and we can have a look. 👀👀

**Comment by nojiritakeshi** [comment]
@tobySolutions @Nyaacinth 
Is this a bug that only happens with pnpm?
> Yes, set vite with million.vite({ mode: "preact" }), i think the problem is not about the compiler, because the code can run with correct behavior, there're only type errors

If I restart VSCode after adding it, won't the error stop happening?

**Comment by Nyaacinth** [comment]
> Is this a bug that only happens with pnpm?

No, you can install the package with any valid node package manager, but the problem will continue to happen. You can check [this](https://www.npmjs.com/package/million?activeTab=code).

> If I restart VSCode after adding it, won't the error stop happening?

No, to avoid IDE-only errors, I always rerun `tsc` for checking, 

----

Overall, it might be only a re-export missing, since there's only `export * from './dist/react';` in the "react.d.ts". I think the only thing we need is just a re-`export * from './dist/preact';` in the "preact.d.ts" at the root of the package

**Comment by tobySolutions** [comment]
> Confirmed with v2.4.6, the bug still exists

It still exists?? 🤔🤔

**Comment by Nyaacinth** [comment]
As it got fixed in the latest release, I'll close this issue. Thank you all for developing this amazing lib!
