### ISSUE TITLE
bug: use block in another block error

### ISSUE THREAD

**Issue by gigasource** [aidenybai/million#439]
**Describe the bug**
Error from compiler : 

**Screenshots**
![image](https://github.com/aidenybai/million/assets/56248437/cef9ba19-4e9b-47d8-9f3b-05a724cf18a8)
![image](https://github.com/aidenybai/million/assets/56248437/399f1b10-8da1-4f18-9b8e-6f80a8fa70ae)
![image](https://github.com/aidenybai/million/assets/56248437/ae664962-91a4-4daa-8f21-79cf3749cbfa)

**Comment by aidenybai** [comment]
Fixed in 2.4.6
