### ISSUE TITLE
feat: Million Meta-framework

### ISSUE THREAD

**Issue by brillout** [aidenybai/million#445]
Hi, author of [vite-plugin-ssr](https://vite-plugin-ssr.com) here.

While Million works with Next.js it can, at some point, make senses to break compatibility with Next.js.

If that's something you're considering, then let me know as the upcoming v1 release enables libraries like Million to easily build their own meta framework. See:
 - https://vite-plugin-ssr.com/build-your-own-framework
 - https://github.com/brillout/vike-react/tree/main/vike-react (see https://vite-plugin-ssr.com/vike-packages)
 - https://github.com/brillout/restack (showcasing a framewrok that completely abstracts vite-plugin-ssr away from the user)

Congrats on the very successful Million launch :rocket:.

**Comment by aidenybai** [comment]
Thank you @brillout! Big fan of you and your work :). FWIW this is definitely an area we are considering to work in

**Comment by tobySolutions** [comment]
Thank you @brillout! 🙌🙌

**Comment by brillout** [comment]
> FWIW this is definitely an area we are considering

Keep me in the loop! Could be very exciting to do something together. More than happy to introduce new lower-level APIs for accommodating a Million Meta-framework (although the V1 design is very flexible already, so chances are that no change is required, even for advanced integrations such as RSC).
