### ISSUE TITLE
bug: Error Thrown When Using React Hooks in a Function

### ISSUE THREAD

**Issue by oshrit-marktrix** [aidenybai/million#447]
**Describe the bug**
When attempting to use React hooks as your example, an error is consistently thrown. 

**To Reproduce**
```
import { block } from "million/react";

import { useState } from "react";

export const Counter = block(function Counter({ initialCount }) {
  const [count, setCount] = useState(initialCount);
  const handleClick = () => {
    setCount(count + 1);
  };

  return <button onClick={handleClick}>{count}</button>;
});

```

**Screenshots**
![image](https://github.com/aidenybai/million/assets/121755690/9060933f-8dec-4e2b-8b08-d1b3e643b08d)

**Comment by sahajjain1** [comment]
any slutions on the above issue i am getting the same for the below code
`import React, { useState,useMemo } from 'react';
import { block } from 'million/react';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';


const generateData = () => {
  const data = [];
  for (let i = 0; i < 100000; i++) {
    data.push({
      id: i + 1,
      name: `Item ${i + 1}`,
      value: Math.random() * 100,
    });
  }
  return data;
};

function App() { 
  const xyz = generateData()
  console.log(xyz);
  const [rowData,setRowData] = useState(xyz)

  const gridOptions = useMemo(() => ({
    defaultColDef: {
      sortable: true,
      filter: true,
    },
    columnDefs: [
      { headerName: 'ID', field: 'id' },
      { headerName: 'Name', field: 'name' },
      { headerName: 'Value', field: 'value' },
    ],
  }), []);

  return (
    <div>
      <h1>React ag-Grid App</h1>
      <div>
        <label>Search: </label>
      </div>
      <div className="ag-theme-alpine" style={{ height: '500px', width: '100%' }}>
        <AgGridReact
          rowData={rowData}
          gridOptions={gridOptions}
        />
      </div>
    </div>
  );
};


const AppBlock = block(App);

export default AppBlock;
`

**Comment by tobySolutions** [comment]
Hmm, hey there @sahajjain1, can you maybe provide a mini-reproduction of this issue? Maybe you can use Stackblitz or Codesandbox. Thanks! 🙌

**Comment by sahajjain1** [comment]
@tobySolutions Thanks for the fast response,
https://codesandbox.io/p/sandbox/sleepy-aj-pj2rft?file=%2Fsrc%2FApp.jsx

**Comment by tobySolutions** [comment]
> @tobySolutions Thanks for the fast response,
> https://codesandbox.io/p/sandbox/sleepy-aj-pj2rft?file=%2Fsrc%2FApp.jsx

Awesome! Thanks, I'll check it out and keep you updated 😁😁

**Comment by tobySolutions** [comment]
> @tobySolutions  i have change the url you can check once Thanks :)
> 

Okay, cool. Of course.

**Comment by sdegueldre** [comment]
Seems like you're just running into https://million.dev/docs/rules#using-the-compiler

**Comment by tobySolutions** [comment]
> Seems like you're just running into https://million.dev/docs/rules#using-the-compiler

Thank you @sdegueldre, any updates @oshrit-marktrix!

**Comment by sahajjain1** [comment]
Thanks @sdegueldre will go through it

**Comment by Criezc** [comment]
> Thanks @sdegueldre will go through it

are you still encountering the issues? if yes, most likely is cause your compiler didn't handle it well. I've just just experienced it. 

On my case, I use `Vite` and I didn't handle `Million` compiling well. Try to use either `Craco` or `Vite`. Good luck!

**Comment by Criezc** [comment]
@sahajjain1 I'm able to reproduce your issues while using `Craco`

try to implement this with `Craco`

```js
const million = require("million/compiler")
module.exports = {
  webpack: {
    plugins: {
      add: [million.webpack()],
    },
  },
};
```

all of your codes work fine with `Million` Block HOC applied :)

**Comment by lxsmnsyc** [comment]
yeah seems like there was no usage of the compiler here. This can probably marked as resolved.

**Comment by Aslemammad** [comment]
I'll close this for now, feel free to re-open!
