### ISSUE TITLE
bug: [Vite] Invalid shorthand property initializer

### ISSUE THREAD

**Issue by composite** [aidenybai/million#450]
**Describe the bug**
The destructed default parameter syntax is not working on wrapped Million's `block` in Vite App.

**To Reproduce**
1. Go to [Reproduced Sandbox](https://codesandbox.io/p/sandbox/million-js-destructed-default-parameter-error-vite-lznps6?file=%2Fsrc%2FSome.tsx%3A1%2C1)
2. See error
3. See `Some.tsx` and destructed default parameter set.

**Expected behavior**
accept default parameter and able to see component content like `Some 1`.

**Device (please complete the following information):**
 - OS Windows
 - Browser Edge 
 - Version  114.0.1823.51

**Additional context**
[I also created same example with `create-react-app` sandbox](https://codesandbox.io/p/sandbox/million-js-destructed-default-parameter-success-webpack-2363hk?file=%2Fsrc%2FSome.tsx%3A1%2C1), it works properly.

**Comment by tobySolutions** [comment]
Can you show a code sample to further explain what this means? @composite

**Comment by composite** [comment]
@tobySolutions

typically destructuring assignment is working normally.

```tsx
const SomeBlock = block(({ a }: { a?: number }) => {
  return <div>Some {a}</div>;
});
```

but destructuring assignment with default value does not work.

```tsx
const SomeBlock = block(({ a = 1 }: { a?: number }) => {
  return <div>Some {a}</div>;
});
```

I installed [`vite-plugin-inspect`](https://github.com/antfu/vite-plugin-inspect) for detailed error description, I saw built source like that transform error raised from `Some.tsx` in my reproduced sandbox:

```js
import { createElement as _createElement$ } from "react";
import { block as _block$ } from "million/react";
import { block } from "million/react";
const _anonymous$2 = ({
  a = 1
}: {
  a?: number;
}) => {
  return _createElement$(_puppet$, {
    a: a,
    __props: {
      a = 1 // <-- ERROR: Unexpected "=" here!
    }
  });
};
const _anonymous$ = ({
  a = 1
}: {
  a?: number;
}) => {
  return <div>Some {a}</div>;
};
_anonymous$2.displayName = "_anonymous$2";
const _puppet$ = _block$(({
  a: a,
  __props: __props
}) => {
  return <div>Some {a}</div>;
}, {
  original: _anonymous$,
  shouldUpdate: (oldProps, newProps) => oldProps?.a !== newProps?.a || oldProps?.__props !== newProps?.__props
});
const SomeBlock = _anonymous$2;
export default SomeBlock;
```

So you can see the error messasge when run `dev` or `build` in my reproduced sandbox:

```
Transform failed with 1 error:
/workspace/src/Some.tsx:12:8: ERROR: Unexpected "="

10 |      a: a,
11 |      __props: {
12 |        a = 1
   |          ^
13 |      }
14 |    });
```

**Comment by aidenybai** [comment]
@composite can you try again in 2.5.0?

**Comment by aidenybai** [comment]
This should be fixed in the latest release.
