### ISSUE TITLE
bug: Module parse failed: Shorthand property assignments are valid only in destructuring patterns

### ISSUE THREAD

**Issue by DiegoCantu** [aidenybai/million#452]
**Describe the bug**
This seems a typescript error when you try to use a interface / type in  a block.

**To Reproduce**
**1. import { For, block } from 'million/react'** ( "million": "^2.4.8-beta.3") 
because if I try to use import { block } from "million/react-server"; 
I receive the next message:
Cannot find module 'million/react-server' or its corresponding type declarations.

**2. Create a type or interface:**
```
type SidebarProps = {
    title: string;
    bannerImage: string;
    sidebarItems: any[];
    type: "flat" | "children"
    userName?: string;
    userImage?: string;
}

```
**3. Use the type in the component:**
Component:
```
const Sidebar: React.FC<SidebarProps> = ({ title, bannerImage, sidebarItems, type = "flat", userName = "", userImage = "" }) => { 
....
};
```

**4. Implement million block:**
```
const BlockComponent = block<SidebarProps>(Sidebar);
export default BlockComponent;
```

**Expected behavior**
The component should be displayed

**Screenshots**
![image](https://github.com/aidenybai/million/assets/8170026/172f6054-4b44-4026-9328-0cfb6cf89edc)

**Device (please complete the following information):**
 - Browser chrome, firefox, etc

**Additional context**
**Error message:**
(137:16)
File was processed with these loaders:
 
./node_modules/next/dist/build/webpack/loaders/next-flight-client-module-loader.js
./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|             bannerImage,
|             sidebarItems,
            type="flat",
|             userName="",
|             userImage=""

**Comment by tobySolutions** [comment]
Hey @DiegoCantu! Can you remove the block and send a reproduction so we can check it out?

**Comment by DiegoCantu** [comment]
https://github.com/aidenybai/million/assets/8170026/336af31f-67c1-48cc-bae9-6a709d52c9a9

**Comment by aidenybai** [comment]
Hold on, does this work without block? @DiegoCantu? Might be a conflict with react refresh

**Comment by tobySolutions** [comment]
> Hold on, does this work without block? @DiegoCantu? Might be a conflict with react refresh

Hmm, the code looks kinda tricky to me too.

**Comment by DiegoCantu** [comment]
This works perfectly fine with no crash, actually this is existing code that I try to add millions to, also after millions is stable for next.js, I'll try to add millions to 60+ react components, which...also already existing and work correctly

**Comment by DiegoCantu** [comment]
I created this repo to reproduce the issue:

https://github.com/DiegoCantu/million-test
https://github.com/DiegoCantu/million-test/blob/master/src/app/components/Sidebar.tsx

**Comment by aidenybai** [comment]
Seems it be an error for typescript parsing. If you remove `block<Type>();`

```js
const BlockComponent = block<SidebarProps>(Sidebar);
```

to:

```
const BlockComponent = block(Sidebar);
```

**Comment by DiegoCantu** [comment]
is the same issue without props in block:

![image](https://github.com/aidenybai/million/assets/8170026/7f096f98-c32d-4690-8eb5-f9ee7b6d3f8b)

**Comment by tobySolutions** [comment]
> is the same issue without props in block:
> 
> ![image](https://github.com/aidenybai/million/assets/8170026/7f096f98-c32d-4690-8eb5-f9ee7b6d3f8b)
> 

Without props? Wait, why? Can you share your code?

**Comment by DiegoCantu** [comment]
without props to test that:

![image](https://github.com/aidenybai/million/assets/8170026/997ea257-afdc-4077-95a6-5acfa41f4ad1)

this is the repo:
https://github.com/DiegoCantu/million-test/blob/master/src/app/components/Sidebar.tsx

**Comment by aidenybai** [comment]
Whoa, now that's weird. Let me get back to you soon

**Comment by tobySolutions** [comment]
Alright, thanks @aidenybai! We'll get back to you soon for sure @DiegoCantu.

**Comment by aidenybai** [comment]
@DiegoCantu can you test with the latest release?

**Comment by DiegoCantu** [comment]
Now this is the new issue, and obviously Sidebar is defined:

error src\app\components\Sidebar.tsx (57:23) @ _Sidebar
- error ReferenceError: _Sidebar is not defined
    at eval (./src/app/components/Sidebar.tsx:190:24)
    at (sc_client)/./src/app/components/Sidebar.tsx (C:\Users\diego\Desktop\RWB\Million\million-test\.next\server\app\page.js:1800:1)
    at __webpack_require__ (C:\Users\diego\Desktop\RWB\Million\million-test\.next\server\webpack-runtime.js:33:42)

![image](https://github.com/aidenybai/million/assets/8170026/174a3abf-1f07-4509-b970-86964294666d)
![image](https://github.com/aidenybai/million/assets/8170026/647fba3b-bda1-4c7a-8cfb-55ac5ab134ba)
