### ISSUE TITLE
feat: Support this functionality for Parcel with typescript?

### ISSUE THREAD

**Issue by DamengRandom** [aidenybai/million#463]
Hi Million team,

This is amazing tool you created, really love it ~~

Currently, my team is using parcel as bundler for bundling purpose, and we also use typescript, and after I have installed the million npm package, I noticed that I got the following errors:

`@parcel/core: Failed to resolve "'million/" react' `

And then, I went to package.json file and disabled alias settings, eg:

```js
alias: {
    "million/react": false
}
```

I have faced another error:

`TypyError: (0, _react.block) is not a function`

Is that possible I can get some help with above error?

Mega thanks in advance ~~

**Comment by tobySolutions** [comment]
Hey @DamengRandom, can you come over to the server and ask this question so we can discuss it to iron things out? [million.dev/chat](million.dev/chat), we'll take a proper look at this issue soon enough so we don't hinder your team's progress.

**Comment by aidenybai** [comment]
@DamengRandom Do you think you could provide a reproduction of this issue?

**Comment by DamengRandom** [comment]
Hi @aidenybai and @tobySolutions, thank you for the reply, and I would say my project use case might be a bit special, we are suing parcel for bundling all the files. I assume during bundling build process, we got this error:

```@parcel/core: Failed to resolve "'million/" react' ```

Or if you have released a new version, I can give it a go and see how it goes and I will update you the result. 

Thank you for help in advance ~~
