### ISSUE TITLE
bug: In some cases, styles do not work well in blocks.

### ISSUE THREAD

**Issue by nojiritakeshi** [aidenybai/million#465]
**Describe the bug**
The following will not work in block.
1. when style is set to a property that contains uppercase letters.
2. When you want to render processed arguments.

Specifically, this is the case when.
```typescript
export const RowBlock = block((adjective: string) => {
  const fuga = adjective + "abc";
  return (
    <tr>
      <td style={{ [adjective]: "red" }}>{fuga}</td>
```

**To Reproduce**
**Expected behavior**
That all will be well.

**Screenshots**
```typescript
// adjective === backgroundColor
export const RowBlock = block(({ adjective, color, noun }: RowProps) => {
  return (
    <tr style={{ backgroundColor: "gray" }}>
      <td style={{ [adjective]: "red" }}>{adjective}</td>
      <td>{color}</td>
      <td>{noun}</td>
    </tr>
  );
});
```
![キャプチャ](https://github.com/aidenybai/million/assets/62943988/90223101-8abd-48d1-afba-3229603aca10)

**Device (please complete the following information):**
 - OS Windows10
 - Browser chrome
 - Version 114.0.5735.199

**Additional context**
I'm currently working on this issue.
I'll do my best to give you a good report.

**Comment by oliverloops** [comment]
Hello @nojiritakeshi 👋, I reproduced your issue. I'm in the same version of Google Chrome but I'm running the sample from macOS Ventura, This proper RowBlock implementation isn't causing any issue, here's an example: 

```
// adjective === backgroundColor
export const RowBlock = block(({ adjective, color, noun }) => {
  return (
    <tr style={{ backgroundColor: "gray" }}>
      <td style={{ [adjective]: color }}>{adjective}</td>
      <td>{color}</td>
      <td>{noun}</td>
    </tr>
  );
});

function RowBlocks() {
  return (
    <table>
      <tbody>
        <RowBlock adjective="backgroundColor" color="blue" noun="cat" />
        <RowBlock adjective="backgroundColor" color="red" noun="dog" />
        <RowBlock adjective="backgroundColor" color="green" noun="mouse" />
      </tbody>
    </table>
  );
}
```

And the results are showing like this:
![Screenshot 2023-07-05 at 2 57 16](https://github.com/aidenybai/million/assets/33361399/cc20a898-6715-4140-966a-5c5a9e070c72)
![Screenshot 2023-07-05 at 2 57 49](https://github.com/aidenybai/million/assets/33361399/c58e370f-117a-4d5a-a19c-be40e1ce369e)

**Comment by oliverloops** [comment]
Are your typed parameters well implemented?, In which environment are you running your implementation?

**Comment by nojiritakeshi** [comment]
@oliverloops 
Oh, really?
I'm also using vite 4.3.9, so does the difference in OS cause problems?

**Comment by nojiritakeshi** [comment]
What version of React are you using?

**Comment by oliverloops** [comment]
Hello again, I'm not sure if the problem is exactly the OS, but there's a possibility. I'm working with React 18.2.0 and Million 2.4.9 check please if both versions of your project are the latests

**Comment by nojiritakeshi** [comment]
@oliverloops Thank you for your response.
hmm.
I'm using the same latest version for both of them.

**Comment by tobySolutions** [comment]
Hey @nojiritakeshi, are you still getting this issue till now? I'm curious to know.

**Comment by nojiritakeshi** [comment]
@tobySolutions 
Thanks for confirming.
I've modified the code to work correctly for the use case I raised! Now I just need to add more test cases.
Just curious about @oliverloops point.

**Comment by nojiritakeshi** [comment]
@tobySolutions 
Once I've written the test cases, I'll create a pull request.

**Comment by aidenybai** [comment]
@nojiritakeshi Okay so–computed are technically "out-of-bounds" because they can introduce non-deterministic properties, but we can support them sort of as long as the value does not change between renders.

Let me push something in the PR and will ping you again on this.
