### ISSUE TITLE
bug: configuring vite.config.ts

### ISSUE THREAD

**Issue by trifkee** [aidenybai/million#467]
**Describe the bug**
on configure ```vite.config.ts```, when adressing plugins, there is error 'Uncaught ReferenceError: require is not defined', all setup instruction are followed by official docs

**To Reproduce**
1. npm i million
2. configure vite.config.ts
3. edit plugins:plugins: [million.vite(), { ...react(), enforce: 'default' }], OR plugins: [million.vite(), react()]
5. Error => Uncaught ReferenceError: require is not defined

**Expected behavior**
Get compiler configured and Million library working

**Screenshots**
![image](https://github.com/aidenybai/million/assets/80207443/7e421ef0-9a8c-463c-b217-791dbea8678f)
![image](https://github.com/aidenybai/million/assets/80207443/4301d16e-7784-499c-a110-c6aab8afe69e)

**Device (please complete the following information):**
Chrome

**Additional context**
/

**Comment by oliverloops** [comment]
Hi @trifkee 👋, I'm checking your issue and this could be related to an error from the module using CommonJS modules instead of ES modules, check if everything on your tsconfig.json is fine. but if the problem persists you can try adding support for CommonJS modules to Vite with the `createCommonjsPlugin(),` just like this: 

```
import { defineConfig } from 'vite';
import { createCommonjsPlugin } from 'vite-plugin-commonjs';

export default defineConfig({
  // other config options
  plugins: [createCommonjsPlugin()],
});
```
Let us know if this works for you or if you found another way to fix it

**Comment by tobySolutions** [comment]
Thank you very much @oliverloops, I really appreciate the response. Would you like me to assign you to this?

Let us know how it goes @trifkee.

**Comment by lucasluca** [comment]
I had the same issue here, and when i add this plugin i get this error

![image](https://github.com/aidenybai/million/assets/16627838/81231784-8316-4c1b-b6bb-9460df4754c9)

**Comment by lucasluca** [comment]
Or if i import million before React on the plugin list i get this:

![image](https://github.com/aidenybai/million/assets/16627838/0eef8d0a-ad7e-45f4-b7b6-a94843198d37)

**Comment by lucasluca** [comment]
I made it work, using this import plugin order:
![image](https://github.com/aidenybai/million/assets/16627838/1d4227da-7152-433b-aae0-6eef8ef0bfb2)

Then i created .babelrc file on the project root

![image](https://github.com/aidenybai/million/assets/16627838/e051b960-85d3-4920-a549-5e2ccfaad33c)

![image](https://github.com/aidenybai/million/assets/16627838/d83a7889-fb0c-4cc3-b4f0-46b9bbb24801)

And also installed this @babel/preset-typescript as a dev dependency... it worked!

**Comment by vctqs1** [comment]
hmm, for my case If Im using vite, The errors appear here, and this line is injected from million plugin
<img width="465" alt="Screenshot 2023-10-27 at 10 44 33" src="https://github.com/aidenybai/million/assets/30227910/48f628b0-8075-4424-92ce-62c4cd2f7c3f">

I also tried to follow instruction to use vite-commonjs-plugin but it produces another error also
<img width="886" alt="image" src="https://github.com/aidenybai/million/assets/30227910/909e60d8-d3be-4150-bf6a-7d39f655a876">

I tried to ignore one by one package appear this error but there is a lot of them
