### ISSUE TITLE
Using million in react gatsby gave error  in build issue but success in development

### ISSUE THREAD

**Issue by aqilusman45** [aidenybai/million#468]
**Describe the bug**
There is an issue that occurs on build time and also in production due to the million js the build is failed continuously where as all the configuration are correct as described in gatsby

Device (please complete the following information):
 - OS [windows 10]
 - Browser [chrome]
 - millionVersion [^2.4.9]
 - react version [^18.2.0]
 - gatsby version [^5.11.0]
 - node version [v19.6.0]
 - npm version [8.19.4]

**Additional context**
In gatsby js the package is installed and imported in gatsby node js as well and all thing works fine in localhost but when i build the site using gatsby it gave me the error 

failed Building static HTML for pages - 5.897s
 ERROR #95313  HTML.COMPILATION
Building static HTML failed for path "/"
See our docs page for more info on this error: https://gatsby.dev/debug-html
WebpackError: See http://million.dev/docs/install to install the compiler.

Screenshots
![image](https://github.com/aidenybai/million/assets/46997126/d648df39-3b8a-43f5-8ce8-6a3bfaf68d89)

when the dev ssr is tru in gatsby the drowser render nothing 
![image](https://github.com/aidenybai/million/assets/46997126/9c8c38b1-0ba3-4dc9-bc10-3ed0961042e4)

and console shows the error

![image](https://github.com/aidenybai/million/assets/46997126/ad6bb0b9-7641-43d6-afff-3312e1afb089)

gatsby node look like 
![image](https://github.com/aidenybai/million/assets/46997126/28b76b03-c799-400d-afed-b01440e7adc2)

the component is look like this
![image](https://github.com/aidenybai/million/assets/46997126/96a9b0af-a1ce-4b4f-8769-5c03a9c6933f)

and the page code look like is this 
![image](https://github.com/aidenybai/million/assets/46997126/a775c560-1398-40a3-a7a9-be5333026886)

when dev ssr is false everything is fine 
![image](https://github.com/aidenybai/million/assets/46997126/5ed64c91-a481-488c-8967-6ce6cbd1230a)

and the console. is clear when devssr is false
![image](https://github.com/aidenybai/million/assets/46997126/d2d53be7-01f8-4ef4-9e77-5701825756bc)

here is the repository url 
[repo url](https://github.com/aqilusman45/million-gatsby.git)

**Comment by tobySolutions** [comment]
Hey @aqilusman45, thank you very much for the detailed issue. We really appreciate this. The team will for sure look into this to get it fixed and set up.

**Comment by aidenybai** [comment]
Can you try with this config instead? @aqilusman45 

```js
const million = require('million/compiler');
 
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    plugins: [million.webpack({ mode: 'react', server: true })],
  })
}
```

**Comment by aqilusman45** [comment]
> Can you try with this config instead? @aqilusman45
> 
> ```js
> const million = require('million/compiler');
>  
> exports.onCreateWebpackConfig = ({ actions }) => {
>   actions.setWebpackConfig({
>     plugins: [million.webpack({ mode: 'react', server: true })],
>   })
> }
> ```

Its the same as shown above nothing different in this there is no change happended still have the issue
