### ISSUE TITLE
bug: Argument of type 'FC<BlockProps>' is not assignable to parameter of type 'ComponentType<MillionProps>

### ISSUE THREAD

**Issue by kul-sudo** [aidenybai/million#470]
**Describe the bug**
```Argument of type 'FC<BlockProps>' is not assignable to parameter of type 'ComponentType<MillionProps>'```
This error appears when using TS with the library.

```tsx
type BlockProps = {
  element: string[];
  index: number;
  setAlertDialogImage: Dispatch<SetStateAction<string>>;
  onOpen: () => void
}

const ColumnBlockComponent: FC<BlockProps> = ({ element, index, setAlertDialogImage, onOpen }) => {
  return (
    <Box
      key={index}
      wordBreak="break-word"
      textAlign="left"
      alignSelf="flex-start"
    >
      <HStack alignItems="top">
        <Text color="gray">{element[2]}</Text>
        <Text color={element[3]}>{element[1]}</Text>
        <Box flex="1" wordBreak="break-word">
          <Text>{element[0]}</Text>
        </Box>
      </HStack>
      {element[4] !== '' && (
        <ChakraImage
          rounded="0.2rem"
          width="80%"
          onClick={() => {
            setAlertDialogImage(element[4])
            onOpen()
          }}
          src={element[4]}
        />
      )}
    </Box>
  )
}

const ColumnBlock = block(ColumnBlockComponent)
```
leads to the error ```Argument of type 'FC<BlockProps>' is not assignable to parameter of type 'ComponentType<MillionProps>'```

As you can see, the documentation has been followed completely, but the error appears nonetheless.

The full error is:
```html
Argument of type 'FC<BlockProps>' is not assignable to parameter of type 'ComponentType<MillionProps>'. ts(2345)
  Type 'FunctionComponent<BlockProps>' is not assignable to type 'FunctionComponent<MillionProps>'.
    Types of property 'propTypes' are incompatible.
      Type 'WeakValidationMap<BlockProps>' is not assignable to type 'WeakValidationMap<MillionProps>'.
        Property 'element' is incompatible with index signature.
          Type 'Validator<string[]>' is not assignable to type 'Validator<string | number | bigint | boolean | symbol | Block>'.
            Type 'string[]' is not assignable to type 'string | number | bigint | boolean | symbol | Block'.
```

**Comment by tobySolutions** [comment]
Hey @kul-sudo, thank you for this. This seems to be a typing issue though, we'll take a look at it to get it sorted. Can you maybe join the Discord server?

**Comment by tobySolutions** [comment]
[https://million.dev/chat](https://million.dev/chat)

**Comment by kul-sudo** [comment]
> Hey @kul-sudo, thank you for this. This seems to be a typing issue though, we'll take a look at it to get it sorted. Can you maybe join the Discord server?

Yeah, I can join, of course.

**Comment by kul-sudo** [comment]
Also, the full error is
```html
Argument of type 'FC<BlockProps>' is not assignable to parameter of type 'ComponentType<MillionProps>'. ts(2345)
  Type 'FunctionComponent<BlockProps>' is not assignable to type 'FunctionComponent<MillionProps>'.
    Types of property 'propTypes' are incompatible.
      Type 'WeakValidationMap<BlockProps>' is not assignable to type 'WeakValidationMap<MillionProps>'.
        Property 'element' is incompatible with index signature.
          Type 'Validator<string[]>' is not assignable to type 'Validator<string | number | bigint | boolean | symbol | Block>'.
            Type 'string[]' is not assignable to type 'string | number | bigint | boolean | symbol | Block'.
```

**Comment by kul-sudo** [comment]
> Hey @kul-sudo, thank you for this. This seems to be a typing issue though, we'll take a look at it to get it sorted. Can you maybe join the Discord server?

Any updates?

**Comment by tobySolutions** [comment]
> > Hey @kul-sudo, thank you for this. This seems to be a typing issue though, we'll take a look at it to get it sorted. Can you maybe join the Discord server?
> 
> Have you got it sorted or decided to ignore this one?

I spoke with the team already, it'll be sorted out soon.

**Comment by destroyer22719** [comment]
Hey there, which version are you using and where are you importing `block` from?

**Comment by kul-sudo** [comment]
> Hey there, which version are you using and where are you importing `block` from?

The absolutely latest version. I import it from `million/react`

**Comment by kul-sudo** [comment]
Closing due to having creating a new more precise issue.
#475

**Comment by kul-sudo** [comment]
Closing due to having creating a new more precise issue.
#475
