### ISSUE TITLE
bug: Broken Link(Reconciling React)

### ISSUE THREAD

**Issue by olaoluwaayanbola** [aidenybai/million#478]
**Describe the bug**
 The link provided in the blog post for 'reconciling-react' is currently broken, leading to a 404 error

**To Reproduce**
1. Go to 'https://million.dev '
2. Click on 'blog'
3. Scroll down to 'reconciling-react) '

**Expected behavior**
The intended outcome should be to redirect you to a webpage that contains the necessary information.

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. iOS]
 - Browser chrome

**Additional context**

**Comment by aidenybai** [comment]
Fixed
