### ISSUE TITLE
bug: Cannot render a block

### ISSUE THREAD

**Issue by vital487** [aidenybai/million#479]
**Describe the bug**
After creating a block it is not rendered.

**To Reproduce**
Check the link [https://codesandbox.io/s/peaceful-varahamihira-nhs8jl?file=/src/App.js](url).

**Expected behavior**
After the issue #412 was solved I tried to add SVG elements and it did not work. Not even to create a block from a `div` (of course not inside the SVG HTML).

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 2.4.9

**Comment by tobySolutions** [comment]
> **Describe the bug** After creating a block it is not rendered.
> 
> **To Reproduce** Check the link [https://codesandbox.io/s/peaceful-varahamihira-nhs8jl?file=/src/App.js](url).
> 
> **Expected behavior** After the issue #412 was solved I tried to add SVG elements and it did not work. Not even to create a block from a `div` (of course not inside the SVG HTML).
> 
> **Device (please complete the following information):**
> 
> * OS: Windows
> * Browser: Chrome
> * Version: 2.4.9

Thank you for raising this @vital487!

**Comment by aidenybai** [comment]
Will be fixed in a release soon.

**Comment by vital487** [comment]
Hi @aidenybai,

Is this fixed? Since the first fix (https://github.com/aidenybai/million/issues/412) I could never make it work.
