### ISSUE TITLE
bug: Macro doc misplaced

### ISSUE THREAD

**Issue by TreciaKS** [aidenybai/million#482]
**Describe the bug**

**To Reproduce**
1. Go to 'Million.dev'
2. Click on '/docs'
3. Scroll down to 'API Reference > below Internals'

**Expected behavior**
To be inside the [internals/macro.mdx] folder

**Screenshots**
<img width="298" alt="Screenshot 2023-07-14 at 14 00 02" src="https://github.com/aidenybai/million/assets/82657928/284ab071-296a-434c-a471-57681022c10e">

**Device (please complete the following information):**
 - OS [e.g. iOS]
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest you can get

**Additional context**

**Comment by aidenybai** [comment]
Fixed
