### ISSUE TITLE
NX monorepo + NextJS + Webpack initialization stuck on component with default export

### ISSUE THREAD

**Issue by Durisvk** [aidenybai/million#494]
I've wrapped your lines of code in the bundled file with the following debugging info:

<img width="940" alt="image" src="https://github.com/aidenybai/million/assets/8467003/36cc1991-a39f-4daa-8c8c-342af73f314b">

I saw that one of our components was stuck on `await core.transformAsync(...)` (the promise never resolved nor rejected).

<img width="642" alt="image" src="https://github.com/aidenybai/million/assets/8467003/ff5c8470-60fd-4d71-aa6d-afc1f1248689">

I then just as a silly attempt tried to change the export from `default` to `const`:

**Before**
```tsx
const ApplicantView = ...

export default ApplicantView;
```

**After**
```tsx
export const Applicant = ...
```

and the promise `await core.transformAsync(...)` got unstuck.

don't have much time to create a minimal reproducible demo but what I do in my `next.config.js` is basically unshift your webpack plugin into my current webpack config:

```js
config.plugins.unshift(
   million.webpack({ mode: 'react', server: options.isServer })
);
```

just like you do in your source code.

not sure if this is a helpful issue report but if someone struggles with the similar issue you can try switching from `default` export to `const` export.

**Comment by aidenybai** [comment]
@Durisvk i dont think this is exclusive to just your setup. will dig into this issue and take a look

**Comment by tobySolutions** [comment]
Awesome, thanks for raising the issue @Durisvk!
