### ISSUE TITLE
Newly created next app with app dir doesn't work with auto: true

### ISSUE THREAD

**Issue by andreifilip123** [aidenybai/million#500]
Hello!
On a newly created nextjs app, adding auto to the next config (as in the docs) breaks the app.

Here's the code sandbox:
https://codesandbox.io/p/github/andreifilip123/million-auto-nextjs

The issue is that the root layout is converted to a client component while being optimized. Maybe that should be skipped ?

**Comment by aidenybai** [comment]
Can you try with `v2.5.3`?

**Comment by andreifilip123** [comment]
I tried that and still doesn't work (both with the latest beta and with // million-ignore

**Comment by aidenybai** [comment]
Fixed in v2.5.4-beta.2. if you are using RSC, make sure to enable rsc as so: `auto: { rsc: true }` @andreifilip123

**Comment by andreifilip123** [comment]
Works now. Congrats and thanks !
