### ISSUE TITLE
bug: Some Mouse events doesnt dispatch

### ISSUE THREAD

**Issue by facu-carri** [aidenybai/million#503]
The events 'onMouseEnter' and 'onMouseLeave' dont dispatch anything.
After note that, i put console.log inside of the funcionts and it doesnt excute
```jsx
const [isMouseOver, setIsMouseOver] = useState(false)
const handleMouseEnter = () => {
    setIsMouseOver(true)
  }

  const handleMouseLeave = () => {
    setIsMouseOver(false)
  }
return <div
    className={`relative w-fit bg-white border-2 border-solid rounded-xl text-center transition duration-200 ${amount > 0 ? 'border-red-500' : 'border-black'}`}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      onContextMenu={handleRightClick}
      onClick={handleClick}
    >
...
```
### Solution
Use onMouseOver and onMouseOut insted of onMouseEnter and onMouseLeave

**Comment by tobySolutions** [comment]
Do you want to work on this issue @facu-carri?

**Comment by facu-carri** [comment]
> Do you want to work on this issue @facu-carri?

Okey, i will do my best :)

**Comment by tobySolutions** [comment]
Any updates @facu-carri? Is it going well?

**Comment by facu-carri** [comment]
I tried to run the build, but this enemy appeared
![imagen](https://github.com/aidenybai/million/assets/43284046/5d82f25b-da43-43a5-8646-a35704d1d29c)

**Comment by tobySolutions** [comment]
Some events actually do work within the block @facu-carri. We tested out a couple of events within the block during the Sunday stream. 

https://www.youtube.com/watch?v=Bs_Ouo-3OvE

Thnk you for the observation.
