### ISSUE TITLE
We must not use block() and <For /> together in the same component?

### ISSUE THREAD

**Issue by do-kevin** [aidenybai/million#504]
Hey there,

I was getting this warning
```
Found unsupported import for block.
```
and I made sure I used `million/react` instead of just `million`. It was complaining on my `main.tsx`, which is pretty much the typical `App.tsx` file.

This warning went away when I either just use million's `<For />` without the `block()`, or I just remove both `block()` and `<For />` from my component and just use map.

What's the correct usage? Am I allowed to use both `block()` and `<For />` in the same component?

**Comment by facu-carri** [comment]
Some examples that works
**Usign 'million/react'**
_next.config.js_
```js
import million from 'million/compiler';

/** @type {import('next').NextConfig} */
const nextConfig = {
    reactStrictMode: true
}

export default million.next(nextConfig, {mute:true})
```
- Using a component (No block)
```jsx
const Button = ({ value }) => {
    return <button>{value}</button>
  }
<For each={products}>
       {(product) => <Button key={product.key} value={product.name}/>}
</For>
```
- Instance in For (No block)
```jsx
<For each={products}>
       {(product) => <button>text</button>}
</For>
```
- Using a block
```jsx
const Button = block(({ value }) => {
       return <div>{value}</div>
})
<For each={products}>
       {(product) => <Button key={product.id} value={product.name}/>}
</For>
```
-Usign Component from other path with Block
_Index.jsx_
```jsx
<For each={products}>
       {(product) => <Product key={product.id} id={product.id} name={product.name}}
</For>
```
_Product.jsx_
```jsx
const Product = block(function ({ id, name }){
  return (
    <div>
      test
    </div>
  )
})

export default Product
```
Hope this helps :)

**Comment by do-kevin** [comment]
> Hope this helps :)

Thank you so much for the concrete examples. So you're confirming

```js
const Product = block((_props) => {
  return (
    <div>
      test
      <For each={tagList}>
           {(tag) => <p>{tag.name}</p>}
      </For>
    </div>
  )
});

export default Product
```

doesn't work or is not compatible with the Rules of Block?

**Comment by tobySolutions** [comment]
Can you maybe provide a link to a repro so I can fiddle with it? @do-kevin

**Comment by do-kevin** [comment]
> Can you maybe provide a link to a repro so I can fiddle with it? @do-kevin

Here was what I had and what caused the warning to show up: https://github.com/do-kevin/system-panda/blob/86f298d888876378fc0921e8d119da4ce93f7727/src/frontend/src/components/CollectionsBlock.tsx

To run the frontend app, just navigate to the frontend folder and `npm run dev`. You don't have to run the backend package, I mocked it. So the fake credentials are `admin@system-panda.com` and `1234`.

I'm also using TanStack Router and MobX, I'm not sure if they could be messing with Million.js. For using Observer pattern, does it make sense to observe Block components or I should only observe on non-Block parent components?

**Comment by Drex72** [comment]
@do-kevin So we'll check the issue out and reproduce it and get back to you
Thanks for sending the Repo Link
