### ISSUE TITLE
Why is it changing the color of my components?

### ISSUE THREAD

**Issue by AlbertoJALJ** [aidenybai/million#505]
![Captura de pantalla 2023-08-03 a la(s) 10 29 45](https://github.com/aidenybai/million/assets/28641316/8e9bf7ee-f714-464b-bcc2-53b898695703)
They were green. The color I've set it up in MUI.

**Comment by tobySolutions** [comment]
Can you give further explanations regarding this? I'm not sure I get it fully.

**Comment by oliverloops** [comment]
Hello @AlbertoJALJ 👋, is possible to se a reproduction of your component?, how are you using it million in this use case?

**Comment by jahirfiquitiva** [comment]
I have a feeling this might be related to `Context` and a child component accessing a `Context` value, like the theme ...

I recently had an issue with a component like the following:

```typescript
const Tabs = () => {
	...
	return <section>
	...
	{Children.map(children, (child, index) => {
          return (
            <div
              role={'tabpanel'}
              id={`tab-${index + 1}-content`}
              aria-labelledby={`tab-${index + 1}`}
              aria-hidden={currentTab !== 0 && currentTab !== index + 1}
              hidden={currentTab !== 0 && currentTab !== index + 1}
            >
              <h2>{tabsNames[index + 1]}</h2>
              {child}
            </TabPanel>
          );
        })}
	</section>
}
```

used like 

```typescript
<ThemeProvider>
<Tabs>
	<div>Tab1 content</div>
	<div>Tab2 content</div>
	<div>Tab3 content</div>
</Tabs>
</ThemeProvider>
```

one of those tabs contents accessed a `Context` value like this:

```
const { isDark } = useTheme();
```

but the value was undefined, as if the content was not a child of the `ThemeProvider`, so I had to re-wrap the `{child}` in a `ThemeContext.Provider` like this:

```typescript
const Tabs = () => {
	const themeData = useTheme();
	...
	return <section>
	...
	{Children.map(children, (child, index) => {
          return (
            <div
              role={'tabpanel'}
              id={`tab-${index + 1}-content`}
              aria-labelledby={`tab-${index + 1}`}
              aria-hidden={currentTab !== 0 && currentTab !== index + 1}
              hidden={currentTab !== 0 && currentTab !== index + 1}
            >
              <h2>{tabsNames[index + 1]}</h2>
              <ThemeContext.Provider value={themeData}>{child}</ThemeContext.Provider>
            </TabPanel>
          );
        })}
	</section>
}
```

I'm not sure if this issue is related or completely different, but hope you give it a look.
Thanks!

**Comment by tobySolutions** [comment]
Does this still occur @AlbertoJALJ?

**Comment by tylerlaprade** [comment]
This still occurs for me.

**Comment by tylerlaprade** [comment]
Further info:

<img width="314" alt="image" src="https://github.com/user-attachments/assets/659b9980-3ed5-4ff4-bb2d-fd23b34dd7d5">
