### ISSUE TITLE
bug: docs page inaccessible from any other page 

### ISSUE THREAD

**Issue by Sid-WC121** [aidenybai/million#506]
when trying to access Docs page from Blog or Foundation page , the page is not loading and remains in the same page. From doc s page it is possible to move to other pages, but not vise versa. However the "get started " button works from home page.

**Comment by oliverloops** [comment]
Hello @Sid-WC121 👋, I'm checking out this problem

**Comment by tobySolutions** [comment]
> Hello @Sid-WC121 👋, I'm checking out this problem

Thank you Oliver.

**Comment by oliverloops** [comment]
I submitted a PR with the solution, just need to wait for the approval in order to merge 👍

**Comment by RANJEETJ06** [comment]
i thing this issue is resolved
if resolved then close the issue

**Comment by tobySolutions** [comment]
Yeah, this has been resolved 😁😁
