### ISSUE TITLE
Spread attributes are not fully supported

### ISSUE THREAD

**Issue by Its-Just-Nans** [aidenybai/million#514]
In react

```js
const Wrapper = ({ ...allPros }) => {
  return (
    <div>
      <p {...allPros}>test</p>
    </div>
  );
};

export default Wrapper;
```
this works

not in million

Here is a demo

https://stackblitz.com/edit/vitejs-vite-m4vdtj

(try removing the `million.auto({auto: true})` in the vite conf)

**Comment by tobySolutions** [comment]
Hmm, let me check this out and inform the team 🤔🤔

**Comment by rishi-raj-jain** [comment]
@aidenybai this is good to go now, correct?
