### ISSUE TITLE
million don't support extended jsx

### ISSUE THREAD

**Issue by Its-Just-Nans** [aidenybai/million#515]
If you are using R3F (threejs with react), r3f extend jsx components namespace :

```js
import * as THREE from 'three'
import { extend, createRoot, events } from '@react-three/fiber'

// Register the THREE namespace as native JSX elements.
// See below for notes on tree-shaking
extend(THREE)
```

https://docs.pmnd.rs/react-three-fiber/tutorials/typescript#extending-threeelements

In this case, if we have a component like this : 

```jsx
const Compo = ()=>{
  return (<line>
        <bufferGeometry />
        <lineBasicMaterial color="blue" />
  </line>);
}
```

The `<line>` element will be detected as svg, and the function `block()` will crash :/

Note that using this https://github.com/pmndrs/react-three-fiber/discussions/1387#discussioncomment-782518 it's working :)

Useful links : 
https://github.com/pmndrs/react-three-fiber/blob/6f62d4f1a84d10032025390e5086a07e4a849909/packages/fiber/src/core/renderer.ts#L85

**Comment by aboueidlautaro** [comment]
Hello, I am also having an error with R3F. My problem is `Error: R3F: Slot is not part of the THREE namespace! Did you forget to extend?` Did something similar happen to you? If so, were you able to fix it? I understand that the problem as such is that THREE does not contain a Slot, which would be the component used internally by million to be able to optimize certain blocks, but when putting said Slot as a `<div>`, R3F crashes since there cannot be `<div>` in `<Canvas>` element .

**Comment by Its-Just-Nans** [comment]
@aboueidlautaro
Hello,
I didn't really understood your problem :/

Can you provide code or a working example ?


Note that to you html components in `<Canvas/>` you can use the `<Html/>` from `@react-three/drei`

https://codesandbox.io/s/zu2wo here is the demo

**Comment by aboueidlautaro** [comment]
Yes, 

This is Canvas component
```html
<Canvas>
    <SplineLogo>
        <Perspective />
        <Orthographic />
        <Hemisphere />
    </SplineLogo>
    <OrbitControls enablePan={false} autoRotate={true} />
</Canvas>
```
and this SplineLogo

```html
<>
      <group {...props} dispose={null}>
        <scene name='Scene'>
          <group
            name='center_black_box'
            position={[176.66, 48.92, -65.07]}
            scale={[1, 0.89, 1]}>
            <FirstShapes nodes={nodes} materials={materials} />
          </group>
          <group name='back_white_logo' position={[-163.26, 75.72, -24.93]}>
            <SecondShapes nodes={nodes} materials={materials} />
          </group>
          <group name='front_white_logo' position={[-163.26, 75.72, 16.65]}>
            <ThirdShapes nodes={nodes} materials={materials} />
          </group>
          {props.children}
        </scene>
      </group>
</>
```
The 'FirstShape, SecondShape, ...' are basically the <mesh/> separated for better readability, but there's nothing weird behind it.

**Comment by Its-Just-Nans** [comment]
Thanks, I think it's not the same problem as extended jsx but [here](https://github.com/aidenybai/million/blob/898842d60eb961b7b48377193d295533dd26d6b8/packages/compiler/react/transform.ts#L118 ) we can read `This is because the runtime API does not currently handle fragments. We will deal with nested fragments later.` so maybe it's more related to fragment usage

What if you try to remove the fragments `<>...</>` and just just the `<group>...</group>` as a parent ?

Related to #531

**Comment by tobySolutions** [comment]
Can you please provide a reproduction?
