### ISSUE TITLE
auto million svg crash

### ISSUE THREAD

**Issue by Its-Just-Nans** [aidenybai/million#516]
SVG bug when using auto million

```txt
Uncaught TypeError: Cannot read properties of null (reading 'firstChild')
    at stringToDOM (million_react.js?v=92615a69:756:14)
    at block (million_react.js?v=92615a69:541:16)
    at block2 (million_react.js?v=92615a69:867:24)
    at Wrapper.jsx:7:39
```

Demo
https://stackblitz.com/edit/vitejs-vite-m4vdtj

(try removing the `million.vite({auto:true})` in the vite conf, it will work)

**Comment by brotzky** [comment]
Same error in Next for me following the installation in [docs](https://million.dev/docs/install#use-the-compiler)

Also, when first installing I ran into
```
 error unhandledRejection: Error: Cannot find package '@babel/plugin-syntax-typescript' imported from /path/to/babel-virtual-resolve-base.js
 ```
 had to manually add it to my `package.json`. Maybe it's a clue to help resolve this.

**Comment by pra2a** [comment]
@brotzky did you add @babel/plugin-syntax-typescript or something else? i have the same issue with nextjs but didn't work for me

**Comment by Cafezinho** [comment]
+1 for all above

**Comment by panquequelol** [comment]
importing an SVG to my component throws `dom is null` in million v2.5.13 :(

**Comment by aidenybai** [comment]
@panquequelol @brotzky @Cafezinho @pra2a @Its-Just-Nans Can you try on `v2.6.0-beta.11` and see if it is fixed?

**Comment by Its-Just-Nans** [comment]
I think it's now working

Demo with `2.6.0-beta.11`  https://stackblitz.com/edit/vitejs-vite-tfqkxn
