### ISSUE TITLE
React.createElement throws error when component is retrieved directly from object

### ISSUE THREAD

**Issue by Barsnes** [aidenybai/million#517]
When you are trying to load components from an object inside of the JSX, and displaying it using `createElement`, it will throw an error unless you use a function to return it.

We have this object of components:
```js
const Components: {
	[key: string]: React.LazyExoticComponent<React.FC<any>>
} = {
    "Button": lazy(() => import('./components/Button'))
}
```

Inside of our JSX we do this to display the components, based on what you want to show:
```js
<Suspense>
    {componentNames.map((block, index) => {
        if (typeof Components[block] !== 'undefined') {
            /* This line throws an error */
            return React.createElement(Components[block], {
                block: block,
                key: 'component-' + index,
            })
        }
        return null
    })}
</Suspense>
```

It throws this error:
```
React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

But if we do this, it works:
```js
<Suspense>
    {componentNames.map((block, index) => {
        if (typeof Components[block] !== 'undefined') {
            return React.createElement(getComponent(block), {
                block: block,
                key: 'component-' + index,
            })
        }
        return null
    })}
</Suspense>

...

function getComponent(block: string) {
    return Components[block]
}
```

**Comment by aidenybai** [comment]
What does getComponent(block) return in this case? wondering if you can log the output and send it over

**Comment by Barsnes** [comment]
> What does getComponent(block) return in this case? wondering if you can log the output and send it over

It returns a functional component from the `Components` object, if the key exists, otherwise it's null. The log output is kinda large, but you get the same thing if you log any functional component.

**Comment by TechWizard9999** [comment]
@Barsnes I am intrested in it 
Please asssign me this

**Comment by Barsnes** [comment]
> @Barsnes I am intrested in it Please asssign me this

Hey! You can create a PR and mention this issue in the description like this: `resolves #517`

**Comment by TechWizard9999** [comment]
@Barsnes  For all issues can we do that or only this

**Comment by Barsnes** [comment]
> @Barsnes For all issues can we do that or only this

You can do it for any issue :)
