### ISSUE TITLE
Issues in basic undestanding

### ISSUE THREAD

**Issue by Cafezinho** [aidenybai/million#521]
Due to issue #516, I wasn't able to use automatic mode in my project. So I started manually inserting blocks in the files that were previously automatically optimized.

I am facing several issues and I think it might be related to my lack of understanding of some premisses.

Can someone help me out?

I can't have any custom components from other libs in my blocks? Can I pass them as parameters to blocks? I tried using a FontAwesome component and it resulted in the issue related to #516, but when I included the svg, it worked. 

Another issue is with Non-deterministic; Do I need to have only one return statement, but can I return a variable that could be set with two different values?

Finally, Does state work normally inside blocks? Had some issues with state not changing accordingly.

Had issues where I received the following error message: "block.mjs:102  Uncaught TypeError: Illegal invocation".  

Thanks and awesome work

Example: I tried replacing a map with For and changing the jsx inside the loop for a block. Can't figure out why this is not working.

`
```
import { For, block } from 'million/react';
import { ReactNode } from 'react';
import { useTranslation } from 'react-i18next';

const FaExclamationSVG = block(() => (
  <svg
    stroke='currentColor'
    fill='currentColor'
    stroke-width='0'
    viewBox='0 0 192 512'
    className='h-4 w-4 fill-white'
    height='1em'
    width='1em'
    xmlns='http://www.w3.org/2000/svg'
  >
    <path d='M176 432c0 44.112-35.888 80-80 80s-80-35.888-80-80 35.888-80 80-80 80 35.888 80 80zM25.26 25.199l13.6 272C39.499 309.972 50.041 320 62.83 320h66.34c12.789 0 23.331-10.028 23.97-22.801l13.6-272C167.425 11.49 156.496 0 142.77 0H49.23C35.504 0 24.575 11.49 25.26 25.199z'></path>
  </svg>
));

const FaCheckSVG = block(() => (
  <svg
    className='h-4 w-4 fill-white'
    xmlns='http://www.w3.org/2000/svg'
    viewBox='0 0 512 512'
  >
    <path d='M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z' />
  </svg>
));

interface SectionsMenuProps {
  formProgress: Record<string, boolean | null>;
  sections: string[];
  expandSection: (sectionToExpand: string) => void;
  isAlreadyExpanded: (section: string) => boolean;
}

const SectionItemBlock = block(
  ({
    value,
    text,
    className,
    onClick,
  }: {
    value: ReactNode;
    text: string;
    className: string;
    onClick: () => void;
  }) => {
    return (
      <li className='relative flex items-center justify-end gap-3 py-2 text-end text-md font-bold leading-4'>
        <span>{text}</span>

        <button onClick={onClick} className={className}>
          {value}
        </button>
      </li>
    );
  }
);

export const SectionsMenu = ({
  sections,
  formProgress,
  expandSection,
  isAlreadyExpanded,
}: SectionsMenuProps) => {
  const { t } = useTranslation();

  const focusOnSection = (
    section: string,
    isAlreadyExpanded: (section: string) => boolean,
    expandSection: (sectionToExpand: string) => void
  ) => {
    console.log(2);
    if (!isAlreadyExpanded(section)) {
      expandSection(section);
    }

    document.getElementById(section)?.scrollIntoView({ behavior: 'smooth' });
  };

  const getButtonContent = (index: number) => {
    let buttonContent: { className: string; content: ReactNode };
    if (formProgress === null) {
      buttonContent = {
        className:
          'rounded-full border-2 border-lightBlue bg-white px-2 py-1 font-bold text-lightBlue transition-all ease-in-out hover:bg-lightBlue hover:text-white',
        content: index + 1,
      };
    } else if (formProgress) {
      buttonContent = {
        className:
          'rounded-full border-2 border-green-650 bg-green-650 px-1 py-1 ease-in-out',
        content: <FaCheckSVG />,
      };
    } else {
      buttonContent = {
        className:
          'rounded-full border-2 border-warning bg-warning px-1 py-1 ease-in-out',
        content: <FaExclamationSVG />,
      };
    }
    return buttonContent;
  };

  return (
    <div className='sticky top-2 w-full min-w-[215px] max-w-sm rounded-xl bg-white px-4 py-5 shadow-md'>
      <div className='absolute bottom-7 right-[28.8px] top-7  w-[1.5px] bg-gray-500' />
      <ul className='flex flex-col gap-4'>
        <For each={sections}>
          {(section, index) => {
            const buttonContent = getButtonContent(index);
            return (
              <SectionItemBlock
                key={section}
                text={t(section)}
                value={buttonContent.content}
                className={buttonContent.className}
                onClick={() => focusOnSection(section)}
              />
            );
          }}
        </For>
      </ul>
    </div>
  );
};
```
`

**Comment by Cafezinho** [comment]
For second example: I tried removing the For and using only a block inside map.

`import { block } from 'million/react';
import { ReactNode } from 'react';
import { useTranslation } from 'react-i18next';
import { FaCheck, FaExclamation } from 'react-icons/fa';

interface SectionsMenuProps {
  formProgress: Record<string, boolean | null>;
  sections: string[];
  expandSection: (sectionToExpand: string) => void;
  isAlreadyExpanded: (section: string) => boolean;
}

const SectionItemBlock = block(
  ({
    value,
    text,
    className,
    onClick,
  }: {
    value: ReactNode;
    text: string;
    className: string;
    onClick: () => void;
  }) => {
    return (
      <li className='relative flex items-center justify-end gap-3 py-2 text-end text-md font-bold leading-4'>
        <span>{text}</span>

        <button onClick={onClick} className={className}>
          {value}
        </button>
      </li>
    );
  }
);

export const SectionsMenu = ({
  sections,
  formProgress,
  expandSection,
  isAlreadyExpanded,
}: SectionsMenuProps) => {
  const { t } = useTranslation();

  const focusOnSection = (section: string) => {
    if (!isAlreadyExpanded(section)) {
      expandSection(section);
    }

    document.getElementById(section)?.scrollIntoView({ behavior: 'smooth' });
  };

  const getButtonContent = (index: number, progress: boolean | null) => {
    let buttonContent: { className: string; content: ReactNode };
    if (progress === null) {
      buttonContent = {
        className:
          'rounded-full border-2 border-lightBlue bg-white px-2 py-1 font-bold text-lightBlue transition-all ease-in-out hover:bg-lightBlue hover:text-white',
        content: index + 1,
      };
    } else if (progress) {
      buttonContent = {
        className:
          'rounded-full border-2 border-green-650 bg-green-650 px-1 py-1 ease-in-out',
        content: <FaCheck className='h-4 w-4 fill-white' />,
      };
    } else {
      buttonContent = {
        className:
          'rounded-full border-2 border-warning bg-warning px-1 py-1 ease-in-out',
        content: <FaExclamation className='h-4 w-4 fill-white' />,
      };
    }
    return buttonContent;
  };

  return (
    <div className='sticky top-2 w-full min-w-[215px] max-w-sm rounded-xl bg-white px-4 py-5 shadow-md'>
      <div className='absolute bottom-7 right-[28.8px] top-7  w-[1.5px] bg-gray-500' />
      <ul className='flex flex-col gap-4'>
        {sections.map((section, index) => {
          const buttonContent = getButtonContent(index, formProgress[section]);
          return (
            <SectionItemBlock
              key={section}
              text={t(section)}
              value={buttonContent.content}
              className={buttonContent.className}
              onClick={() => focusOnSection(section)}
            />
          );
        })}
      </ul>
    </div>
  );
};
`

As a result, it is bringing me the className for the second if block inside getButtonContent but content is showing index....
I am lost.

![image](https://github.com/aidenybai/million/assets/16946896/311a6286-d4a2-40af-ad03-c7306fd3d019)

should be 
![image](https://github.com/aidenybai/million/assets/16946896/8d6fe729-e416-4903-b21e-09437529f44b)

**Comment by tobySolutions** [comment]
Hmm, thank you very much for this. We'll definitely try to review this issue and get back to you. :thinking:

**Comment by Drex72** [comment]
@Cafezinho , could you please update to the latest million version and see if the issues have been resolved

**Comment by tobySolutions** [comment]
Thanks for your kind words @Cafezinho; has this issue been resolved for you?

**Comment by Cafezinho** [comment]
Will try it out in the next few days and give you a feedback. Thanks for the help

**Comment by rushi-visilean** [comment]
I ran into a similar issue, can you re-open this? @tobySolutions

**Comment by tobySolutions** [comment]
> I ran into a similar issue, can you re-open this? @tobySolutions 

Can I see what you ran into?

**Comment by rushi-visilean** [comment]
Sure, @tobySolutions.

I tried adding a block into my routing component as shown in Kitchen-Sink by @aidenybai. 

import { Routes, Route, Navigate } from 'react-router-dom';
import { Test } from '../Test';
import { TaktPage } from 'pages/TaktPage';
import { BimLayout } from 'pages/BimLayout';
import { CreateSchedulerPage } from 'pages/CreateSchedulerPage';
import { block } from 'million/react';

import { AppGlobalLayout } from 'pages/AppLayout';

import {AllRoute} from 'pages/AllRoutes';
...
...
..

export const AppRouter = block(() => {
	// export const AppRouter = () => {
	// const { t } = useTranslation();
	return (
		<>
			<Routes>
				<Route path="/" element={<Navigate to="/app/takt-view" replace />} />
				<Route path="/login" element={<h1>This is login page</h1>} />
				<Route path="/style-guide" element={<StyleGuilde />} />
				<Route path="/ui/Visilean/autodeskRedirect" element={<AutodeskRedirect />} />
				<Route path="/app" element={<AppGlobalLayout />}>
					<Route index path="takt-view/create/:projectId" element={<CreateSchedulerPage />} />
					<Route path="takt-view/:projectId" element={<TaktPage />} />
					<Route path="/app/bim-view/:projectId" element={<BimLayout />}>
						<Route index element={<BimLayout />} />
						<Route path=":embedReportId" element={<BimLayout />} />
					</Route>
					<Route path=":projectId/templates" element={<TemplatePage />} />
					<Route path=":projectId/reports/" element={<ReportPage />}>
						<Route index element={<ReportList />} />
						<Route path=":embedReportId" element={<ReportDetail />} />
					</Route>
					<Route path=":projectId/setting" element={<SettingPage />}></Route>
					<Route path=":projectId/profile" element={<ProfilePage />}></Route>
					<Route path=":projectId/constraint" element={<ConstraintPage />}></Route>
					<Route path="/app/scheduler-view/:projectId" element={<SchedulerPage />}></Route>
					<Route path="/app/table-view/:projectId" element={<TablePage />}></Route>
				</Route>

				<Route path="*" element={<h3>{'page_not_found'}</h3>} />
				<Route path="test" element={<Test />} />
				<Route path="/buttons" element={<ButtonStyle />} />
				<Route path="/checkbox" element={<CheckboxStyle />} />
				<Route path="/radio" element={<RadioStyle />} />
				<Route path="/chips" element={<ChipStyle />} />
				<Route path="/status" element={<StatusButtonStyle />} />
			</Routes>
		</>
	);
});

But here I encountered two errors:
 index.tsx:29 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

react.development.js:1618 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (react.development.js:1618:1)
    at useInRouterContext (hooks.tsx:90:1)
    at useRoutesImpl (hooks.tsx:352:1)
    at useRoutes (hooks.tsx:343:1)
    at Routes (components.tsx:468:1)
    at unwrap (million.4d88fdd9.mjs:74:1)
    at million.4d88fdd9.mjs:87:1
    at Array.map (<anonymous>)
    at unwrap (million.4d88fdd9.mjs:87:1)
    at block (million.52d69b41.mjs:632:1)
    
//    craco.config.cjs
const million = require('million/compiler');
module.exports = {
  webpack: {
    plugins: { add: [million.webpack({ auto: true })] }
  }
};

I am using create-react-app and the version of million is 2.6.4.

**Comment by rushi-visilean** [comment]
@tobySolutions & @aidenybai my app is up and running with Million. The steps I followed were:
Step 1 Install Craco:
  npm i -D @craco/craco
Step 2 Update the existing calls to react-scripts in the scripts section of your package.json to use the craco CLI:
  "start": "craco start"
  
  After performing these steps my app got integrated with Million js.

**Comment by tobySolutions** [comment]
Thank you folks! I'll be closing this now.
