### ISSUE TITLE
deprecated dependencies in babel-plugin-transform-react-createelement-to-jsx 1.1.0

### ISSUE THREAD

**Issue by pnodet** [aidenybai/million#524]
Hi! Thanks for the work 💖

I noticed on installing using `pnpm@8.6.5` that `million@2.5.11` depends on [babel-plugin-transform-react-createelement-to-jsx](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx) which hasn't been updated in a long time and is using deprecated dependencies.

<img width="1136" alt="Screenshot 2023-08-12 at 17 08 50" src="https://github.com/aidenybai/million/assets/5941125/d634dcf8-da3a-40dc-a505-fdc4e8a928fc">

Apart for the annoying warning, it uses a very old version of core-js that could maybe lead to better perfs.

 <img width="1191" alt="Screenshot 2023-08-12 at 17 07 05" src="https://github.com/aidenybai/million/assets/5941125/c9528e4f-710e-4426-9e0a-4b62f4661fcf">

**Comment by Shubhamtribhuvan8** [comment]
hey @pnodet  Could this issue be assigned to me, please? I'm excited to work on resolving these dependency concerns and enhancing performance. Thank you! 🙌

**Comment by pnodet** [comment]
Hi @Shubhamtribhuvan8 

I am not involved In the project and not responsible for assigning this. Sorry 🤷‍♂️
You should wait for someone to do the triage.

**Comment by aidenybai** [comment]
We should probably create our own transformer here

**Comment by ashutosh887** [comment]
@aidenybai 
let me work on this issue 
/attempt
/assign

**Comment by aidenybai** [comment]
Fixed
