### ISSUE TITLE
background screen flashes on reload

### ISSUE THREAD

**Issue by sshkeda** [aidenybai/million#529]
### What version of `million` are you using?

2.5.13

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

When I open or reload the official million site there is a quick flash of a white background before switching to the dark mode background.

### What's the expected result?

I don't expect to see a white background flash before the page switches to a dark background whenever I open the site or reload the page.

### Link to Minimal Reproducible Example

https://million.dev/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by sshkeda** [comment]
Created a PR for this issue

https://github.com/aidenybai/million/pull/497

**Comment by sshkeda** [comment]
Created a PR for this issue

https://github.com/aidenybai/million/pull/530

**Comment by tobySolutions** [comment]
Fixed by #530
