### ISSUE TITLE
Problems with <slot> tag in threejs.

### ISSUE THREAD

**Issue by aboueidlautaro** [aidenybai/million#531]
Hello, nice to meet you.
I am working with the R3F library to use threejs in React, when using million my component crashes because the `<slot>` tag is not included within the THREE namespaces, so in the `<Canvas>` component that renders my 3D object it happens an error because it does not find that `<slot>` tag within its declarations. The problem is that I can't expand THREE namespaces with slot because I don't know what that extension should include.

Could you help me? Thank you!

Error explained:

`Error: R3F: Slot is not part of the THREE namespace! Did you forget to extend?`
`The above error occurred in the <ForwardRef(Canvas)> component:`
`The above error occurred in the <slot> component:`

**Comment by tobySolutions** [comment]
Hmm, thank you for this @aboueidlautaro. We'll have the team review it so we can get a move on to get it looked at.

**Comment by verekia** [comment]
React Three Fiber users are probably going to be quite interested in Million.js performance improvements in general. I think it would be worth mentioning in the FAQ if Million.js works with R3F or if there are plans to support it.

**Comment by aboueidlautaro** [comment]
I honestly just wish I could remove R3F from Millionjs optimization in “auto: true” mode.

**Comment by rishi-raj-jain** [comment]
Blocking because of #567

**Comment by Drex72** [comment]
> I honestly just wish I could remove R3F from Millionjs optimization in “auto: true” mode.

@aidenybai , do you think there's a way that we can set it up in the auto mode that you can exclude certain components from being optimized by million

**Comment by Drex72** [comment]
> I honestly just wish I could remove R3F from Millionjs optimization in “auto: true” mode.

I dont think the million auto mode optimizes libraries
there's an existing issue with slots, which is curerntly underway, once it is resolved, i believe it should also resolve your issue
just join the discord so you'd know we make an update
