### ISSUE TITLE
[$35] Support React 16 + 17

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#534]
### Describe the feature

Currently Million.js supports React 18. It would be nice to support React 16/17 builds. 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by rishi-raj-jain** [comment]
@aidenybai 

this'd just involve supporting it in https://github.com/aidenybai/million/tree/main/packages/react, right?

**Comment by aidenybai** [comment]
Yes

**Comment by rishi-raj-jain** [comment]
Thanks, on it!

**Comment by rishi-raj-jain** [comment]
How do I validate if my fixes are correct?

**Comment by aidenybai** [comment]
@rishi-raj-jain create a new vite project. use react 17 + react-dom 17. check if it works. then try with react 18. if it works on both, you can claim the issue

**Comment by rishi-raj-jain** [comment]
@aidenybai 

On it, thanks for the direction!

**Comment by rishi-raj-jain** [comment]
[vite-million-18.zip](https://github.com/aidenybai/million/files/12365421/vite-million-18.zip)

Works fine with v18, breaks with v16 and v17 for react-dom errors.

**Comment by rishi-raj-jain** [comment]
Ohkay, the only problem is of react-dom/client and shall be using react-dom in react < 18. Working on that.

**Comment by shubhamsingh259** [comment]
I have started working on that issues. I have steuped vite with react 18 and is also supported in react 16/17.  Kindly make sure Is it right? then I can share zip file on that

**Comment by shubhamsingh259** [comment]
@aidenybai Please guide me Am i right?

**Comment by shubhamsingh259** [comment]
ok thanks

**Comment by shubhamsingh259** [comment]
I have created vite with react18 project. I have also intsalled million.js in vite+react project.
[https://github.com/shubhamsingh259/react-18.git]

**Comment by shubhamsingh259** [comment]
Please check this repository and kindly guide me. Am I right?.

**Comment by shubhamsingh259** [comment]
Congratulations!

**Comment by joeyfigaro** [comment]
~What version was this released in? [2.6.0-beta.0](https://github.com/aidenybai/million/releases/tag/v2.6.0-beta.0) is not a valid tag on npm it looks like. Neither is `2.6.0`.~

~Disregard–looks like I'm looking for `@million/lint`~

~Still not sure which version I should use for React v17 quite yet.~

For anyone else stumbling here–see [https://github.com/aidenybai/million/issues/1070#issuecomment-2386990975](https://github.com/aidenybai/million/issues/1070#issuecomment-2386990975)
