### ISSUE TITLE
[$69] Integrate Million.js automatic mode into cal.com

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#535]
### Describe the feature

Get auto mode working in https://github.com/calcom/cal.com

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by PeerRich** [comment]
69 -- nice

**Comment by yashug** [comment]
@aidenybai i was able to run it for cal.com. how can we validate further ?

![Screenshot 2023-08-17 at 10 16 33 AM](https://github.com/aidenybai/million/assets/14201280/2570d74d-4888-4d1c-af3a-47dd5ace3f24)

**Comment by ashutosh887** [comment]
@aidenybai Let me try this issue
/attempt
/assign

**Comment by rishi-raj-jain** [comment]
@yashug 

You'd wanna do a build of the repo?

**Comment by rishi-raj-jain** [comment]
As @yashug has aborted the attempt, I'd love to get to this.

@aidenybai How do you consider this resolved? A PR to cal.com github repo, or attaching a zip here?

**Comment by tobySolutions** [comment]
> As @yashug has aborted the attempt, I'd love to get to this. /attempt #535
> 
> @aidenybai How do you consider this resolved? A PR to cal.com github repo, or attaching a zip here?
> 
> <details id="algora-options">
>   <summary>Options</summary>
>   <ul>
>     <li>
>       <a href="https://console.algora.io/api/bounties/clle8rbcv0002mm0fg2veb1r7/cancel-attempt">
>         Cancel my attempt
>       </a>
>     </li>
>   </ul>
> </details>
> 

A PR to Cal.com would suffice. 😁😁😁😁

**Comment by rishi-raj-jain** [comment]
So if cal guy merges it, then only it's considered resolved?

**Comment by rishi-raj-jain** [comment]
@PeerRich Are you guys open to it? Just wanna confirm before putting in the effort.

**Comment by rishi-raj-jain** [comment]
@PeerRich Are you guys open to it? Just wanna confirm before putting in the effort.

**Comment by rishi-raj-jain** [comment]
Tagging @zomars from calcom regarding the same.

**Comment by rishi-raj-jain** [comment]
Tagging @zomars, @PeerRich, @hariombalhara from calcom regarding the same.

**Comment by aidenybai** [comment]
Yes, if cal merges, then we will give the bounty @rishi-raj-jain

**Comment by ashutosh887** [comment]
> Yes, if cal merges, then we will give the bounty @rishi-raj-jain

Even I'd commented @aidenybai

**Comment by rishi-raj-jain** [comment]
Tagging @zomars, @PeerRich, @hariombalhara from calcom regarding the same.

**Comment by rishi-raj-jain** [comment]
Tagging @zomars, @PeerRich, @hariombalhara from calcom regarding the same.

**Comment by rishi-raj-jain** [comment]
@PeerRich Are you guys open to it? Just wanna confirm before putting in the effort.

**Comment by Ashu999** [comment]
hi @aidenybai, I have integrated million.js into cal.com. But some of the E2E test are [failing](https://github.com/calcom/cal.com/actions/runs/6084177244/job/16505683181?pr=11150).

what do you suggest would be right way to deal with this?
can it be resolved by adding `// million-ignore` to [ignore](https://million.dev/docs/install#ignoring-components) the components involved in those E2E tests?

**Comment by Drex72** [comment]
@tobySolutions this issue should be closed since cal.com has already merged the pr

**Comment by kunal00000** [comment]
Hi @PeerRich shall I make a PR for this?

**Comment by tobySolutions** [comment]
The PR for this was never merged @aidenybai. I'll take it that this issue stays open

**Comment by syedbarimanjan** [comment]
@aidenybai @PeerRich  is this still open should I work on it.
