### ISSUE TITLE
Optimize Components wrapped in React.memo in automatic mode.

### ISSUE THREAD

**Issue by michael1997** [aidenybai/million#539]
### Describe the feature

Many of my react components are wrapped in React.memo for performance reasons. I'd like automatic mode to be able to optimize these components.

In automatic mode million doesn't seem to detect or optimize the following component format (based on it not appearing in vite logs)
`const MyComponent = React.memo(function MyComponent(){})`

If the component is of the form below it appears in the vite logs as optimized. 
`function MyComponent() {}`

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hmm, what do you mean? Could you be more specific? 🤔🤔. Why do you want that?

**Comment by Drex72** [comment]
@michael1997 
Is this issue still a valid issue
and i want to ask, why do you want million to optimize your memoized components?
Are you looking forward to optimizing an optimization ??

**Comment by michael1997** [comment]
@Drex72 I was looking for a way to trial million.js quickly with some of our components for plotting and data tables where I thought I could see the biggest benefits as they are very dom heavy with large amount of data changes. 

We're using React.memo currently for these to mostly not rerun on props staying the same when the parent rerenders. 

Not necessarily looking for an optimization on an optimization as blocks already perform a similar function but would have thought many others are already using memo on performance critical components. I was hoping that automatic mode could handle part of deciding if a memo or a block is better. Or if performance is better with both then its an easy drop in to accelerate adoption.

**Comment by Drex72** [comment]
> @Drex72 I was looking for a way to trial million.js quickly with some of our components for plotting and data tables where I thought I could see the biggest benefits as they are very dom heavy with large amount of data changes.
> 
> We're using React.memo currently for these to mostly not rerun on props staying the same when the parent rerenders.
> 
> Not necessarily looking for an optimization on an optimization as blocks already perform a similar function but would have thought many others are already using memo on performance critical components. I was hoping that automatic mode could handle part of deciding if a memo or a block is better. Or if performance is better with both then its an easy drop in to accelerate adoption.

Ohhh, in a way, i understand you
So basically, right now you're using react.memo to optimize components
but you want million auto mode to decide whether to use block or to use react.memo underneath the hood.

If that's the case, i dont think the million compiler does that but what you can try is removing react memoo from those components and allowing million to do the optimization of the components and you can do a performance test and see which one works better for you

**Comment by tobySolutions** [comment]
Thanks @Drex72, @michael1997!
