### ISSUE TITLE
NextJs RSC data disapears when using million

### ISSUE THREAD

**Issue by m10rten** [aidenybai/million#540]
### What version of `million` are you using?

2.5.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

PNPM

### What operating system are you using?

Win

### What browser are you using?

Chrome

### Describe the Bug

With NextJS and an array of components, the data showed as: `$: 'data'`
data was the array with stuff in it, now it turns into a string.

nextjs throws and the data is not in my RSC client component.

Uppon removing million from the next.config.mjs, everything worked (yes i tried restarting the server before that)

### What's the expected result?

to give me the data in the client component.

### Link to Minimal Reproducible Example

no link, local.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
Can you give a reproduction? Ideally in a stackblitz or GitHub repo so we can triage and fix the issue

**Comment by tobySolutions** [comment]
Any updates @m10rten?

**Comment by m10rten** [comment]
> Any updates @m10rten?

Went on using without million, maybe in the near future I will retry it.

**Comment by rishi-raj-jain** [comment]
I think we shall close this issue as it doesn't provide the minimal reproduction.

**Comment by Drex72** [comment]
@tobySolutions  Please close this issue until there is a minimal reproduction available

**Comment by tobySolutions** [comment]
Closing this for now. Thanks @rishi-raj-jain, @Drex72, @SukkaW
