### ISSUE TITLE
Types have Masquerading as CJS problem because no `types.d.mts` files generated

### ISSUE THREAD

**Issue by AbhiPrasad** [aidenybai/million#541]
### What version of `million` are you using?

2.5.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

-

### What browser are you using?

-

### Describe the Bug

When checking the types for million via https://arethetypeswrong.github.io/?p=million%402.5.13 [Masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) is raised as a problem.

<img width="1490" alt="image" src="https://github.com/aidenybai/million/assets/18689448/4808ab35-1936-4a11-965a-6bb8c4b1a5e9">

<img width="331" alt="image" src="https://github.com/aidenybai/million/assets/18689448/70de73cc-c5bc-4321-ba00-0d5884d48d62">

### What's the expected result?

Fix the types.

We probably need to generate `types.d.mts` and use it. Seems like this is supported in [unbuild `v2.0.0-rc.0`](https://github.com/unjs/unbuild/releases/tag/v2.0.0-rc.0).

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AbhiPrasad** [comment]
This is a good first issue if anyone is interested - I don't have the perms to add labels.

**Comment by itsajay1029** [comment]
I'd like to work on this @aidenybai. Can you guide me on how to resolve the issue a little ?

**Comment by pnodet** [comment]
@itsajay1029 You should try setting the version of `unbuild` in package.json to `2.0.0-rc.0`
It will likely print errors since the version set is `0.7.6`

**Comment by itsajay1029** [comment]
@pnodet Can you review the PR ?

**Comment by pnodet** [comment]
What was I thinking...

@itsajay1029 First of all, I'm nor a contributor nor do I have the authority to review the PR.

I was simply offering advice when I came across this issue. Once you have installed the new version you need to run the build command and actually fix the errors. Not just upgrade the dependencies.

**Comment by itsajay1029** [comment]
![image](https://github.com/aidenybai/million/assets/77872387/2fe5573e-503a-432f-9c62-657f7547c8ae)
Getting this error while I am trying to build @pnodet

**Comment by aidenybai** [comment]
Fixed as of latest
