### ISSUE TITLE
Deprication warning of required dependencies

### ISSUE THREAD

**Issue by AfroXLandfee** [aidenybai/million#543]
### What version of `million` are you using?

2.5.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac and Linux

### What browser are you using?

Chrome, Firefox , Safari

### Describe the Bug

When trying to ```npm install``` I get the following errors for both @babel/polyfill@7.12.1 and core-js@2.6.12:

```deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.```

```deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.```

### What's the expected result?

To create and download node modules without errors

### Link to Minimal Reproducible Example

https://issueIsInTheTerminal.terminal/dontKnowHowToUseStackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by QuiiBz** [comment]
Note: Both deprecation warnings come from the [babel-plugin-transform-react-createelement-to-jsx](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx#readme) package, which hasn't been updated since a few years:

![Screenshot 2023-08-19 at 16 25 20](https://github.com/aidenybai/million/assets/43268759/1d2024f0-a14f-4344-9c96-a3bf81459dd8)

**Comment by AbhiPrasad** [comment]
[babel-plugin-transform-react-createelement-to-jsx](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx#readme) is also [GNU GPL v3](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx/blob/master/LICENSE), and there are [mixed opinions if it is allowed](https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l) for MIT licensed projects to still use the MIT license when using GNU GPL licensed projects.

It might make sense to just drop the dependency and re-implement @aidenybai

**Comment by aidenybai** [comment]
Fixed on latest @AfroXLandfee
