### ISSUE TITLE
[$30] Integrate Million.js into AnswerOverflow

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#553]
### Describe the feature

Integrate Million.js auto mode into https://github.com/AnswerOverflow/AnswerOverflow

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Akshay-Patel-dev** [comment]
@rishi-raj-jain  go ahead, incase you don't wan't , please tell me.

**Comment by rishi-raj-jain** [comment]
I commented on #552.

**Comment by Akshay-Patel-dev** [comment]
yeah,

**Comment by Akshay-Patel-dev** [comment]
@RhysSullivan  are you open for it?

**Comment by RhysSullivan** [comment]
@Akshay-Patel-dev Sure I'd be happy to accept a PR for it

**Comment by ayusham001** [comment]
Hii @aidenybai Please review my PR at https://github.com/AnswerOverflow/AnswerOverflow/pull/487

**Comment by ayusham001** [comment]
Hi @aidenybai , just checking in with you since it has been a while. Please revert back to this whenever you find it suitable, I will be looking forward to your reply.

**Comment by aidenybai** [comment]
@ayusham001 hey, thanks for the PR. looks like AnswerOverflow is no longer interested in Million.js, so we will close this issue. The condition for the bounty is that you must A. create a working PR and B. have the PR merged and integrated into prod. unfortunately this is not the case, so i am unable to award the bounty
