### ISSUE TITLE
[$30] Integrate Million.js into OpenSauced

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#554]
### Describe the feature

Integrate Million.js auto mode into https://github.com/open-sauced/app

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ayusham001** [comment]
/claim https://github.com/aidenybai/million/issues/554 via https://github.com/open-sauced/app/pull/1608

**Comment by ayusham001** [comment]
Hii @aidenybai Please review my PR at https://github.com/open-sauced/app/pull/1608
and let me know if any further changes are required

**Comment by ayusham001** [comment]
Hi @aidenybai , just checking in with you since it has been a while. Please revert back to this whenever you find it suitable, I will be looking forward to your reply.

**Comment by aidenybai** [comment]
Pending a merge status on the PR, a bounty will be awarded if merged

**Comment by a0m0rajab** [comment]
@aidenybai the PR is merged. 
@ayusham001 congrats on the prize!

**Comment by ayusham001** [comment]
Hi @aidenybai, now that the PR has been merged, can we proceed to the next step for the bounty?

**Comment by aidenybai** [comment]
Great work :) prize was awarded
![image](https://github.com/aidenybai/million/assets/38025074/1849a81b-89f6-4781-bfc3-c1be941d98e1)

**Comment by ayusham001** [comment]
Thank you @aidenybai :)
