### ISSUE TITLE
[$30] Integrate Million.js into Lenster

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#555]
### Describe the feature

Integrate Million.js auto mode into https://github.com/lensterxyz/lenster

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by rishi-raj-jain** [comment]
@bigint @saagu335 are you open to accepting a PR to it?

**Comment by evonloch** [comment]
@rishi-raj-jain Can you please tell me how to run million.js locally? As there is no dev command available?

**Comment by evonloch** [comment]
@rishi-raj-jain  😂. No man, I am not taking this one. Thanks

**Comment by rishi-raj-jain** [comment]
@bigint @saagu335 are you open to accepting a PR to it?

**Comment by bigint** [comment]
Yup we are open for the PR!

We can grant bounty of $200 from our side 🚀

cc @aidenybai

**Comment by rishi-raj-jain** [comment]
In crypto only!? I'd love it in PayPal/Stripe.
I'll get to it asap.

**Comment by bigint** [comment]
@rishi-raj-jain we can pay via PayPal as well!

**Comment by rishi-raj-jain** [comment]
That's great! I'll get on to it!

**Comment by anikdhabal** [comment]
> Hey @anikdhabal,
> 
> I am already working on it, as you can see from the comments above.

Ohh, I didn't notice it. Although my PR is not intuitive.

**Comment by rishi-raj-jain** [comment]
This issue is now dependent on #567

**Comment by kunal00000** [comment]
Hi @bigint , shall I make a PR to add million to hey.

**Comment by tobySolutions** [comment]
Any updates on this @rishi-raj-jain?

**Comment by rishi-raj-jain** [comment]
Well lenster closed it @tobySolutions, because of the reason they think it is kinda unresolvable: https://github.com/heyxyz/hey/pull/3632#issuecomment-1751663915

**Comment by rishi-raj-jain** [comment]
This issue is dependent on Slots one.
