### ISSUE TITLE
Daisy UI Dropdown Bug

### ISSUE THREAD

**Issue by GabTheGreat25** [aidenybai/million#560]
### What version of `million` are you using?

2.6.0-beta.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When I try combine daisyUI and Million js it doesn't have any problem only in the dropdown where the in built UI of daisyUI dropdown doesn't work.

### What's the expected result?

The dropdown should work when I click the avatar and it should instantly work because it's a pre built UI

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by oliverloops** [comment]
Hi @GabTheGreat25 👋, Can you provide a screenshot or the code of your dropdown implementation?

**Comment by Grenish** [comment]
Hello @GabTheGreat25, It would be a big help if you can provide an image of the problem or the video.

**Comment by oliverloops** [comment]
@GabTheGreat25 are you still having some troubles?, there's something we can see in action?

**Comment by tobySolutions** [comment]
Any updates @GabTheGreat25?

**Comment by rishi-raj-jain** [comment]
Hey all, the issue with dropdown is that each <select> that contains <For> created via million with <option> will be rendered as:

<select>
<slot>
<option>
</option>
</slot>
</select>

which is not supported <slot> is not a native tag. I think this is again, blocking given #567
