### ISSUE TITLE
[$500] Remove slots

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#567]
### Describe the feature

Remove the usage of <slot> elements from everything-from compile to runtime

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by feliciien** [comment]
https://discord.com/channels/938129049539186758/1148796877853163530

**Comment by rishi-raj-jain** [comment]
@feliciien We need the <slot> to be removed from components as it simply blocks all the parent CSS properties.

**Comment by feliciien** [comment]
I'm no longer authorized to work on this 😅

**Comment by rishi-raj-jain** [comment]
Oh okay okay

**Comment by rishi-raj-jain** [comment]
Why's that?

**Comment by itsvanshchavda** [comment]
Hello brother can you give some more description about that issue I want to work on this

**Comment by ogil7190** [comment]
@aidenybai is this issue open to solve?

**Comment by tobySolutions** [comment]
> @aidenybai is this issue open to solve?

Yep! Go ahead! 💯💯

**Comment by evoxf1** [comment]
is it still open ?

**Comment by dennismzia** [comment]
> is it still open ?

seems like so try your luck man

**Comment by joshpcausey** [comment]
@tobySolutions what element would should we render instead of <slot>

**Comment by tobySolutions** [comment]
> @tobySolutions @aidenybai what element should we render instead of slot



cc @aidenybai

**Comment by jeet-dhandha** [comment]
Can someone tell me why are we using slots to wrap components ?

**Comment by devilserpent123** [comment]
is this solved?

**Comment by tobySolutions** [comment]
> is this solved?
> 

Nope, not yet @devilserpent123. Do you want to take it on?

**Comment by devilserpent123** [comment]
Yeah sure.

**Comment by tobySolutions** [comment]
> Yeah sure.
> 

Awesome! Go ahead.

**Comment by ologbonowiwi** [comment]
@tobySolutions @aidenybai, is there any component we should use instead of a slot, or should we render just the plain component received?

**Comment by ologbonowiwi** [comment]
Can you assign this to me? I'll handle it. 

/claim #567

**Comment by sankalp142002** [comment]
Hello, @tobySolutions. Can I take this issue forward if the work is still not done?

**Comment by tobySolutions** [comment]
> Hello, @tobySolutions. Can I take this issue forward if the work is still not done?

Sure thing, go ahead @sankalp142002!

**Comment by aidenybai** [comment]
@aslemammad  Jan 15

**Comment by tobySolutions** [comment]
> @Aslemammad Jan 15

Oh, awesome! Nice one.

**Comment by skushagra9** [comment]
Is this issue solve, if not I would like to contribute here

**Comment by loganbek** [comment]
this still available?

**Comment by Aslemammad** [comment]
Everything's implemented, but the issue is that it's hard to trust the implemented technicalities in the PR, that's why we're trying to reimplement it partially here. So if that didn't succeed as well, I'll try to send an update here.

What we want to achieve with this PR is nearly impossible because of how much we're doing hacky solutions with portals and changing elements' positioning that are passed to us using Reactjs, which it'll lose control over after changing the positions.

Thank you so much.

**Comment by deepak-patwa-dkpit** [comment]
/attempt #567

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clm3w3u080002ml0fuvo1rg26/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
