### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [aidenybai/million#569]
### What version of `million` are you using?

Latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

Screenshot
<img width="947" alt="Screenshot 2023-09-07 164927" src="https://github.com/aidenybai/million/assets/91591901/2bb2d143-92eb-4eb5-aef6-0ef1e4568119">

### What's the expected result?

The Twitter logo should be changed to X.

### Link to Minimal Reproducible Example

https://million.dev/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Sure thing! You can go ahead and do that!

**Comment by tobySolutions** [comment]
I can assign you the issue.

**Comment by lalitkumawat1m** [comment]
Thanks @tobySolutions will raise a pr soon

**Comment by tobySolutions** [comment]
> Thanks @tobySolutions will raise a pr soon

Perfect.
