### ISSUE TITLE
Next.js and auto:true - using "next start" million.js runs and then stops server

### ISSUE THREAD

**Issue by Jahrhause** [aidenybai/million#570]
### What version of `million` are you using?

2.6.0-beta.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I have installed million.js and added it to my next.config.js as described in the tutorial.
When i start next.js in developer mode "Next Start" it looks like everything works fine, but after million.js has optimized some components it just exits the terminal.

```
- wait compiling /src/middleware (client and server)...
- event compiled successfully in 411 ms (53 modules)
- wait compiling /api/redirects (client and server)...

🦁  million  Automatic mode is enabled ✓ (beta)
Schedule a call if you need help: https://million.dev/hotline. To disable help messages, set the "mute" option to true.
There is no guarantee that features in beta will be completely production ready, so here be dragons.

💡 TIP: Use // million-ignore to skip over problematic components.

- event compiled successfully in 2.8s (78 modules)
- wait compiling / (client and server)...
⚡ <ErrorFallback> was optimized. Estimated reconciliation improvement: ~41% faster.
   7 nodes, 3 attributes, 2 texts, 1 components, and 4 expressions. Average depth = 5. (12 - 5) / (12 + 5) = 41%.
⚡ <DynamicComponent> was optimized. Estimated reconciliation improvement: ~38% faster.
   5 nodes, 3 attributes, 3 texts, 1 components, and 4 expressions. Average depth = 4. (11 - 5) / (11 + 5) = 38%.
⚡ <Employee> was optimized. Estimated reconciliation improvement: ~11% faster.
   17 nodes, 18 attributes, 0 texts, 5 components, and 23 expressions. Average depth = 2. (35 - 28) / (35 + 28) = 11%.
⚡ <Preview> was optimized. Estimated reconciliation improvement: ~64% faster.
   4 nodes, 3 attributes, 2 texts, 1 components, and 1 expressions. Average depth = 0. (9 - 2) / (9 + 2) = 64%.
```

### What's the expected result?

I would excpect it to keep running the server, so I could view the page by going to localhost:3000.
Or is this only a build time thing and cant be use together with the server running?

I apologize if this is not a bug but intended behaviour.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by vitaliy-grusha** [comment]
I am using  million@2.6.0-beta.13 with next@13.4.19. Works fine with this config:

next.config.mjs
```typescript 
import million from 'million/compiler';

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: 'standalone',
}

const millionConfig = {
  auto: { rsc: true },
}

export default million.next(nextConfig, millionConfig);
```

**Comment by tobySolutions** [comment]
Yep! I just used it on a project too. I think you should change it to next.config.mjs

**Comment by Jahrhause** [comment]
Thanks everyone....
Must have been Gremlins in my machine, today it just works, nothing changed :)

**Comment by tobySolutions** [comment]
> Thanks everyone....
> Must have been Gremlins in my machine, today it just works, nothing changed :)

Awesome! Glad it works now.
