### ISSUE TITLE
[$150] CLI-based setup wizard

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/million#571]
### Describe the feature

Create a CLI (distributed via the `million`) package that: 

- Automatically detects the environment (e.g. Next.js, Vite, Webpack), or if not available, prompt options to pick a compatible build tool (Currently compatible with: Next.js, Gatsby, Astro, Vite, Create-React-App, Webpack, Rollup, Rspack, Esbuild). [See installation page](https://million.dev/docs/install#use-the-compiler)
- Create or update the config with Million.js auto mode options. Provide a diff so it is not destructive. If this is Next.js, make sure to detect for App router (RSC mode for auto mode)
- Be able to call this via CLI (e.g. `npx million@latest`)
- Provide a fallback to the installation page if failed: https://million.dev/docs/install#use-the-compiler
- Add documentation on this feature (ideally the default path for installation)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by rishi-raj-jain** [comment]
@aidenybai Are you sure you don't want to raise the about to maybe $150, it's a whole CLI we're talking about!

**Comment by kunal00000** [comment]
Hi @aidenybai . I would like to this one up.
/attempt #571

**Comment by aidenybai** [comment]
@rishi-raj-jain changed to 125! i think it should be a lot simpler than a fully fledged cli – main problems are adding the plugin and detecting files really

**Comment by AbhiPrasad** [comment]
If it’s useful, sentry has written a guide about how to create good wizard for setting up libraries/SDKs. I recommend the million CLI take some inspiration from this guide. 

There is some sentry specific stuff in here, but the general principles around how to structure a cli and the DX it should have https://develop.sentry.dev/sdk/setup-wizards/

specifically the tricky thing is to figure out how to mutate configs/js files. I recommend taking a look at https://github.com/unjs/magicast to make this easy.

**Comment by rishi-raj-jain** [comment]
Thanks for the references, @AbhiPrasad! I'd love to work on this!
/#571
