### ISSUE TITLE
Millionjs compatibility with lodable when using webpack 4

### ISSUE THREAD

**Issue by jainChetan81** [aidenybai/million#576]
### What version of `million` are you using?

2.5.13

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

We are using lodable, with webpack 4 config at my office, the stack is custom built SSR without and framework, for reference [this link here](https://github.com/wellyshen/react-cool-starter) is the repo we are using to build or web app.
The problem I am facing is with lodable on cold start, it has trouble understanding lodable config and I couldn't find a way to overrride this without breaking anything else and I couldn't understand the error.

error images
<img width="1047" alt="Screenshot 2023-09-13 at 3 36 46 PM" src="https://github.com/aidenybai/million/assets/38555207/2fb3359c-79c1-4ed1-ad2d-1b6f04a3d73c">
<img width="1116" alt="Screenshot 2023-09-13 at 3 36 59 PM" src="https://github.com/aidenybai/million/assets/38555207/eb33b0a0-8656-48d6-8984-b84b4c24bd41">

### What's the expected result?

Million should be able to work with lodable

### Link to Minimal Reproducible Example

https://github.com/wellyshen/react-cool-starter

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
@jainChetan81 can you try on latest?

**Comment by tobySolutions** [comment]
Hey @jainChetan81! Any updates on this?

**Comment by jainChetan81** [comment]
same issue, using this with million@2.6.0 now

**Comment by Drex72** [comment]
Hey @jainChetan81 ,retry again with version 2.6.4
if it persists, let us know

**Comment by jainChetan81** [comment]
Sure, will update here...
