### ISSUE TITLE
Not able to use UseState inside the block

### ISSUE THREAD

**Issue by kdRanaa** [aidenybai/million#581]
### What version of `million` are you using?

2.6.0-beta.13

### Are you using an SSR adapter? If so, which one?

NO

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

While using block component 

`const Block=block(MyComp)`

I am getting error "Invalid hook call. Hooks can only be called inside of the body of a function component"

I am using useState hooks inside the component.

### What's the expected result?

The block should work without the above issue

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kul-sudo** [comment]
Could you send that piece of code, please?

**Comment by rishi-raj-jain** [comment]
Agreed, @kdRanaa can we have a minimal reproduction that you're facing?

**Comment by kdRanaa** [comment]
Here is the code snippet

`import React from 'react'
import {block} from 'million/react'


const Mycomp=()=>{
  const [state,setState]=React.useState<number>(0)

  return (
    <p>{state}</p>
  )
}

const Myblock=block(Mycomp)

export default Myblock

`



And the error i am getting is 
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

**Comment by kul-sudo** [comment]
> Here is the code snippet
> 
> ```
> import React from 'react'
> import {block} from 'million/react'
> 
> 
> 
> const Mycomp=()=>{
>   const [state,setState]=React.useState<number>(0)
> 
>   return (
>     <p>{state}</p>
>   )
> }
> 
> const Myblock=block(Mycomp)
> 
> export default Myblock
> ```
> 
> And the error i am getting is
> 
> ```
> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> ```

Well, that's a rule blocks are supposed to follow. If you really need to use the state, then pass it's value and the function for setting it to a value as arguments to the component of the block.

**Comment by aidenybai** [comment]
This is likely a misconfiguration with the compiler. Can you send your config? @kul-sudo

**Comment by kul-sudo** [comment]
> This is likely a misconfiguration with the compiler. Can you send your config? @kul-sudo

I am not the one who has the problem.

**Comment by kdRanaa** [comment]
`I am using react-app-rewired 

const path = require("path");
const fs = require("fs");
const rewireBabelLoader = require("react-app-rewire-babel-loader");
const million = require('million/compiler');

const appDirectory = fs.realpathSync(process.cwd());
module.exports = function override(config, env) {

  

  

  config.plugins = (config.plugins || []).concat([
    million.webpack()
  ]);
  
  config.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto",
  });



  return config;
};

`
i have added the configuration to the file, now i am getting runtime error , regarding "Module Not Found" which were imported from mui and other.

**Comment by kdRanaa** [comment]
@kul-sudo, I have shared my compiler configuration.

**Comment by kul-sudo** [comment]
> @kul-sudo, I have shared my compiler configuration.

I have never used ```react-app-rewired```, so I am not sure what I can say.

**Comment by Drex72** [comment]
@aidenybai  can you have a look at @kdRanaa  configuration becuase it looks alright to me, but look at it and see if it's the configuration that's causing the issue
and @kdRanaa , try updating to the latest version of million and see if the issue still persists

**Comment by tobySolutions** [comment]
Are you still getting the same error @kdRanaa?

**Comment by afreix-bricks** [comment]
@aidenybai 

> This is likely a misconfiguration with the compiler

I'm seeing this as well and I'm not confident my compiler is set up correctly. Is there something I can do to validate my complier set up?

**Comment by rushi-visilean** [comment]
I am facing the same basic issue, any help would be appreciated!

**Comment by Skarvion** [comment]
@rushi-visilean I had the same issue the other day. Have you installed craco yet? After installing it, I manage to get it working.

One thing that the documentation needs for newbie (like me) is that it's dependent on craco instead of assuming prior knowledge just because it shows a craco configuration file.

**Comment by rushi-visilean** [comment]
Hi @Skarvion 

Thanks for your prompt reply and for sharing your experience. I completely agree with your observation. After installing Craco and updating the start script, I successfully integrated Million. It's great to know I wasn't the only one facing this and that it worked for you too.

I completely empathize with your point about the documentation. It's crucial to have clear instructions, especially for newcomers like us. The documentation could be improved by highlighting the dependency on Craco for newcomers who might not have prior knowledge. It can be quite confusing without explicit guidance.

Hopefully, our feedback will help refine the documentation for a smoother experience for future users.

**Comment by tobySolutions** [comment]
> Hi @Skarvion 
> 
> Thanks for your prompt reply and for sharing your experience. I completely agree with your observation. After installing Craco and updating the start script, I successfully integrated Million. It's great to know I wasn't the only one facing this and that it worked for you too.
> 
> I completely empathize with your point about the documentation. It's crucial to have clear instructions, especially for newcomers like us. The documentation could be improved by highlighting the dependency on Craco for newcomers who might not have prior knowledge. It can be quite confusing without explicit guidance.
> 
> Hopefully, our feedback will help refine the documentation for a smoother experience for future users.

Thank you very much, Rushi!! We're actually on it 😢😢😢
