### ISSUE TITLE
Add support for Turbopack in Next.js 13

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [aidenybai/million#585]
### Describe the feature

Usually I use Turbopack instead of Webpack. I am experiencing an error rendering the root server when attempting to use Turbopack in conjunction with Million.js.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hmm, what is this issue, please?

**Comment by pupbrained** [comment]
Having a similar issue with our NextJS + turbopack project here -- million gives errors relating to rules of hooks and making sure we installed the compiler correctly, but I triple-checked everything and it looks fine. On top of that, none of these problems are present when using webpack.

**Comment by Drex72** [comment]
We'll look into that
Thank you for reporting the issue

**Comment by lockieluke** [comment]
Million still doesn't work with Turbopack enabled

**Comment by verekia** [comment]
Can confirm that this is still the case.

Next.js 14.2.3 + @million/lint 1.0.0-rc.13 does not work with Turbopack.

If you use `next dev --turbo`, remove `--turbo`.

**Comment by sickl8** [comment]
2026, doesn't work, compiler errors even if you try `next dev --webpack`
