### ISSUE TITLE
not able to add todo task after removing it - Million Kitchen Sink

### ISSUE THREAD

**Issue by merouanezouaid** [aidenybai/million#586]
### What version of `million` are you using?

i tested on the sink website

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

none

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

when i add a todo task and remove it and readd it it doesn't work 

here's the reproduction of the issue:

![bug sink](https://github.com/aidenybai/million/assets/74367730/19f2c7aa-278d-4cd1-bafa-35a474661ff9)

### What's the expected result?

i expect it to operate normally by adding and removing any task

### Link to Minimal Reproducible Example

https://github.com/aidenybai/million/assets/74367730/19f2c7aa-278d-4cd1-bafa-35a474661ff9

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by oliverloops** [comment]
hello @merouanezouaid 👋, I'm on this right now. let me correct it and update the kitchen sink. thanks for reporting this issue

**Comment by merouanezouaid** [comment]
for sure!! thank you :D

**Comment by tobySolutions** [comment]
Awesome! Has this been fixed @merouanezouaid?

**Comment by merouanezouaid** [comment]
> Awesome! Has this been fixed @merouanezouaid?

actually not yet, i think it hasn't get pushed to prod yet since Oliver was working on it

**Comment by oliverloops** [comment]
Hello again, sorry for the delay guys. the solution PR is already on https://github.com/aidenybai/million/pull/728, thanks for report it @merouanezouaid, when the PR is merged we can close this issue @tobySolutions

**Comment by tobySolutions** [comment]
Awesome! Thanks for this @oliverloops. I'll review in a bit. 🙌 🙌

**Comment by vimode** [comment]
This bug is similar to #680

**Comment by tobySolutions** [comment]
Thank you @merouanezouaid. Is this a go-ahead to merge your PR @oliverloops?  I'll check it out in a few.

**Comment by oliverloops** [comment]
Hello. Yes @tobySolutions, this fix is included on the PR 👍

**Comment by tobySolutions** [comment]
Hmm, oh ok awesome @oliverloops. I'll be reviewing it now.

**Comment by tobySolutions** [comment]
https://github.com/aidenybai/million/pull/728

Can you please make another PR @oliverloops, it seems I mistakenly closed this and for some reason I don't have access to reopen it.

**Comment by oliverloops** [comment]
Is still open, is one of the 4 PR's open now. The Kitchen Sink bugs fixed one

**Comment by tobySolutions** [comment]
> Is still open, is one of the 4 PR's open now. The Kitchen Sink bugs fixed one

Oh, my bad. Let me check that one

**Comment by oliverloops** [comment]
No worries, that PR should fix this problem and other related reported on a closed issue before
