### ISSUE TITLE
TypeScript error from React Vite

### ISSUE THREAD

**Issue by tuanductran** [aidenybai/million#591]
My package.json:

`
{
  "name": "todo-list",
  "private": true,
  "version": "1.0.0",
  "packageManager": "pnpm@8.7.6",
  "scripts": {
    "dev": "concurrently \"pnpm dev:layout\" \"pnpm dev:tailwind\"",
    "dev:layout": "vite",
    "dev:tailwind": "pnpm postcss css/app.css -o css/build.css --watch",
    "build": "vite build",
    "build:all": "pnpm build:tailwind && pnpm build",
    "build:tailwind": "pnpm postcss css/app.css -o css/build.css --verbose",
    "preview": "vite preview",
    "prettier:check": "prettier --check \"**/*.{js,jsx,ts,tsx,css}\" --cache",
    "prettier:write": "prettier --write \"**/*.{js,jsx,ts,tsx,css}\" --cache",
    "lint": "tsc"
  },
  "dependencies": {
    "clsx": "^2.0.0",
    "dompurify": "^3.0.5",
    "million": "^2.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hot-toast": "^2.4.1",
    "swr": "^2.2.2",
    "tailwindcss": "^3.3.3",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@ianvs/prettier-plugin-sort-imports": "^4.1.0",
    "@types/node": "^20.6.2",
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "6.7.2",
    "@typescript-eslint/parser": "6.7.2",
    "@vitejs/plugin-react": "^4.1.0",
    "autoprefixer": "^10.4.15",
    "concurrently": "^8.2.1",
    "eslint": "8.50.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-plugin-import": "2.28.1",
    "eslint-plugin-react": "7.33.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-tailwindcss": "3.13.0",
    "eslint-plugin-typescript-sort-keys": "3.0.0",
    "eslint-plugin-unicorn": "48.0.1",
    "postcss": "^8.4.29",
    "postcss-cli": "^10.1.0",
    "postcss-import": "^15.1.0",
    "postcss-lightningcss": "^1.0.0",
    "prettier": "3.0.3",
    "prettier-plugin-pkg": "0.18.0",
    "prettier-plugin-tailwindcss": "0.5.4",
    "turbo": "^1.10.14",
    "typescript": "^5.2.2",
    "vite": "^4.4.9"
  }
}
`

Log error:

`pnpm tsc`

node_modules/.pnpm/million@2.6.0/node_modules/million/dist/packages/compiler.d.ts:1:1 - error TS1036: Statements are not allowed in ambient contexts.

1 'use client';
  ~~~~~~~~~~~~

node_modules/.pnpm/million@2.6.0/node_modules/million/dist/packages/compiler.d.ts:23:46 - error TS2304: Cannot find name 'WebpackPluginInstance'.

23 declare const webpack: (options: Options) => WebpackPluginInstance;
                                                ~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/million@2.6.0/node_modules/million/dist/packages/compiler.d.ts:25:45 - error TS2304: Cannot find name 'RspackPluginInstance'.

25 declare const rspack: (options: Options) => RspackPluginInstance;
                                               ~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/million@2.6.0/node_modules/million/dist/packages/compiler.d.ts:32:36 - error TS2304: Cannot find name 'WebpackPluginInstance'.

32     webpack: (options: Options) => WebpackPluginInstance;
                                      ~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/million@2.6.0/node_modules/million/dist/packages/compiler.d.ts:34:35 - error TS2304: Cannot find name 'RspackPluginInstance'.

34     rspack: (options: Options) => RspackPluginInstance;
                                     ~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:1:47 - error TS2307: Cannot find module '@rspack/core/dist/config/zod' or its corresponding type declarations.

1 import * as _rspack_core_dist_config_zod from '@rspack/core/dist/config/zod';
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:2:26 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

2 import * as webpack from 'webpack';
                           ~~~~~~~~~

node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:3:49 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

3 import { Compiler, WebpackPluginInstance } from 'webpack';
                                                  ~~~~~~~~~

node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:4:68 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

4 export { Compiler as WebpackCompiler, WebpackPluginInstance } from 'webpack';
                                                                     ~~~~~~~~~

node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:14:62 - error TS2307: Cannot find module '@rspack/core' or its corresponding type declarations.

14 import { Compiler as Compiler$1, RspackPluginInstance } from '@rspack/core';
                                                                ~~~~~~~~~~~~~~

node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:15:66 - error TS2307: Cannot find module '@rspack/core' or its corresponding type declarations.

15 export { Compiler as RspackCompiler, RspackPluginInstance } from '@rspack/core';
                                                                    ~~~~~~~~~~~~~~

node_modules/.pnpm/webpack-virtual-modules@0.5.0/node_modules/webpack-virtual-modules/lib/index.d.ts:1:31 - error TS2307: Cannot find module 'webpack' or its corresponding type declarations.

1 import type { Compiler } from 'webpack';
                                ~~~~~~~~~


Found 12 errors in 3 files.

Errors  Files
     5  node_modules/.pnpm/million@2.6.0/node_modules/million/dist/packages/compiler.d.ts:1
     6  node_modules/.pnpm/unplugin@1.5.0/node_modules/unplugin/dist/index.d.ts:1

**Comment by rishi-raj-jain** [comment]
Hey @tuanductran,

Can you help us with a minimal reproduction? Thanks!

**Comment by Drex72** [comment]
@tuanductran  any response on the minmal reproduction?

**Comment by tobySolutions** [comment]
Hey there @tuanductran? I'll be closing this now.
