### ISSUE TITLE
TypeError: Illegal invocation, The above error occurred in the <Effect> component:

### ISSUE THREAD

**Issue by NishilSB** [aidenybai/million#592]
### What version of `million` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/aidenybai/million/assets/18629343/57b62431-6ef3-4b28-a9af-df640a698fc7)

### What's the expected result?

App should build/run successfully

### Link to Minimal Reproducible Example

https://stackoverflow.com/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by rishi-raj-jain** [comment]
Hey @NishilSB,

Can you help us with a minimal reproduction? Thanks!

**Comment by NishilSB** [comment]
please find the code sand box
https://codesandbox.io/s/kind-bush-94kxkn?file=/src/App.js
