### ISSUE TITLE
Endless components are optimized in the console

### ISSUE THREAD

**Issue by khoakomlem** [aidenybai/million#594]
### What version of `million` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/aidenybai/million/assets/46867018/1f0090de-8189-4617-b2fb-f5d260b1066d)
![image](https://github.com/aidenybai/million/assets/46867018/bb184733-a554-443b-99ff-112444f2f29d)
It never stops and I cannot load any pages of my app
The page wont load so it's not necessary to have example
![image](https://github.com/aidenybai/million/assets/46867018/abb5f9a6-e90a-4db9-b795-4467b279a665)

### What's the expected result?

Load the page and no endless optimize components

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Pratikdate** [comment]
Assign me i will work upon it

**Comment by Pratikdate** [comment]
Can you add hecktoberfest icon

**Comment by tobySolutions** [comment]
Awesome! Sure thing! Go ahead.

**Comment by SukkaW** [comment]
> Assign me i will work upon it
> Can you add hecktoberfest icon

@Pratikdate Ping me or @tobySolutions when the PR is opened so that we can add the `hacktoberfest-accepted` label to your PR!

**Comment by tobySolutions** [comment]
> > Assign me i will work upon it
> > Can you add hecktoberfest icon
> 
> @Pratikdate Ping me or @tobySolutions when the PR is opened, so that we can add the `hacktoberfest-accepted` label to your PR!

Thank you Sukka!

**Comment by khoakomlem** [comment]
Any updates?

**Comment by tobySolutions** [comment]
Are you still getting this error @khoakomlem?

**Comment by tobySolutions** [comment]
Any updates @Pratikdate?

**Comment by khoakomlem** [comment]
> Hey there @khoakomlem can you provide a repro of this?

Sorry I can't but I will try my best to provide detail imformation

**Comment by khoakomlem** [comment]
> Are you still getting this error @khoakomlem?

No since you ask me this, I will reopen this when it occurs again
