### ISSUE TITLE
Kitchen Sink: Build A Weather App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#600]
Build an app that displays current weather data using a weather API that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by cyberviking5** [comment]
please assign this issue to me

**Comment by tobySolutions** [comment]
> please assign this issue to me

Sure thing, go ahead!!

**Comment by vatsalsinghkv** [comment]
@tobySolutions I'd also like to contribute by sharing weather app. Is it possible to have two weather apps?

**Comment by tobySolutions** [comment]
> @tobySolutions I'd also like to contribute by sharing weather app. Is it possible to have two weather apps?
> 

Sure thing! @vatsalsinghkv

**Comment by cyberviking5** [comment]
@tobySolutions i have submitted the pr please review it :)

**Comment by tobySolutions** [comment]
Hmm, oh ok @cyberviking5. You're right. I'll check out your PR and reconsider you.

**Comment by tobySolutions** [comment]
Fixed by #635
