### ISSUE TITLE
Kitchen Sink: Build A Recipe Finder

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#601]
Build a recipe finder app that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Yash9276** [comment]
Is a recipe finder like you can search any recipes with their names or ingredients names? 
If yes, then assign it to me, I want to develop a recipe finder
Thank you :)

**Comment by arunavabasu-03** [comment]
can assign me this ! and what api we need to use for this like any prefered ??

**Comment by TechWizard9999** [comment]
@tobySolutions  I am intrested in it 
Please assign it to me

**Comment by tobySolutions** [comment]
Sure thing @TechWizard9999!
