### ISSUE TITLE
Kitchen Sink: Task Tracker with Drag and Drop: 

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#602]
Build a task tracker where users can drag and drop tasks to change their status that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by devhd9** [comment]
Hey @tobySolutions , I would love to build this. can you please assign this to me ?

**Comment by tobySolutions** [comment]
Hey there @devhd9! Sure thing.

**Comment by tobySolutions** [comment]
Awesome work @devhd9, I can see that you have an existing PR; gonna review that soon, Thanks.

**Comment by tobySolutions** [comment]
fixed by #710
