### ISSUE TITLE
Kitchen Sink: Build A News Aggregator App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#603]
Build an app that aggregates news articles from various sources using a news API.that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by sukritmalpani** [comment]
@tobySolutions Can you please assign this issue to me?

**Comment by tobySolutions** [comment]
Sure thing! @sukritmalpani!

**Comment by tobySolutions** [comment]
Fixed by #646
