### ISSUE TITLE
Kitchen Sink: Build A Currency Converter

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#604]
Build a currency converter with real-time exchange rates that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Roar022** [comment]
@tobySolutions Please assign this issue to me. I wanna solve this issue.

**Comment by tobySolutions** [comment]
> @tobySolutions Please assign this issue to me. I wanna solve this issue.

Sure thing! Go ahead! 😁😁.
