### ISSUE TITLE
Kitchen Sink: Build A Pomodoro Timer App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#605]
Build a Pomodoro timer for productivity that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md  

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Devanshukoli** [comment]
@tobySolutions could you please assign this issueto me. I would like to work on it.

**Comment by arunavabasu-03** [comment]
Can pls assign it to me ?

**Comment by tobySolutions** [comment]
Hey there @arunavabasu-03, @Devanshukoli requested first; I think it's only fair that we let them have this.

**Comment by tobySolutions** [comment]
Issue fixed by #695
