### ISSUE TITLE
Kitchen Sink: Build An Expense Tracker

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#606]
Build an app for tracking expenses and income that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by vimode** [comment]
Hey @tobySolutions I would like to contribute to this!

Seems like a great opportunity to *get my feet wet* in **million**.  😄

**Comment by BikramNarayan** [comment]
I want to work on this issue.

**Comment by tobySolutions** [comment]
Hey there @BikramNarayan! @vimode requested to be assigned this first, I think it's only fair we assigned them this.

**Comment by tobySolutions** [comment]
Gonna check out your PR soon @vimode

**Comment by tobySolutions** [comment]
Issue closed by #655
