### ISSUE TITLE
Kitchen Sink: Build A Quiz App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#607]
Build a quiz app with multiple-choice questions and a scoring system that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by arunavabasu-03** [comment]
can you assign it to me ?

**Comment by tobySolutions** [comment]
> can you assign it to me ?

Sure thing! Go ahead! 🙌🙌

**Comment by tobySolutions** [comment]
Resolved by #691
