### ISSUE TITLE
Kitchen Sink: Build A Calendar App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#608]
Build a calendar application with event creation and reminders that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by ATREAY** [comment]
hey @tobySolutions, can I work on this issue?

**Comment by rjangid9080** [comment]
hey @tobySolutions, Please assign to me?

**Comment by tobySolutions** [comment]
Hey there @rjangid9080, @ATREAY requested first, so maybe we should let him have this one.

**Comment by ATREAY** [comment]
Hey @tobySolutions, I've added a calendar app. Could you please take a look when you have a moment?

**Comment by tobySolutions** [comment]
Hey @ATREAY! Sure thing, gonna check it out.

**Comment by tobySolutions** [comment]
Issue fixed by #642
