### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mehanalavimajd** [aidenybai/million#61]
**Describe the bug**
I wanted to use million.js but I got this error `Uncaught SyntaxError: Cannot use import statement outside a module`

**To Reproduce**
I installed million and this is my file:
```
import {m , patch , createElement} from "million"

const app = createElement(m("h1" , {id:"app"} , ["helloworld"]))
document.body.appendChild(app)
patch(app , m("div" , {id:"app"}, ["goodbye"]))
```

**Screenshots**
![Screenshot from 2021-07-07 13-00-22](https://user-images.githubusercontent.com/74927578/124726904-708bed80-df23-11eb-9d95-6a31c10140b7.png)

**Desktop (please complete the following information):**

- OS: [linux ubuntu]
- Browser [chrome]
- Version [Version 91.0.4472.114 (Official Build) (64-bit)]

**Comment by aidenybai** [comment]
Are you bundling this? If you are, you'll need to attach a `type="module"` attribute to the script tag

**Comment by mehanalavimajd** [comment]
Thanks a lot 🙏
