### ISSUE TITLE
Kitchen Sink: Build A Location-Based App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#610]
Build an app that uses geolocation to display nearby points of interest that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by arunavabasu-03** [comment]
Can pls assign it to me !

**Comment by tobySolutions** [comment]
Sure thing! Go ahead @arunavabasu-03.
