### ISSUE TITLE
Kitchen Sink: Build A Crypto Currency Tracker

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#612]
Build an app that displays real-time cryptocurrency prices and trends that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by cyberviking5** [comment]
@tobySolutions please assign me this issue :)

**Comment by arunavabasu-03** [comment]
Can pls assign me this !

**Comment by tobySolutions** [comment]
Hey there @cyberviking5, @arunavabasu-03; I think @cyberviking5 requested first, so I think I might assign this to him instead.

**Comment by tobySolutions** [comment]
fixed by #653
