### ISSUE TITLE
Kitchen Sink: Build A Virtual Whiteboard

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#613]
Build a collaborative virtual whiteboard for drawing and brainstorming; you can keep it simple too if you want to that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by one2code** [comment]
I'd like to be assigned this issue. Thx.

**Comment by tobySolutions** [comment]
Sure thing! Go ahead 😁.

**Comment by tobySolutions** [comment]
Hey there @one2code, any updates on this at all?

**Comment by one2code** [comment]
@tobySolutions PR is in. I ended up starting a bit later than expected and encountered more technical challenges than I initially anticipated. Overall, I'm satisfied with the PR and had a lot of fun. Was a great learning experience!

**Comment by tobySolutions** [comment]
Awesome work @one2code! I love all the work and the whole building in public is just amazing. I can't wait to go review this PR.

**Comment by tobySolutions** [comment]
Closed by #742
