### ISSUE TITLE
Kitchen Sink: Build A Personal Journal

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#614]
Build a digital journaling app with text and multimedia entries that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by rakshixh** [comment]
Hey @tobySolutions I would like to work on this. Please assign me this issue! Thank you!

**Comment by tobySolutions** [comment]
Sure thing! Go ahead 😁

**Comment by tobySolutions** [comment]
Hey there @rakshixh, any updates on this?

**Comment by rakshixh** [comment]
Hey @tobySolutions This issue can be closed now right, since it is solved?

**Comment by tobySolutions** [comment]
Sure thing @rakshixh. Issue fixed by #737
