### ISSUE TITLE
Kitchen Sink: Build A Real-time Polling App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#615]
Build a polling app that displays real-time results that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by UzairNoman** [comment]
Hi @tobySolutions, I would like to work on this issue :)

**Comment by tobySolutions** [comment]
Sure thing @UzairNoman!

**Comment by UzairNoman** [comment]
Hi @tobySolutions, I have mentioned the blocker in screen sharing in issue https://github.com/aidenybai/million/issues/680. But I think you have closed the polling app feature PR by mistake, this feature is almost completed, just needs a reset button as @Timonwa suggested in the PR. I will implement it soon as we find some solution to https://github.com/aidenybai/million/issues/680. Can we reopen that issue?

**Comment by tobySolutions** [comment]
Hey there @UzairNoman, you can go ahead and maybe work make a PR including the bug, so I can raise it with the team and we can also have a look at it. Thanks!

**Comment by UzairNoman** [comment]
Hi @tobySolutions, sounds good! can you please open the #669 PR again, I will work on it.

**Comment by tobySolutions** [comment]
> Hi @tobySolutions, sounds good! can you please open the #669 PR again, I will work on it.

Awesome! You can just make another PR though. I will review it accordingly.
