### ISSUE TITLE
Kitchen Sink: Build A Blog or Portfolio Website

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#616]
Build a personal blog or portfolio website to showcase your work that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by vatsalsinghkv** [comment]
@tobySolutions Can I work on this issue? Please assign it to me. I am thinking to using my professional portfolio website template which is easy to use and many people are using it for their portfolio.

**Comment by tobySolutions** [comment]
> @tobySolutions Can I work on this issue? Please assign it to me. I am thinking to using my professional portfolio website template which is easy to use and many people are using it for their portfolio.
> 

Sure thing! Go ahead.

**Comment by vatsalsinghkv** [comment]
@tobySolutions Hey so I was adding an amazing portfolio website. But i've built it with tailwindCSS & framer motion for animations, so would it be okey if I install it in the kitchen-sink?

**Comment by tobySolutions** [comment]
Yeah, sure thing @vatsalsinghkv! As long as it's Millionified! I hope tailwind doesn't mess things up though as per styles and stuff.

**Comment by tobySolutions** [comment]
Hey there @vatsalsinghkv, any updates at all on this?
