### ISSUE TITLE
Kitchen Sink: Build A Meme Generator

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#617]
Build a meme generator where users can add text to popular meme templates that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by adhirajkar3103** [comment]
Please can you assign me this task/issue?

**Comment by sr2005roy** [comment]
@tobySolutions I would like to work on this issue please assign me.

**Comment by BikramNarayan** [comment]
@tobySolutions, I would like to take ownership of this issue and work on it. I have already completed some portions of it.

**Comment by tobySolutions** [comment]
Hey there @adhirajkar3103, @BikramNarayan; I think @adhirajkar3103 requested first. Are you still interested in this Adhiraj?

**Comment by adhirajkar3103** [comment]
Hey @tobySolutions  I am still interested! looking forward to contribute

**Comment by tobySolutions** [comment]
Sorry folks, but, @adhirajkar3103 requested first. I can assign all of you though.

**Comment by tobySolutions** [comment]
Hey there @adhirajkar3103, any updates on this at all?

**Comment by tobySolutions** [comment]
Anyone at all?
