### ISSUE TITLE
Kitchen Sink: Build A Flashcard Vocabulary Game

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#618]
Build a vocabulary-learning game with flashcards and quizzes that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by grbknr1996** [comment]
Can you assign this to me @tobySolutions

**Comment by tobySolutions** [comment]
Sorry @grbknr1996, I didn't see this sooner. It's all yours!

**Comment by grbknr1996** [comment]
Thanks :) Started working on it 👍

**Comment by tobySolutions** [comment]
Issue fixes by #709
