### ISSUE TITLE
Kitchen Sink: Build A Drawing Canvas

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#619]
Build a drawing canvas with tools for drawing and coloring artwork that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Yash7426** [comment]
@tobySolutions Can you assign this issue to me.

**Comment by tobySolutions** [comment]
Sure thing! @Yash7426!

**Comment by Hicode-dev** [comment]
@tobySolutions  can you assign me to this issue too

**Comment by Yash7426** [comment]
@tobySolutions Please review my PR.
