### ISSUE TITLE
Kitchen Sink: Build A Emoji Picker

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#620]
Build an emoji picker that lets users easily insert emojis into text inputs that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Roar022** [comment]
@tobySolutions Please assign this issue to me. I wolud like to solve this issue.

**Comment by tobySolutions** [comment]
> @tobySolutions Please assign this issue to me. I wolud like to solve this issue.
>  

Wait, you're working on some other issues too, you sure you can manage them?

**Comment by Roar022** [comment]
> > @tobySolutions Please assign this issue to me. I wolud like to solve this issue.
> 
> Wait, you're working on some other issues too, you sure you can manage them?

YES

**Comment by tobySolutions** [comment]
> > > @tobySolutions Please assign this issue to me. I wolud like to solve this issue.
> > 
> > Wait, you're working on some other issues too, you sure you can manage them?
> 
> YES

Ok cool, awesome!
