### ISSUE TITLE
Kitchen Sink: Build A  File Upload and Preview Component

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#623]
Build a file upload component that allows users to upload images and displays a preview that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by darshbaxi** [comment]
@tobySolutions  I want to work on this issue, can you assign this issue to me?

**Comment by tobySolutions** [comment]
> @tobySolutions  I want to work on this issue, can you assign this issue to me?

Sure thing! Go ahead! 🙌

**Comment by darshbaxi** [comment]
@tobySolutions  please review my PR. I made all the requested changes.

**Comment by tobySolutions** [comment]
Awesome!

**Comment by darshbaxi** [comment]
@tobySolutions  suggested changes made, please review my PR again :)
