### ISSUE TITLE
Kitchen Sink: Build A Markdown Editor

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#624]
Build a Markdown editor that allows users to write and preview formatted text that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by sr2005roy** [comment]
@tobySolutions please assign this issue to me

**Comment by cyberviking5** [comment]
@tobySolutions  please assign me this issue

**Comment by tobySolutions** [comment]
> @tobySolutions  please assign me this issue
> 

Sure thing! Go ahead! 🙌🙌

**Comment by UzairNoman** [comment]
I'd like to contribute to this one :)

**Comment by tobySolutions** [comment]
> I'd like to contribute to this one :)

Maybe you can discuss with @cyberviking5 to know how far they have gotten with the issue.

**Comment by tobySolutions** [comment]
Thay already have a PR on this; sorry I forgot.

**Comment by tobySolutions** [comment]
Hey there @UzairNoman, if you'd still like to work on this, please do let me know 😁

**Comment by UzairNoman** [comment]
Hi @tobySolutions, yes, sure, please assign it to me :)

**Comment by tobySolutions** [comment]
Awesome @UzairNoman, I'm gonna review your PR soon. Thanks!
