### ISSUE TITLE
Kitchen Sink: Build A URL Shortener

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#625]
Build a URL shortening service that takes long URLs and generates short, shareable links that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Abhishek-Mallick** [comment]
could you please assign this to me?

**Comment by sr2005roy** [comment]
@tobySolutions I would like to work on this project. Kindly assign me

**Comment by tobySolutions** [comment]
Hey @Abhishek-Mallick, @sr2005roy; I think @Abhishek-Mallick requested first. Are you still interested @Abhishek-Mallick?

**Comment by Abhishek-Mallick** [comment]
Yes @tobySolutions I will be working on it
Please assign me

**Comment by Judge-Paul** [comment]
@tobySolutions is this issue still up for grabs?

**Comment by Abhishek-Mallick** [comment]
Hey @Judge-Paul  sorry for the delay..I'm working on it will be creating an pull req within a few hrs

**Comment by Abhishek-Mallick** [comment]
Hey @tobySolutions 
Could you please have a look at https://github.com/aidenybai/million/pull/664

**Comment by tobySolutions** [comment]
Gonna get on it soon @Abhishek-Mallick!
