### ISSUE TITLE
Kitchen Sink: Build A Music Playlist Creator

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#626]
Build a music playlist builder with the ability to add, remove, and reorder songs that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by rjangid9080** [comment]
Hey @tobySolutions , Please assign to me

**Comment by tobySolutions** [comment]
Sure thing @rjangid9080!

**Comment by tobySolutions** [comment]
Any updates on this @rjangid9080?

**Comment by tobySolutions** [comment]
Any updates on this, @rjangid9080? I might need to close this soon.

**Comment by rjangid9080** [comment]
Hi @tobySolutions, I have been inactive for a month and might continue to be in the coming days. Please assign this task to other contributors so they can contribute.

**Comment by pritipsingh** [comment]
Hey @tobySolutions can I take this up?

**Comment by pritipsingh** [comment]
Thanks @tobySolutions just wanted to understand, do you expect them to add from Spotify and fetch it from Spotify or it would just be a link to songs with the ability to add , delete & shuffle songs?
