### ISSUE TITLE
Kitchen Sink: Build A QR Code Generator:

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#627]
Build a QR code generator that converts text or URLs into QR codes that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by Abhishek-Mallick** [comment]
could you please assign this to me?
