### ISSUE TITLE
Kitchen Sink: Build A Book Recommendation App

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#628]
Develop an app that recommends books based on user preferences that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by adetyaz** [comment]
Please, Can I work on this?

**Comment by arunavabasu-03** [comment]
can you assign it to me ?

**Comment by rakshixh** [comment]
Hey @tobySolutions I would like to work on this issue, Please assign me this, Thank you!

**Comment by tobySolutions** [comment]
Hello folks @adetyaz, @arunavabasu-03, @rakshixh! I think @adetyaz requested first. Are you still interested in this @adetyaz?

**Comment by adetyaz** [comment]
Yes I am

**Comment by tobySolutions** [comment]
Awesome! All yours @adetyaz!

**Comment by adetyaz** [comment]
💪🏾 thanks

**Comment by tobySolutions** [comment]
Hey there @adetyaz; any updates on this?

**Comment by adetyaz** [comment]
I'm working on it @tobySolutions

**Comment by tobySolutions** [comment]
Awesome @adetyaz!

**Comment by tobySolutions** [comment]
Any updates @adetyaz?

**Comment by adetyaz** [comment]
Yes, by this time tomorrow I would have made a pr @tobySolutions
