### ISSUE TITLE
Kitchen Sink: Build A Guestbook

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#630]
Build a guestbook application where visitors can leave comments or messages, which are displayed in a list that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md 

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by adhirajkar3103** [comment]
Can I contribute and solve this issue?

**Comment by tobySolutions** [comment]
> Can I contribute and solve this issue?

Awesome! Sure thing, go ahead!

**Comment by adhirajkar3103** [comment]
Hello @tobySolutions 
Should i use state management library or local storage so that the info stays after refreshing  or should I use normal state using useState?
Thank you!

**Comment by tobySolutions** [comment]
> Hello @tobySolutions 
> Should i use state management library or local storage so that the info stays after refreshing  or should I use normal state using useState?
> Thank you!

Hey there! I think anything you use works, you can go ahead to use anything you deem fit. 


You gotta Millionify it though haha 😅

**Comment by tobySolutions** [comment]
Awesome! Good job @adhirajkar3103, I'll check it out now.

**Comment by tobySolutions** [comment]
fixed by #633
