### ISSUE TITLE
Hover & Focus state for Social Icons

### ISSUE THREAD

**Issue by vatsalsinghkv** [aidenybai/million#634]
### Describe the feature

Right now the social icons do not have any hover or focus state which is not a good user experience and it's not consistent with the rest of the website.

I'd like to implement this feature where Hovering & Focusing on Social Icons change their colour to the `accent` (purple) colour.

#### Before (on Hover):
<img width="556" alt="Screenshot 2023-10-02 at 4 04 15 PM" src="https://github.com/aidenybai/million/assets/68834718/cb4e28ec-6491-4075-9811-422bc4b95f9f">

#### After (on Hover):
<img width="552" alt="Screenshot 2023-10-02 at 4 04 06 PM" src="https://github.com/aidenybai/million/assets/68834718/aa19715f-68b8-4b18-be97-8e76e41a5c79">

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by adetyaz** [comment]
Hey, please can I work on this?

**Comment by jasonetorres** [comment]
I see someone already claimed but I’ll take it if they moved on!

**Comment by adetyaz** [comment]
@jasonetorres I still want to work on it, I was waiting for a confirmation.

**Comment by jasonetorres** [comment]
No worries

**Comment by tobySolutions** [comment]
Hey thanks for coming on here @jasonetorres; how are you man???!! Of course @adetyaz, you can go ahead. I'll assign you now.

**Comment by adetyaz** [comment]
Thanks @tobySolutions

**Comment by tobySolutions** [comment]
Fixed by #536

**Comment by tobySolutions** [comment]
Fixed by #670
