### ISSUE TITLE
Kitchen Sink: Build A Snake Game

### ISSUE THREAD

**Issue by sr2005roy** [aidenybai/million#638]
### Describe the feature

I would like to develop a Snake game and incorporate it into this repository. The game will display the player's score as well as the highest score achieved in previous games.
could you kindly assign this issue to me under the hactoberfest label.

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing! @sr2005roy. Your PR for the game has to include your usage of Million though 😁

**Comment by sr2005roy** [comment]
sure i will include Million js, @tobySolutions can you please assign me the issue under hactoberfest label.

**Comment by sr2005roy** [comment]
I have made a PR of my previous task in the repo. Can you assign me this issue, so that I can start working on it :)

**Comment by sr2005roy** [comment]
@tobySolutions can you plese check the PR.

**Comment by tobySolutions** [comment]
Awesome! Gonna review the PR soon @sr2005roy; amazing work!

**Comment by sr2005roy** [comment]
@tobySolutions can you please check the PR
:)

**Comment by sr2005roy** [comment]
@tobySolutions can you please check the PR: [added Snake Game #738](https://github.com/aidenybai/million/pull/738)
:)
