### ISSUE TITLE
VFlag Import Undefined

### ISSUE THREAD

**Issue by joselevelsup** [aidenybai/million#64]
**Describe the bug**
Importing VFlags leads to import errors with Webpack

**Expected behavior**
Just being able to import VFlags from Millionjs to use with `m` function

**Screenshots**
![image](https://user-images.githubusercontent.com/10066172/124840562-45bc8c00-df59-11eb-86a9-3930b04c3433.png)

**Desktop (please complete the following information):**

- OS: Manjaro 
- Browser: Firefox

**Comment by aidenybai** [comment]
Can you provide more context? Are other methods accessible? Can you send your setup?

**Comment by joselevelsup** [comment]
So far, all the other methods have been accessible (Mostly the `m` and `createElement` functions since I've been just using those the most) It seems like I just can't access the VFlags Enum. 
The project that I am using Million with is [here](https://github.com/joselevelsup/codename-scattered-stars)
As for my setup, you can go to the root of my project. Its using Webpack.

**Comment by aidenybai** [comment]
Try taking a look at this: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**Comment by joselevelsup** [comment]
I'm confused. I'm trying to use the value of the Enum not use it as a type.

**Comment by aidenybai** [comment]
Enums are a typescript only feature, meaning that you'll have to import it that way I believe.

**Comment by joselevelsup** [comment]
You don't have to import/export enums that way. If you were only going to use enums only as a type, then that would make sense. 
I have custom enums setup in this project and I import them as a regular exported enum and I'm able to access their values. An example [here](https://github.com/joselevelsup/codename-scattered-stars/blob/main/src/utils/index.ts).
The array `supplyList` uses the enum `InventoryItemTypes` values to categorize the item type.

**Comment by aidenybai** [comment]
I think if you write your own enums in your own project you can just import it directly and do as you please, but I believe for libraries (when using a bundler) it's a bit different.

At least in my vite setup (I'm not sure about webpack), I need to import with the `type` keyword. I'm assuming this needs to happen to hint to the bundler to check the type declarations file rather than the actual exports (which are just javascript and don't actually export typess)

**Comment by aidenybai** [comment]
You can see in the bundle at LOC 91 https://unpkg.com/browse/million@0.2.2/dist/million.umd.js

But in the type declaration bundle it is exported LOC 14 https://unpkg.com/browse/million@0.2.2/dist/million.d.ts

**Comment by aidenybai** [comment]
I'll look into this and get back to with a solution once I find one

**Comment by aidenybai** [comment]
@joselevelsup Fixed in [v0.2.3](https://github.com/aidenybai/million/releases/tag/v0.2.3). I recommend checking the new docs for clarifications on VFlags

**Comment by joselevelsup** [comment]
Awesome! I'll take a look when I can. Thank you for looking at this.
