### ISSUE TITLE
Kitchen Sink : Etch-A-Sketch

### ISSUE THREAD

**Issue by sukritmalpani** [aidenybai/million#650]
### Describe the feature

I want to add an Etch-A-Sketch Component,a sketching application in pixelated form.The user can select any color from color palatte and can even generate random colors.Can you please assign this issue to me under the hacktoberfest label?

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Awesome! Go ahead!

**Comment by tobySolutions** [comment]
Fixed by #682
