### ISSUE TITLE
Kitchen Sink: Development of  Quiz Website with API Integration

### ISSUE THREAD

**Issue by BikramNarayan** [aidenybai/million#654]
### Describe the feature

I'd like to propose an issue for the development of a  quiz website that integrates with an API.
Pls assign this issue to me.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hmm, sure thing!

**Comment by tobySolutions** [comment]
Make sure to use Million.js though 😁

**Comment by tobySolutions** [comment]
Hey there @BikramNarayan; any updates on this?

**Comment by tobySolutions** [comment]
Hey there @BikramNarayan, any updates on this? I might need to close this soon.
