### ISSUE TITLE
Whack-a-mole game

### ISSUE THREAD

**Issue by Yash9276** [aidenybai/million#658]
### Describe the feature

Whack-a-Mole is a simple and fun  game where you have a board with holes, and little creatures (moles) pop up randomly from these holes. Your job is to quickly hit (whack) each mole back into its hole with a mallet before it disappears.
The goal is to get the highest score possible by whacking as many moles as you can within a set time limit.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Yash9276** [comment]
Please assign this issue under hacktoberfest tag 
I will make this game using million library
Thank you :)

**Comment by tobySolutions** [comment]
Yeah, sure thing!

**Comment by tobySolutions** [comment]
All yours, Yash!

**Comment by Yash9276** [comment]
Please assign this issue to me
Thank you:)

**Comment by tobySolutions** [comment]
Awesome stuff! Hey there @Yash9276; any updates on this?

**Comment by tobySolutions** [comment]
Any updates on this @Yash9276? I might need to close this soon.
