### ISSUE TITLE
Speech_detecting

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [aidenybai/million#659]
### Describe the feature

I want to make speech_detector ,

When user speaks , some thing his speech is translated into words and that words are displayed dynamically on the notebook which is build with beautiful UI .

Please assign this to me , I want to contribute myself In hacktoberfest_23 : )

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Bharath-KumarReddy** [comment]
I just now resolved this issue and i made a PR #693 once please check it and merge it , kindly inform for further modifications _hacktoberfest_23 : )

**Comment by Bharath-KumarReddy** [comment]
I made A PR again but this time with better UI and functionalities but it is getting error
Can you please say why it is getting error  ,
![image](https://github.com/aidenybai/million/assets/127650446/83ffe5cf-ac11-4a94-aae3-b2cd908627d8)

**Comment by Timonwa** [comment]
This is happening because the sink app failed to build. You can run the build script on your local repo to view the errors in your terminal to fix them. Then try again

**Comment by tobySolutions** [comment]
Hey there @Bharath-KumarReddy; have you been able to resolve the issues? Any updates?

**Comment by Bharath-KumarReddy** [comment]
Yes , I resolved this issue and I made a PR #736 once please check : )

**Comment by tobySolutions** [comment]
I left some reviews on your PR @Bharath-KumarReddy. Can you please check them out? Thanks.
