### ISSUE TITLE
Voice assistant to chatgpt kind of AI

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [aidenybai/million#660]
### Describe the feature

I want to work on Voice assistant to chatGpt Kind of AI

Like instaed of typing every time we can use our assistant so that it can listen  to our words and it will generate the response 
and it will also read the response for us .

Can you assign this to me  , I want to participate myself in hacktoberfest_23 : )

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Awesome! Sure thing, go ahead and work on this. It's all yours.

**Comment by tobySolutions** [comment]
Hey there @Bharath-KumarReddy; any updates on this issue?

**Comment by Bharath-KumarReddy** [comment]
Yes , I had done with chatgpt but now adding voice assistant is some what takes time , I need to explore on voice assistant .

![Chatgpt __](https://github.com/aidenybai/million/assets/127650446/6e80f521-0a68-444b-bff8-ee4818030327)

**Comment by tobySolutions** [comment]
Hmm, oh ok no problem @Bharath-KumarReddy; take your time.

**Comment by tobySolutions** [comment]
Awesome work so far @Bharath-KumarReddy. Any updates so far?
