### ISSUE TITLE
Kitchen Sink: Type Racing Game

### ISSUE THREAD

**Issue by izruff** [aidenybai/million#663]
### Describe the feature

I would like to create a single-player type racing game, where the user has to maintain a positive HP by quickly typing each sentence appearing on the screen. The HP is constantly depleting, and each time a sentence is completed it depletes faster. Each sentence is generated by an API (e.g. [this](https://github.com/lukePeavey/quotable)) and each completed sentence adds the HP by a certain amount.

Please assign this to me under the hacktoberfest label. Thank you! :)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hmm, interesting. This sounds like something interesting that can be added to the kitchen sink. Thank you. I'll assign this to you now.

**Comment by tobySolutions** [comment]
Hey there @izruff; any updates on this?

**Comment by izruff** [comment]
Hi @tobySolutions, thanks for reaching out. I was busy for the past few days so I did not have much time, I will try to work on this again today!

**Comment by tobySolutions** [comment]
> Hi @tobySolutions, thanks for reaching out. I was busy for the past few days so I did not have much time, I will try to work on this again today!

Of course, no problem at all. It's totally fine!
