### ISSUE TITLE
Kitchen Sink : Github User Search

### ISSUE THREAD

**Issue by capsy14** [aidenybai/million#668]
### Describe the feature

I would like to contribute to this repository by creating a Github-user-search application using the Million.js library.
This application will provide a simple and efficient way to search users on github and get their details such as followers ,etc.
**Could you please assign this issue to me:)**

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hmm, go ahead @capsy14! All yours!
