### ISSUE TITLE
Kitchen Sink : Virtual Dice Roller

### ISSUE THREAD

**Issue by UzairNoman** [aidenybai/million#672]
### Describe the feature

This app will roll a die for board games or decision-making.

Please assign this to me, I want to participate in hacktoberfest_23 : )

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by sr2005roy** [comment]
@Timonwa @tobySolutions Is this task open for contribution ??
if so please assign it to me :)

**Comment by tobySolutions** [comment]
Hey, I think @UzairNoman wants to work on it.
