### ISSUE TITLE
Kitchen Sink : Mortgage Calculator App

### ISSUE THREAD

**Issue by UzairNoman** [aidenybai/million#673]
### Describe the feature

This app will calculate monthly payments need to be made for mortgage.

Please assign this to me , I want to participate in hacktoberfest_23 : )

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Timonwa** [comment]
Hi @UzairNoman. Thank you for wanting to contribute to Million. You can go ahead with working on this issue. Do not forget to implement Million in your project.

**Comment by Timonwa** [comment]
I can see that you opens 2 other issues: #672 and #671. Please ensure that you only open one PR per issue. This will make it easy for us to review.

**Comment by UzairNoman** [comment]
Yes yes, Each PR will have single feature only. Thanks for reiterating :)

**Comment by tobySolutions** [comment]
Hmm, oh ok. I'll come back to review this soon.

**Comment by UzairNoman** [comment]
Blocker by issue #680 since it would also have a reset button functionality.

**Comment by tobySolutions** [comment]
Hmm, I'm really sorry about this blocker @UzairNoman; to clariify, are you still experiencing this issue though?

**Comment by tobySolutions** [comment]
Any updates on this @UzairNoman, were you able to find a resolution or a workaround?

**Comment by UzairNoman** [comment]
> Any updates on this @UzairNoman, were you able to find a resolution or a workaround?

Yes, I was able to do this one with million.js and reset button wasn't necessary for this one. You can merge it.
