### ISSUE TITLE
Kitchen Sink: Development of Hangman game

### ISSUE THREAD

**Issue by ANKITy102** [aidenybai/million#675]
### Describe the feature

I would like to develop Hangman game using Million.js.

**Below is the description of the game:**

- Ask a question related to a word and let the user guess it.
- Limit users to a certain number of wrong guesses.
- Display parts of a hangman figure for each incorrect guess.
- If the hangman figure is fully formed, the user loses.

**Could you please assign me this issue?**

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Thanks @Timonwa!

**Comment by tobySolutions** [comment]
Fixed by #683
