### ISSUE TITLE
Kitchen Sink : 2048 Game

### ISSUE THREAD

**Issue by cyberviking5** [aidenybai/million#686]
### Describe the feature

2048 is a single-player sliding block puzzle game designed by Italian web developer Gabriele Cirulli. The game’s objective is to slide numbered tiles on a grid to combine them to create a tile with the number 2048. However, one can continue to play the game after reaching the goal, creating tiles with larger numbers.

I will be using Million.js to make it  :)
Please assign me this issue under hacktoberfest tag  :)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing @cyberviking5! Go ahead.

**Comment by tobySolutions** [comment]
Any updates on this @cyberviking5?

**Comment by tobySolutions** [comment]
Any updates @cyberviking5? I might need to close this soon though.
