### ISSUE TITLE
Kitchen Sink : 15-Puzzle Game

### ISSUE THREAD

**Issue by sukritmalpani** [aidenybai/million#688]
### Describe the feature

This is a puzzle game where user has to arrange 15 numbers in order in a 4x4 grid.I would like to implement this feature and make it millionified.Can you please assign me this issue under the label of hacktoberfest.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing @sukritmalpani! It's all yours!

**Comment by tobySolutions** [comment]
Anny updates on this @sukritmalpani?

**Comment by sukritmalpani** [comment]
I have already posted a pull request,but it seems that you have closed my pull request before merging.
