### ISSUE TITLE
Kitchen Sink : Development of Sudoku Puzzle

### ISSUE THREAD

**Issue by ANKITy102** [aidenybai/million#690]
### Describe the feature

I would like to develop the Sudoku and add to this repository.

- The Sudoku puzzle should follow standard rules, including a 9x9 grid divided into 3x3 subgrids.
- Implement a random Sudoku generator to provide unique puzzles for each session.
- Ensure the puzzle is solvable and has a single valid solution.
- Allow users to fill in cells with numbers and provide feedback on correctness.
- Include options for checking the puzzle's progress and solving it.
- Add a timer to track the time spent on solving the Sudoku puzzle.
- Include a scoring system or rewards for completing puzzles within certain time limits.
- Integrate visually appealing graphics and user-friendly controls for Sudoku interaction.

Could you please assign me this issue?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing @ANKITy102! The issue is all yours.

**Comment by tobySolutions** [comment]
Awesome work @ANKITy102; gonna review your PR soon. I think I left some comments on there though.

**Comment by tobySolutions** [comment]
Hey there @ANKITy102, have you applied the updates, yet? 😁

**Comment by ANKITy102** [comment]
@tobySolutions could you review my pr?
I have done necessary changes and fixed the styling issues.
