### ISSUE TITLE
Kitchen Sink - Interactive Card Game

### ISSUE THREAD

**Issue by onlybond** [aidenybai/million#701]
### Title:
Add Interactive Card Game Feature

### Description:
I suggest adding an interactive card game feature to the application. This feature would involve a card game where users can shuffle and interact with cards.

can you please assign me this Issue??

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Awesome! Go ahead!

**Comment by tobySolutions** [comment]
Awesome! Gonna review your PR soon.

**Comment by tobySolutions** [comment]
Fixed by #729
