### ISSUE TITLE
Kitchen sink: a movie finder app 

### ISSUE THREAD

**Issue by ForJessicaSake** [aidenybai/million#702]

**Comment by ForJessicaSake** [comment]
Hi @tobySolutions I would like to work on this issue can you please assign this to me?

**Comment by tobySolutions** [comment]
Hey there @ForJessicaSake! It's all yours

**Comment by ForJessicaSake** [comment]
thanks

**Comment by tobySolutions** [comment]
> thanks

My pleasure Jessica. Can you maybe check my latest comment on your PR?
