### ISSUE TITLE
Kitchen sink : 3D Tshirt designer

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [aidenybai/million#712]
### Describe the feature

I want to Add 3D Tshirt Designer , user can create his own tshirt based on his interest and he can choose different colors .,he can design.

This can be build using three.js 

can you please assign this to me , I am interested to participate myself in hacktoberfest_23 : )

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Amazing! Go ahead @Bharath-KumarReddy!

**Comment by tobySolutions** [comment]
Any updates on this @Bharath-KumarReddy?
