### ISSUE TITLE
Kitchen sink : Complete wikipedia_website    Browse as your wish

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [aidenybai/million#714]
### Describe the feature

Wikipedia , User can browse any thing and he will get his response based on  his search .

for example---

![image](https://github.com/aidenybai/million/assets/127650446/13387672-d873-4936-b203-db0ddfff51fe)

can you please assign this to me , I am interested to contribute myself In hacktoberfest_23 : )

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Any updates on this @Bharath-KumarReddy?
