### ISSUE TITLE
Kitchen Sink : Pokemon App

### ISSUE THREAD

**Issue by sushilmagare10** [aidenybai/million#718]
### Describe the feature

This app will show all the pokemons and their stats and Evolutions.

Please assign me this for the **hacktoberfest_2023**

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Go ahead @sushilmagare10!

**Comment by tobySolutions** [comment]
Any updates on this @sushilmagare10?
