### ISSUE TITLE
`browser` field has higher priority than `module`

### ISSUE THREAD

**Issue by hyrious** [aidenybai/million#72]
**Describe the bug**
The package.json is wrong. `browser` field is not only can be used to tell cdn to use this file, but also tells bundlers (webpack, rollup, etc.) to use it over the `module` one.

- [See webpack prefers `browser` over `module`](https://webpack.js.org/configuration/resolve/#resolvemainfields).
- [Esbuild the same](https://esbuild.github.io/api/#main-fields).

This prevents bundlers to use the esm file. The `browser` field is to create dual modules which both supports node.js and browser but need a bit different code.

You can checkout [axios](https://cdn.jsdelivr.net/npm/axios@0.21.1/package.json) for an example, which is not `m` have to worry about since it can only run on the browser.

The correct package.json should be:

```json
  "main": "dist/million.umd.js",
  "module": "dist/million.esm.js",
  "jsdelivr": "dist/million.min.js",
  "unpkg": "dist/million.min.js",
  "types": "dist/million.d.ts",
  "exports": {
    "require": "./dist/million.umd.js",
    "import": "./dist/million.esm.js"
  },
```

**Comment by aidenybai** [comment]
Thanks for the information and educating me, this was very helpful. I'll push out a new patch release fixing this issue.
