### ISSUE TITLE
Kitchen Sink : Paragraph Summrizer 

### ISSUE THREAD

**Issue by sushilmagare10** [aidenybai/million#720]
### Describe the feature

This App will take a Long Paragraph and Summerize it iin smaller paragraph, It will use OpenAI api to achieve.

Assign me this for  **Hacktoberfest_2023**

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Awesome! Sure thing, go ahead @sushilmagare10.

**Comment by tobySolutions** [comment]
Any updates on this @sushilmagare10?

**Comment by sushilmagare10** [comment]
i have updated it with the same branch @tobySolutions
