### ISSUE TITLE
Kitchen Sink : Development of a Minesweeper Game

### ISSUE THREAD

**Issue by neelesh133** [aidenybai/million#724]
### Describe the feature

**Describe the feature** -
 I would like to develop the Minesweeper game and add it to this repository.

- The minesweeper game follows standard rules, with a grid of your choice (max: 18 x 18).
- Implement a random generator for mines and blank squares on the grid area.
- Ensure the game is winnable and has an outcome every game.
- Allow users to check the grids and specify them whether its a mine or not through small image.
- Add a field to specify the number of mines to be spawned in each game with it's counter during game.
- Integrate visually appealing graphics and user-friendly controls for this minesweeper game.

Could you please assign me this issue?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Yeah, sure go ahead!
