### ISSUE TITLE
Website: Theme Of Website Flashes And Changes From Light To Dark Mode

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#726]
The theme of the website begins from light mode and changes to dark mode on page load and this might be related to a Nextjs thing. I have done the below screen recording to show the issue:

https://github.com/aidenybai/million/assets/96334363/e3437016-44ac-465a-bb9c-f9b5b68e166b

Check out https://million.dev

**Comment by akshayw1** [comment]
@tobySolutions  Could you Pls assign me this issue, Looking forward to work on these on issue.

**Comment by tobySolutions** [comment]
All yours @akshayw1!

**Comment by akshayw1** [comment]
I have started working on the issue please assign

**Comment by nraychaudhuri** [comment]
@tobySolutions Hey Tobi, I would like to give this one a go. Let me explore and I will update here my findings

**Comment by akshayw1** [comment]
I have started working on the issue please assign

**Comment by tobySolutions** [comment]
Awesome! All yours @akshayw1.

**Comment by akshayw1** [comment]
@tobySolutions Is there any guide to setup website on local, As I have found what the solution just need to implement it

**Comment by Keith-Web3** [comment]
Hey @akshayw1, any update on this?

**Comment by Devanshukoli** [comment]
Hey! In this issue, When I try to visit the site again and again. Then it does light to dark. But also I noticed that in below page, my pc shows, **system**, Meaning it is automatically taking **system** theme.

does anyone happenings like this ?

**Comment by tobySolutions** [comment]
Hmm, yeah @Devanshukoli; you can actually switch the theme though.

**Comment by tobySolutions** [comment]
> @tobySolutions Is there any guide to setup website on local, As I have found what the solution just need to implement it

Hey there Akshay, were you able to set it up? Also, can you maybe share your solution?

**Comment by rishi-raj-jain** [comment]
@tobySolutions 

What's the

- Default value we wanna go with: system, dark or light?
- Do we wanna persist across localStorage or sessionStorage?

**Comment by rishi-raj-jain** [comment]
https://github.com/pacocoursey/next-themes is to the rescue here I believe.

**Comment by tobySolutions** [comment]
> @tobySolutions
> 
> What's the
> 
> * Default value we wanna go with: system, dark or light?
> * Do we wanna persist across localStorage or sessionStorage?

- System should be the default here @rishi-raj-jain 
- Localstorage should be persisted yes, I think

**Comment by tobySolutions** [comment]
> https://github.com/pacocoursey/next-themes is to the rescue here I believe.

Hmm, can you show a demo or something. I'm trying to see if there are any implications with Nextra.

**Comment by tobySolutions** [comment]
> > https://github.com/pacocoursey/next-themes is to the rescue here I believe.
> 
> Hmm, can you show a demo or something?  I'm trying to see if there are any implications with Nextra.

**Comment by tobySolutions** [comment]
> > > https://github.com/pacocoursey/next-themes is to the rescue here I believe.
> > 
> > 
 Hmm, can you show a demo or something?  I'm trying to see if there are any implications with Nextra.

**Comment by rishi-raj-jain** [comment]
I think Nextra shall already be using it. Let me try to make a PR

**Comment by rishi-raj-jain** [comment]
@tobySolutions How to setup website locally?

**Comment by tobySolutions** [comment]
> I think Nextra shall already be using it. Let me try to make a PR

Hmm, oh ok awesome. Thanks.

**Comment by tobySolutions** [comment]
> @tobySolutions How to setup website locally?

Can we jump on a call or you can just cd to website after cloning Million and installing dependencies. You can  then `npm run dev`

**Comment by rishi-raj-jain** [comment]
@tobySolutions Yes, happy to jump on a call

**Comment by rishi-raj-jain** [comment]
https://cal.com/rishi-raj-jain/15min

**Comment by tobySolutions** [comment]
> @tobySolutions Yes, happy to jump on a call

Awesome! So, Discord or Google meet? I'll dm you with a link now.

**Comment by rishi-raj-jain** [comment]
https://meet.google.com/zau-nrbj-tvz?authuser=0
