### ISSUE TITLE
Kitchen Sink : House selling website

### ISSUE THREAD

**Issue by bhanuSingh10** [aidenybai/million#732]
### Describe the feature

I would like to contribute to this repository by creating a House-selling-website frontend application using the Million.js library.
This application will provide a simple and efficient way to the users for buy and selling houses .
Could you please assign this issue to me :) 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hey there! Of course, the issue is all yours! Go ahead @bhanuSingh10
