### ISSUE TITLE
Kitchen Sink: Mac OS UI clone 

### ISSUE THREAD

**Issue by IamSAL** [aidenybai/million#735]
**Describe the feature:**

Mac OS widget editor clone.

A complex app that has the following functionalities:
- Drag and drop (copy & move)
- Search
- Animating each state using framer motion.
- Heavy DOM manipulation
- Using million to enhance smoothness.

**Live Link:** [Check out the live link here (desktop view only)](https://gmac.vercel.app/)

**Source**(I'll modify and export default as  react component to match sink examples): [usage of million](https://github.com/IamSAL/goriberMac/blob/main/next.config.js)

![Screenshot Image](https://pasteimg.com/images/2023/10/13/Screenshot-at-Oct-13-14-45-52.png)

## Additional Information

Please check the box if you are willing to help implement this feature.

- [x] I am willing to contribute to the implementation of this feature.

if approved, please assign me this under hacktoberfest label.

**Comment by tobySolutions** [comment]
Sure thing @IamSAL, the issue is all yours!
