### ISSUE TITLE
Kitchen Sink: Age Calculator

### ISSUE THREAD

**Issue by chukwuani** [aidenybai/million#743]
### Describe the feature

I'd like to add an age calculator feature to the GitHub repository. This feature will allow users to input a date of birth, and it will calculate and display the person's age in years, months, and days. 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Awesome! Go ahead boss!

**Comment by chukwuani** [comment]
Alright Tobi 👍

**Comment by tobySolutions** [comment]
Awesome @chukwuani.
