### ISSUE TITLE
Kitchen Sink: Count Down Timer

### ISSUE THREAD

**Issue by rakshixh** [aidenybai/million#751]
### Describe the feature

I would like to add the **Count Down Timer** that counts down to a specific time in the format of **Hours: Minutes: Seconds: Milli Seconds**.

For example:

- It will take input for **Hours and Minutes** from the user.
- Output will be in the format of **00: 00: 00: 00**

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by Vince-arch** [comment]
Kindly assign this to me.

**Comment by rakshixh** [comment]
Hey @Vince-arch I was the first person to open this issue and I'm also willing to contribute to this. 

Hey, @tobySolutions please go through the issue and assign it to me. Thank you!

**Comment by Vince-arch** [comment]
Sorry I'm new to open source I didn't mean to infringe.

**Comment by rakshixh** [comment]
Hey, @tobySolutions please go through the issue and assign it to me. Thank you!

**Comment by tobySolutions** [comment]
Hey there @rakshixh, please go ahead. Thanks!

**Comment by rakshixh** [comment]
#767 @tobySolutions Please check with this Pull request.

**Comment by rakshixh** [comment]
Hey @tobySolutions please check with PR #807 I have updated the file. and there are no merge conflicts. Also once it is reviewed please close this issue too. Thank you!
