### ISSUE TITLE
Kitchen Sink: BMI Calculator

### ISSUE THREAD

**Issue by rakshixh** [aidenybai/million#752]
### Describe the feature

I would like to implement the **BMI Calculator** feature!

- It will take inputs of **Age, Gender, Height, and Weight** from the user.
- Based on the input from the user it will calculate and display **BMI** along with **labels** such as **Underweight, Normal, Overweight, etc**

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by rakshixh** [comment]
Hey. @tobySolutions Please assign this issue to me. Thank you!

**Comment by tobySolutions** [comment]
Awesome @rakshixh, go ahead!

**Comment by rakshixh** [comment]
#768 Sent PR for this. Please check it.

**Comment by rakshixh** [comment]
Hey @tobySolutions Please review the PR and merge it. Thank you!
#768
