### ISSUE TITLE
Kitchen Sink: Morse Code Translator

### ISSUE THREAD

**Issue by rakshixh** [aidenybai/million#753]
### Describe the feature

I would like to implement the **Morse Code Translator** feature!

- It will take input of **Text or Morse Code** from the user.
- If the user has entered **Text**, then it will translate it into **Morse Code**. Same way if the user has entered **Morse Code**, then it will translate it into **Text**.
- Also there will be a button to **display the Morse Code Guide**.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by rakshixh** [comment]
Hey. @tobySolutions Please assign this issue to me. Thank you!

**Comment by tobySolutions** [comment]
Sure thing @rakshixh! Go ahead please

**Comment by rakshixh** [comment]
Hey @tobySolutions please review the PR and merge it. Thank you!
#772

**Comment by rakshixh** [comment]
Hey @tobySolutions please close this issue since it is resolved. Thank you!
