### ISSUE TITLE
TypeError: Illegal invocation, The above error occurred in the <Effect> component

### ISSUE THREAD

**Issue by NishilSB** [aidenybai/million#757]
### What version of `million` are you using?

2.6.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/aidenybai/million/assets/18629343/d58bb80f-a718-4323-9fe5-043201e743c2)

### What's the expected result?

App should build/run successfully

### Link to Minimal Reproducible Example

https://codesandbox.io/s/kind-bush-94kxkn?file=/src/App.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
This issue depends on #488

**Comment by tobySolutions** [comment]
Thanks for this @NishilSB.
