### ISSUE TITLE
I was trying to create a UI library on top of million, but there are few bugs.

### ISSUE THREAD

**Issue by abhishekraj272** [aidenybai/million#76]
**Describe the bug**
Can't create element without children

**To Reproduce**
```js
const element = Nimble.createElement(
  "div",
  { id: "foo" },
  Nimble.createElement("a", null, "bar"),
  Nimble.createElement("b")
);
```
Here, Nimble is the wrapper on Million.

**Screenshots**
![image](https://user-images.githubusercontent.com/27128838/125943344-48318b7a-b94c-4e74-a262-0bd0a9b7394e.png)

@aidenybai

**Comment by hyrious** [comment]
You should read the [doc](https://million.js.org/functions/createElement) first.

To create a single tag, example code:

```js
const vnode = Million.m('a') // { tag: 'a' }
const node = Million.createElement(vnode) // <a></a>
document.body.append(node)
```
