### ISSUE TITLE
Kitchen Sink: Jotter App

### ISSUE THREAD

**Issue by Ibukun-tech** [aidenybai/million#760]
### Describe the feature

**Describe Feature.**
I would like to implement the Jotter app feature.

- I would get the text from the user.
- Once it is gotten it will save the text written by the user to the browser.
- Then the user can decide to edit what he or she wrote or delete it later.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Ibukun-tech** [comment]
Yes

**Comment by Ibukun-tech** [comment]
**Sorry I am having this issue while trying**:

pnpm install

its showing me this error 

 ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename 'C:\Users\USER\Desktop\million\node_modules\.pnpm\@tanstack+query-core@4.32.6\node_modules\@tanstack\query-core_tmp_7696' -> 'C:\Users\USER\Desktop\million\node_modules\.pnpm\@tanstack+query-core@4.32.6\node_modules\@tanstack\query-core'
Progress: resolved 1315, reused 339, downloaded 329, added 331

**Comment by tobySolutions** [comment]
> **Sorry I am having this issue while trying**:
> 
> pnpm install
> 
> its showing me this error
> 
>  ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename 'C:\Users\USER\Desktop\million\node_modules.pnpm@tanstack+query-core@4.32.6\node_modules@tanstack\query-core_tmp_7696' -> 'C:\Users\USER\Desktop\million\node_modules.pnpm@tanstack+query-core@4.32.6\node_modules@tanstack\query-core' Progress: resolved 1315, reused 339, downloaded 329, added 331

Are you still getting this @Ibukun-tech? Can you maybe provide a screenshot?

**Comment by Ibukun-tech** [comment]
I was having exams that is why I did not come back to do It?

**Comment by Ibukun-tech** [comment]
Can I still do this
