### ISSUE TITLE
Kitchen Sink: Discount Calculator 

### ISSUE THREAD

**Issue by lalitkumawat1m** [aidenybai/million#761]
### Describe the feature

I would like to implement the Discount Calculator feature!

- It will take inputs of the Original Price and discount (% off) from the user.
- Based on the input from the user it will calculate and display Final Price along with labels such as you save 100 etc.

Hey @tobySolutions Please assign this issue to me under hactoberfest label. Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hey there @lalitkumawat1m; sure thing! You are on a roll though.
