### ISSUE TITLE
Kitchen Sink: Data Converter

### ISSUE THREAD

**Issue by lalitkumawat1m** [aidenybai/million#764]
### Describe the feature

I would like to implement the Discount Calculator feature!

- This app will convert the data value based on user input such as MB to GB etc.

Hey @tobySolutions, Please assign this issue to me under hactoberfest label. Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing @lalitkumawat1m; all yours. I hope you are able to handle them all though.
