### ISSUE TITLE
Kitchen Sink: Investment Calculator

### ISSUE THREAD

**Issue by lalitkumawat1m** [aidenybai/million#765]
### Describe the feature

I would like to implement the Investment Calculator feature!

- It will take inputs of the Total investment amount, interest rate, and duration from the user.
- Based on the input from the user it will calculate and display the Total amount after duration.

Hey @tobySolutions, Please assign this issue to me under hactoberfest label. Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing @lalitkumawat1m; it's all yours!
