### ISSUE TITLE
Kitchen Sink: Temperature Converter

### ISSUE THREAD

**Issue by lalitkumawat1m** [aidenybai/million#766]
### Describe the feature

I would like to implement the Temperature Converter feature!

- This app will convert the temperature value based on user input such as Celsius to Fahrenheit etc.

Hey @tobySolutions, Please assign this issue to me under the hactoberfest label. Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Sure thing! Assigning this to you now.
