### ISSUE TITLE
Kitchen Sink : Dragon game

### ISSUE THREAD

**Issue by akshayw1** [aidenybai/million#769]
### Describe the feature

Dragon game is endless runner genre, where players control a character (in this case, a dragon) that automatically moves forward, and the player's task is to make the character jump over obstacles to avoid collisions.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hey @akshayw1, I'm gonna review your PR soon; I'm gonna assign you this issue now.
