### ISSUE TITLE
Kitchen Sink : Number Guessing

### ISSUE THREAD

**Issue by sukritmalpani** [aidenybai/million#771]
### Describe the feature

In this game a random number will be generated and the user has to guess the number in minimum number of turns.The user will be given hints whether the number is greater or lesser than the guessed number.Can you please assign me to implement this feature under the label of hacktoberfest.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Youngemmy5956** [comment]
hacktoberfest

Number Guessing #771

Sent a PR on this..

**Comment by tobySolutions** [comment]
Awesome! Assigning you now @Youngemmy5956!

**Comment by sukritmalpani** [comment]
@tobySolutions I think you have mistakenly assigned someone else this issue.I have already asked for this issue and have built it and is almost ready.Can you please assign me this issue.

**Comment by tobySolutions** [comment]
Sure thing @sukritmalpani, sorry; my bad.
