### ISSUE TITLE
Kitchen Sink: Develop a News displaying website

### ISSUE THREAD

**Issue by neelesh133** [aidenybai/million#773]
### Describe the feature

**A website to display current news from various sources and different categories.**

- Displays current news on various categories such as general, sports, technology ,etc.
- Have a button to read more on a particular headline.
- Update displayed news periodically.
- Add interactive styling and user-friendly navigations.

Could you please assign me this issue?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Hey there @neelesh133, go ahead!
