### ISSUE TITLE
Theme switch on load.

### ISSUE THREAD

**Issue by Keith-Web3** [aidenybai/million#793]
### Describe the feature

Currently, the site's theme is always on "light" when the website is initially opened and then switches to the user's choice after the website has loaded. This could easily go unnoticed but it would be a nice UX if the theme could be set to the user's preference immediately the site is open rather than switching when the site is loaded.

### Additional information

- [X] Would you be willing to help implement this feature?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/aidenybai) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/aidenybai/million/issues/793">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aidenybai/million/issues/793/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aidenybai/million/issues/793/pledge.svg">
</picture>
</a>

**Comment by tobySolutions** [comment]
Thus issue is linked to #726; can you review that @Keith-Web3?

**Comment by tobySolutions** [comment]
> Alright

Aweome!
