### ISSUE TITLE
Header text getting cut

### ISSUE THREAD

**Issue by Brijesh1963** [aidenybai/million#809]
### What version of `million` are you using?

0.0.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome 

### Describe the Bug

Header text getting cut due to proper responsiveness.

![Screenshot 2023-11-01 203522](https://github.com/aidenybai/million/assets/98037970/7170c257-05b2-4ebc-a96a-9146e85cde74)

### What's the expected result?

Need to show proper header text name "Million"

### Link to Minimal Reproducible Example

https://million.dev/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
What device is this?

**Comment by tobySolutions** [comment]
Do you want to work on this as well?

**Comment by tobySolutions** [comment]
Any updates on this @Brijesh1963?

**Comment by OlaniyanEniola** [comment]
@Brijesh1963, can you give a screenshot, I can't seem to recreate the instance.

**Comment by tobySolutions** [comment]
Hey there @OlaniyanEniola; it's on a Galaxy fold phone.
