### ISSUE TITLE
ReferenceError: require is not defined in Reactjs Ts Vite

### ISSUE THREAD

**Issue by shoaib-blocksdev** [aidenybai/million#819]
### What version of `million` are you using?

^2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

i'm using vite and typescript  getting this error on browser console 

```
Uncaught ReferenceError: require is not defined
    at main.tsx:3:15
```

vite.config.ts

```
import { defineConfig } from 'vite';
import million from 'million/compiler';
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths'
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import path from 'path'

export default defineConfig({
  plugins: [million.vite({ auto: false }),tsconfigPaths({ root: 'src'}),react()],
  server: {
    port: 3000,
  },
  resolve: {
    alias: [
      { find: '@', replacement: path.resolve(__dirname, 'src') },
    ],
  },
});
```

main.tsx file
```

import ReactDOM from 'react-dom/client'
import {RecoilRoot} from 'recoil';

import App from './App'
import './index.scss';
import './styles/App.scss';
import './styles/upgrades.scss';
import Boundary from "./components/Boundary";

ReactDOM.createRoot(document.getElementById('root')!).render(
    <>
        <RecoilRoot>
            <Boundary>
                <App/>
            </Boundary>
        </RecoilRoot>
    </>
)
```

### What's the expected result?

there should be no error in console when adding millionjs in vite.config.ts

### Link to Minimal Reproducible Example

https

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hmm, this is weird. Can you please provide a repro @shoaib-blocksdev.
