### ISSUE TITLE
Misleading warning message: Found unsupported import for block. Make sure blocks are imported from correctly

### ISSUE THREAD

**Issue by afreix-bricks** [aidenybai/million#839]
### What version of `million` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm using storybook. Here is `/.storybook/main.ts`

```
import { TransformOptions } from '@babel/core';
import { config as defaultConfig } from '@databricks/config-storybook';
import type { Configuration } from 'webpack';
import { merge } from 'webpack-merge';
import million from 'million/compiler';

const config = {
  ...defaultConfig,
  babel: (config: TransformOptions) => ({
    ...config,
    presets: [
      ...(config.presets || []),
      [
        '@babel/preset-react',
        {
          runtime: 'automatic',
          importSource: '@emotion/react',
        },
        'unique alias for @babel/preset-react from @emotion/react',
      ],
    ],
    plugins: ['formatjs', '@emotion', ...(config.plugins || [])],
  }),
  webpackFinal: async (rawConfig: Configuration) => {
    const baseConfig = await defaultConfig.webpackFinal(rawConfig);
    const appConfig: Configuration = {
      module: {
        rules: [
          {
            test: /\.css$/,
            use: ['style-loader', 'css-loader'],
          },
        ],
      },
      plugins: [million.webpack({})],
      // Add source map support for production build
      devtool: process.env.NODE_ENV === 'production' ? 'source-map' : 'eval-source-map',
    };

    return merge(baseConfig, appConfig);
  },
};

export default config;
```

The warning message points to a `lodash` import, and I'm not clear why that would be. It appears to be confused

Output from `yarn start:storybook`

<img width="1191" alt="Screenshot 2023-11-21 at 2 09 39 PM" src="https://github.com/aidenybai/million/assets/76451129/91401a42-4f58-49e6-be7a-6eb003b0a245">

### What's the expected result?

Error message points to an import of `block` or an import from `million`

### Link to Minimal Reproducible Example

Not available

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hmm, thanks for this @afreix-bricks; can you maybe provide a repro? Thanks.

**Comment by afreix-bricks** [comment]
I won't be able to provide a repro. This is from a larger project at work. I realize that it makes it quite difficult to resolve

**Comment by tobySolutions** [comment]
Hmm, thanks @afreix-bricks. I'll try to test it out. I can try to bootstrap a simple storybook project

**Comment by Eric-LLi** [comment]
The problem is still there. I created a new project and imported lodash. However, it's still throwing the same error with automatic setup.
https://codesandbox.io/p/devbox/vite-react-forked-3g9xwl

**Comment by tobySolutions** [comment]
> The problem is still there. I created a new project and imported lodash. However, it's still throwing the same error with automatic setup. https://codesandbox.io/p/devbox/vite-react-forked-3g9xwl

Thank you for the above. Much appreciated
