### ISSUE TITLE
Flying cursor in the docs

### ISSUE THREAD

**Issue by NiedziolkaMichal** [aidenybai/million#843]
### What version of `million` are you using?

0.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

None

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Hi,

I was just reading a blog post https://million.dev/blog/million-3 on your page and I have found the flying cursors to be extremely irritating, distructing, annoying. Article wasn't long, but it was quite hard to keep being focused.

### What's the expected result?

Could you please get read of them or at least make them stationary?

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hey there @NiedziolkaMichal, that is actually [Liveblocks](https://liveblocks.io/) in action

**Comment by NiedziolkaMichal** [comment]
@tobySolutions Whatever your relation is with that product, don't you care about accessibility at all? Please, take a look at https://www.accessguide.io/guide/moving-content

**Comment by tobySolutions** [comment]
> @tobySolutions Whatever your relation is with that product, don't you care about accessibility at all? Please, take a look at https://www.accessguide.io/guide/moving-content

We'll look into it. Thank you for this.
