### ISSUE TITLE
(million plugin) Sourcemap is likely to be incorrect 

### ISSUE THREAD

**Issue by issam-seghir** [aidenybai/million#844]
### What version of `million` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome dev version

### Describe the Bug

when active `sourcemap` in vite config , and start `vite build `
there is an error :
 `(million plugin) Sourcemap is likely to be incorrect: a plugin (million) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help`

vite config : 

```js
import million from "million/compiler";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
// import path from "path";
export default defineConfig(({ command, mode, ssrBuild }) => ({
	filenameHashing: true,
	build: {
		sourcemap: true,
	},

	plugins: [
		million.vite({ auto: true }),
		[react()],
                      ],
}));
```

```bash
vite v4.5.1 building for production...
✔ [vite-aliases] - Config: E:/Documents/Vs Code Projects/Web Dev/Portfolio/Shoppy Dashboard/tsconfig.json successfully read!                                                                                             3:16:59 م
ℹ [vite-aliases] - File: Interpreted indentation as (4 spaces) from file tsconfig.json successfully                                                                                                                      3:16:59 م
✔ [vite-aliases] - File: tsconfig.json successfully created                                                                                                                                                              3:16:59 م
transforming (1) index.html
  ⚡ Million.js 2.6.4
  - Tip:     use // million-ignore for errors
  - Hotline: https://million.dev/hotline    
  
(million plugin) Sourcemap is likely to be incorrect: a plugin (million) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

### What's the expected result?

generate sourcemap without any error 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-rhb8ec?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hmm @issam-seghir, the reproduction you provided doesn't actually have this error 🤔

**Comment by mrjvs** [comment]
I'm getting this as well, it seems to happen for every output file. It spams the console quite a lot.

@tobySolutions the minimal reproducable example link does have the warning. But only if you run `npm run build` manually instead of the default command it starts with.

**Comment by tobySolutions** [comment]
This will be fixed in Million 3.0 @mrjvs; thanks for this.

**Comment by mrjvs** [comment]
This bug still happens for us, and can still be reproduced. So don't think it should be closed as stale. :)

**Comment by issam-seghir** [comment]
bot remove stale

**Comment by lxsmnsyc** [comment]
Can you still confirm if this is an issue with the latest version?
