### ISSUE TITLE
bug: Uncaught DOMException: Failed to execute 'replaceChild' on 'Node'

### ISSUE THREAD

**Issue by jalexanderII** [aidenybai/million#848]
```
Uncaught TypeError: Cannot read properties of undefined (reading '__t')
    at Block.p (million.52d69b41.mjs:779:1)
    at ArrayBlock.p (million.52d69b41.mjs:516:1)
    at react.mjs:84:1
```
and 
```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at Block.p (http://localhost:3000/static/js/bundle.js:1078098:29)
    at ArrayBlock.p (http://localhost:3000/static/js/bundle.js:1077859:16)
    at http://localhost:3000/static/js/bundle.js:1077131:67
```

Unable to understand why the error is occurring, this should be the problem code:
```
          if (newValue && typeof newValue === "object" && "foreign" in newValue) {
            const scopeEl = el[TEXT_NODE_CACHE][k];
            if ("unstable" in newValue && oldValue !== newValue) {
              const newScopeEl = newValue.current;
              el[TEXT_NODE_CACHE][k] = newScopeEl;
              replaceChild$.call(el, newScopeEl, scopeEl);
            } else {
              newValue.current = scopeEl;
            }
            continue;
```
inside of class Block. 

I tried to `// million-ignore all` of the functions in the components where the error occurred but the error didn't go away. 

Potential solution, Conditional Replacement: Check if `oldChild` is actually a child of `parentNode` before using `replaceChild`. You can verify with `parentNode.contains(oldChild)`
```
if (parentNode.contains(oldChild)) {
  parentNode.replaceChild(newChild, oldChild);
} else {
  // Handle the case when oldChild is not a child of parentNode
}
```

**Comment by aidenybai** [comment]
Hi can you provide a repro!

**Comment by tobySolutions** [comment]
@jalexanderII, are you there?

**Comment by jalexanderII** [comment]
Hey team. I do not know how to reproduce. I am not sure why this is occurring or what in my code is triggering the problem. All I know is the source of the error from the error message.

**Comment by jalexanderII** [comment]
@tobySolutions & @aidenybai

**Comment by riju-stone** [comment]
I am facing the same issue for my site. Here is the error in console - 
![image](https://github.com/aidenybai/million/assets/24350724/c1b742a2-63cb-49c0-b93c-1bdf2b76ed05)

This is my vite.config.js
![image](https://github.com/aidenybai/million/assets/24350724/8160d7ca-8007-4b5e-8efa-be081de22467)

This is main App.js file
![image](https://github.com/aidenybai/million/assets/24350724/3681f3d8-4cda-4a46-bca1-7a413ddbfb72)

I'm not sure where the error is coming from though. Any help would be highly appreciated.

**Comment by vimalsonara** [comment]
I'm also facing the same issue.
here is the url of StackBlitz repo [https://stackblitz.com/edit/vitejs-vite-ofx7tf?file=package.json](url)

**Comment by tobySolutions** [comment]
> I'm also facing the same issue. I'm rendering same component 4 times, but it's only showing 1 time.
> 
> ![image](https://private-user-images.githubusercontent.com/104844068/298284145-82226d24-644d-40a8-902d-07eb2683020d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA3ODgsIm5iZiI6MTcwNTc2MDQ4OCwicGF0aCI6Ii8xMDQ4NDQwNjgvMjk4Mjg0MTQ1LTgyMjI2ZDI0LTY0NGQtNDBhOC05MDJkLTA3ZWIyNjgzMDIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNDIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmM1YmQyZjNkMzA3YjdkYjY4YjA2M2EzNzcyNDM2MDI0OGFkYWVjYWE2MmFhYTA5ODMyZTY3ZTQ2MGYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rYS796-v-pRjs8vmM4tL1a4JmpXHvncPEIneYZll8PQ)
> 
> sample code url: https://stackblitz.com/edit/vitejs-vite-ofx7tf?file=src%2FApp.tsx

Thanks for the reproduction. I'll definitely check it and get back to you!

**Comment by tobySolutions** [comment]
> > I'm also facing the same issue. I'm rendering same component 4 times, but it's only showing 1 time.
> > ![image](https://private-user-images.githubusercontent.com/104844068/298284145-82226d24-644d-40a8-902d-07eb2683020d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA3ODgsIm5iZiI6MTcwNTc2MDQ4OCwicGF0aCI6Ii8xMDQ4NDQwNjgvMjk4Mjg0MTQ1LTgyMjI2ZDI0LTY0NGQtNDBhOC05MDJkLTA3ZWIyNjgzMDIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNDIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmM1YmQyZjNkMzA3YjdkYjY4YjA2M2EzNzcyNDM2MDI0OGFkYWVjYWE2MmFhYTA5ODMyZTY3ZTQ2MGYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rYS796-v-pRjs8vmM4tL1a4JmpXHvncPEIneYZll8PQ)
> > sample code url: https://stackblitz.com/edit/vitejs-vite-ofx7tf?file=src%2FApp.tsx
> 
> Thanks for the reproduction. I'll definitely check it and get back to you!

Hey there @vimalsonara, so I made tweaks and I used manual mode to make the optimizations for `MonthDaysDisplay`, I had to ignore automatic mode for the `MonthDaysDisplay` component: https://stackblitz.com/edit/vitejs-vite-hjcfai?file=src%2FMonthDaysDisplay.tsx

**Comment by vimalsonara** [comment]
> > > I'm also facing the same issue. I'm rendering same component 4 times, but it's only showing 1 time.
> > > ![image](https://private-user-images.githubusercontent.com/104844068/298284145-82226d24-644d-40a8-902d-07eb2683020d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA3ODgsIm5iZiI6MTcwNTc2MDQ4OCwicGF0aCI6Ii8xMDQ4NDQwNjgvMjk4Mjg0MTQ1LTgyMjI2ZDI0LTY0NGQtNDBhOC05MDJkLTA3ZWIyNjgzMDIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNDIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmM1YmQyZjNkMzA3YjdkYjY4YjA2M2EzNzcyNDM2MDI0OGFkYWVjYWE2MmFhYTA5ODMyZTY3ZTQ2MGYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rYS796-v-pRjs8vmM4tL1a4JmpXHvncPEIneYZll8PQ)
> > > sample code url: https://stackblitz.com/edit/vitejs-vite-ofx7tf?file=src%2FApp.tsx
> > 
> > 
> > Thanks for the reproduction. I'll definitely check it and get back to you!
> 
> Hey there @vimalsonara, so I made tweaks and I used manual mode to make the optimizations for `MonthDaysDisplay`, I had to ignore automatic mode for the `MonthDaysDisplay` component: https://stackblitz.com/edit/vitejs-vite-hjcfai?file=src%2FMonthDaysDisplay.tsx

Thank you @tobySolutions 
It's working now.

**Comment by tobySolutions** [comment]
> > > > I'm also facing the same issue. I'm rendering same component 4 times, but it's only showing 1 time.
> > > > ![image](https://private-user-images.githubusercontent.com/104844068/298284145-82226d24-644d-40a8-902d-07eb2683020d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA3ODgsIm5iZiI6MTcwNTc2MDQ4OCwicGF0aCI6Ii8xMDQ4NDQwNjgvMjk4Mjg0MTQ1LTgyMjI2ZDI0LTY0NGQtNDBhOC05MDJkLTA3ZWIyNjgzMDIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNDIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmM1YmQyZjNkMzA3YjdkYjY4YjA2M2EzNzcyNDM2MDI0OGFkYWVjYWE2MmFhYTA5ODMyZTY3ZTQ2MGYwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rYS796-v-pRjs8vmM4tL1a4JmpXHvncPEIneYZll8PQ)
> > > > sample code url: https://stackblitz.com/edit/vitejs-vite-ofx7tf?file=src%2FApp.tsx
> > > 
> > > 
> > > Thanks for the reproduction. I'll definitely check it and get back to you!
> > 
> > 
> > Hey there @vimalsonara, so I made tweaks and I used manual mode to make the optimizations for `MonthDaysDisplay`, I had to ignore automatic mode for the `MonthDaysDisplay` component: https://stackblitz.com/edit/vitejs-vite-hjcfai?file=src%2FMonthDaysDisplay.tsx
> 
> Thank you @tobySolutions It's working now.

My pleasure @vimalsonara!
