### ISSUE TITLE
Gsap and Million.js

### ISSUE THREAD

**Issue by VeroniDeev** [aidenybai/million#860]
### What version of `million` are you using?

2.5.1

### Are you using an SSR adapter? If so, which one?

Nextjs

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Brave (chromium)

### Describe the Bug

When I have million.js installed on my project I see that gsap doesn't work but when I remove million.js it does. I see a lot of slots in devtool that ruin my gsap animation.

![image](https://github.com/aidenybai/million/assets/100876793/8e51c36c-5df8-4f75-a83e-da3752112bec)

### What's the expected result?

I was expecting my gsap animation to work, but it didn't. 

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/VeroniDeev/million-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Any updates on this @VeroniDeev?

**Comment by VeroniDeev** [comment]
The main problem source is not million but gsap

**Comment by tobySolutions** [comment]
> In fact the problem is still there but when I delete million the problem is solved, when I open devtool, it shows me lots of slots with a width of 0, which prevents me from making animations. And i forgot its million 2.6.4 not 2.5.1

So, are you saying it works now? Also, what's your setup like?

**Comment by VeroniDeev** [comment]
> > In fact the problem is still there but when I delete million the problem is solved, when I open devtool, it shows me lots of slots with a width of 0, which prevents me from making animations. And i forgot its million 2.6.4 not 2.5.1
> 
> So, are you saying it works now? Also, what's your setup like?

No, it still doesn't work when I use million on my animation components with gsap and I can see why. When I open my chrome devtool, I see a lot of slots with a width of size 0 and it's because of the slot size that my problem persists.
