### ISSUE TITLE
🛠️ Tooling: no .env.example in the repo

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [aidenybai/million#865]
The contributing guide suggests copying `.env.example` to `.env`:

https://github.com/aidenybai/million/blob/d8b5c212ea41e1f811a25376a75ae224515d9324/.github/CONTRIBUTING.md#L143-L146

...but that `.env.example` file doesn't exist. Is it missing? What should we put in it?

I wasn't sure whether to file this as a docs request (to update the docs) or tooling one (to report an issue with the preset files)... but since `.env.example` is a common strategy for websites, my guess is it's a tooling issue that the file doesn't exist?

**Comment by tobySolutions** [comment]
Thank you very much for this @JoshuaKGoldberg, really appreciate it.
