### ISSUE TITLE
🛠️ Tooling: Issue templates for docs and tooling requests?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [aidenybai/million#866]
Thanks for making issue forms for 🐛 bugs and 🚀 feature requests! There are a couple of other common issue types that could have forms:

* 📝 Documentation requests: e.g. #864
* 🛠️ Tooling requests: e.g. #865

Would you be open to making those issue templates? I'd feel a bit more comfortable filing those types of issues with a repo-suggested template for them. 😄 

FWIW the issue templates I personally use are defined here: https://github.com/JoshuaKGoldberg/create-typescript-app/tree/main/.github/ISSUE_TEMPLATE

**Comment by tobySolutions** [comment]
Awesome! Thanks for this @JoshuaKGoldberg!
