### ISSUE TITLE
🛠️ Tooling: Allow local website development without a Liveblocks key?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [aidenybai/million#867]
Right now, if you don't set a `NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY` environment key and then `pnpm dev` the website, the page throws an error in the terminal:

```plaintext
 ✓ Compiled / in 6s (3741 modules)
 ⨯ Error: Invalid Liveblocks client options. Please provide either a `publicApiKey` or `authEndpoint` option. They cannot both be empty. For more information: https://liveblocks.io/docs/api-reference/liveblocks-client#createClient
    at prepareAuthentication (file:///Users/josh/repos/million/node_modules/.pnpm/@liveblocks+core@1.5.0/node_modules/@liveblocks/core/dist/index.mjs:1449:9)
    at createAuthManager (file:///Users/josh/repos/million/node_modules/.pnpm/@liveblocks+core@1.5.0/node_modules/@liveblocks/core/dist/index.mjs:1298:26)
    at createClient (file:///Users/josh/repos/million/node_modules/.pnpm/@liveblocks+core@1.5.0/node_modules/@liveblocks/core/dist/index.mjs:6001:23)
    at eval (webpack-internal:///./liveblocks.config.ts:15:80) {
  page: '/'
}
```

...which gets shown as a blocking Next.js error modal:

![Screenshot of a Next.js error modal showing the 'Invalid Liveblocks client options' error from the code block. Its source code block shows liveblocks.config.ts (5:28), from a call to a createClient function.](https://github.com/aidenybai/million/assets/3335181/3f323ae9-019e-44b3-81ca-f7e006be340b)

It'd be nice if we didn't need to have a Liveblocks account to run the website locally. Would you be open to letting the website run without one in dev mode? I'd be happy to send a PR that refactors this a bit to just log a warning! ❤️

**Comment by Siddharth1605** [comment]
I'd like to work on this issue

**Comment by skushagra9** [comment]
Hey, I was working on this, I logged a warning for the absence of the env variable
@tobySolutions , are you open to run the website like this in dev mode??

**Comment by Adi-ty** [comment]
something like this could work as a solution would love to contribute 
<img width="475" alt="image" src="https://github.com/aidenybai/million/assets/92062352/f554378d-d2a7-4486-8cbe-4f7e24501428">

**Comment by JoshuaKGoldberg** [comment]
🤔 this feels like an unnecessarily aggressive stale bot. It probably shouldn't close issues that aren't waiting on an external person, no?

**Comment by JoshuaKGoldberg** [comment]
bamp

**Comment by JoshuaKGoldberg** [comment]
bibbity

**Comment by JoshuaKGoldberg** [comment]
bobbity

**Comment by JoshuaKGoldberg** [comment]
boomp

**Comment by JoshuaKGoldberg** [comment]
bidoof

**Comment by ImLunaHey** [comment]
can someone change the stale bot my god..

**Comment by aidenybai** [comment]
Liveblocks GONE
