### ISSUE TITLE
📝 Documentation(All-in-Africa): Add Cap.so to the showcase page

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#888]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

It would be nice to have [Cap.so](https://cap.so) be on the [Showcase](https://million.dev/showcase) page of Million as well as Cap recently added Million to their setup

<img width="1512" alt="Screenshot 2024-01-20 at 12 19 18" src="https://github.com/aidenybai/million/assets/96334363/1f53082a-775a-4d60-9077-258997280dec">

### Additional Info

To find the file needed for the showcase, go to: https://github.com/aidenybai/million/blob/main/website/pages/showcase.mdx

**Comment by adelanaofficial** [comment]
Hey, could you kindly assign this to me?

**Comment by tobySolutions** [comment]
> Hey, could you kindly assign this to me?

Sure thing!
