### ISSUE TITLE
📝 Documentation(i18n): Translate the website homepage to French 

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#899]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Homepage of the website](https://million.dev/) to French; go to [index.fr-FR.tsx](https://github.com/aidenybai/million/blob/main/website/pages/index.fr-FR.mdx), you may see that the `<Home/>` component is coming from the `components` folder, you can create a `fr` version of the components folder or something along the lines of that.

<img width="1512" alt="Screenshot 2024-01-23 at 15 58 52" src="https://github.com/aidenybai/million/assets/96334363/271bb435-d5f4-4783-ab79-287a03982c8c">

### Additional Info

- All files with the `fr.FR`are the French language files.  Make changes to the front-matter in the file as well

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by GuiBibeau** [comment]
Hey! I can have a look at this

**Comment by tobySolutions** [comment]
> Hey! I can have a look at this

Sure thing, Gui!
