### ISSUE TITLE
📝 Documentation(i18n): Translate the docs to French

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#900]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Docs](https://million.dev/docs/introduction) to French; go to [/docs](https://github.com/aidenybai/million/tree/main/website/pages/docs), and you'll see the files with the extension `.fr-FR` extension, those are the french versions of the files; you can enter those files and make the necessary changes

<img width="1512" alt="Screenshot 2024-01-23 at 16 09 10" src="https://github.com/aidenybai/million/assets/96334363/1aed49f7-5873-4f72-9427-51a18a2f5529">

### Additional Info

- Make sure to take a look at the [English version ](https://million.dev/docs/introduction) on the website and only make the translations necessary. For example, the code snippets don't need to be translated. Make changes to the front-matter in the file as well

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by josuembuyu** [comment]
Hey @tobySolutions 
I can work on this

**Comment by tobySolutions** [comment]
Sure thing, go ahead @josuembuyu!

**Comment by tobySolutions** [comment]
You can try using the informal tone, not too informal though @josuembuyu

**Comment by josuembuyu** [comment]
OK no worries

**Comment by tobySolutions** [comment]
> OK no worries

Awesome!
