### ISSUE TITLE
📝 Documentation(i18n): Translate the Showcase page to French 

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#901]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Showcase Page](https://million.dev/showcase) to French; go to [showcase.fr-FR.mdx](https://github.com/aidenybai/million/blob/main/website/pages/showcase.fr-FR.mdx) and make the translations from there.

All you have to change is the top section though:

<img width="1512" alt="Screenshot 2024-01-23 at 16 24 51" src="https://github.com/aidenybai/million/assets/96334363/51e2f347-53d4-4479-9122-c0994727cc21">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by iamfortune** [comment]
Need help with this? I can take the task off you

**Comment by tobySolutions** [comment]
> Need help with this? I can take the task off you

Sure thing boss, go ahead! It's all yours. You can just go through the Contributing guide

**Comment by geoffreylgv** [comment]
Hi @iamfortune and @tobySolutions 
Any updates on this issue?
How is going ?

**Comment by iamfortune** [comment]
Hello @geoffreylgv I will make a PR to fix this on Wednesday. Thank you.

**Comment by iamfortune** [comment]
Hi @geoffreylgv I've made a PR for this

**Comment by geoffreylgv** [comment]
> Hi @geoffreylgv I've made a PR for this

Ok, well done!
