### ISSUE TITLE
📝 Documentation(i18n): Translate the FAQ page to French 

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#902]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [FAQ Page](https://million.dev/faq) to French; go to [faq.fr-FR.mdx](https://github.com/aidenybai/million/blob/main/website/pages/faq.fr-FR.mdx) and make the translations from there, you will have to step into the [Components folder](https://github.com/aidenybai/million/blob/main/website/pages/faq.fr-FR.mdx) to allow for there to be french version needed. 

@GuiBibeau has an implementation that he has recommended to make this work.

<img width="1512" alt="Screenshot 2024-01-23 at 16 36 09" src="https://github.com/aidenybai/million/assets/96334363/d7c88d96-5048-47a6-80d2-b9d3c692bdcb">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by preshpi** [comment]
@tobySolutions Please, I would like to work on this. I've gone through @guigui64 PR. I'll start working on mine when his PR is merged to use the same flow he used.

**Comment by tobySolutions** [comment]
> @tobySolutions Please, I would like to work on this. I've gone through @guigui64 PR. I'll start working on mine when his PR is merged to use the same flow he used.

Perfect! Thanks @preshpi! I'm assigning this to you now.
