### ISSUE TITLE
📝 Documentation(i18n): Translate the AI page to French

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#903]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [AI Page](https://million.dev/ai) to French; go to [ai.fr-FR.mdx](https://github.com/aidenybai/million/blob/main/website/pages/ai.fr-FR.mdx) and make the translations from there, you will have to step into the [Components folder](https://github.com/aidenybai/million/tree/main/website/components/ai) to allow for there to be french version needed.

@GuiBibeau has an implementation that he has recommended to make this work.

<img width="1512" alt="Screenshot 2024-01-23 at 16 47 46" src="https://github.com/aidenybai/million/assets/96334363/dbcd2cd7-0cf4-47d9-b0e2-b92bc259a21e">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by iamfortune** [comment]
I'd like to take care of this.

**Comment by tobySolutions** [comment]
> I'd like to take care of this.

Sure thing, boss!!!

**Comment by geoffreylgv** [comment]
Can I work on this page as well @tobySolutions ?

**Comment by tobySolutions** [comment]
> Can I work on this page as well @tobySolutions ?

I think @iamfortune is currently working on it, but, you can pick it up.

**Comment by geoffreylgv** [comment]
> > Can I work on this page as well @tobySolutions ?
> 
> I think @iamfortune is currently working on it, but, you can pick it up.

Ok, let have update on it then
@iamfortune how is going ?

**Comment by tobySolutions** [comment]
> > > Can I work on this page as well @tobySolutions ?
> > 
> > 
> > I think @iamfortune is currently working on it, but, you can pick it up.
> 
> Ok, let have update on it then @iamfortune how is going ?
> 
> In the meantime, I'll work on it if possible to send a PR, sounds good ?

Perfect!

**Comment by iamfortune** [comment]
I've made a PR for this @tobySolutions @geoffreylgv

**Comment by geoffreylgv** [comment]
> I've made a PR for this @tobySolutions @geoffreylgv

Hi, You mean this into Spanish?

**Comment by iamfortune** [comment]
No, to french. AI page to french

**Comment by iamfortune** [comment]
Halo, any word on this?
