### ISSUE TITLE
📝 Documentation(i18n): Translate the Blogs To French

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#905]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Blogs](https://million.dev/blog) to French; go to [blog.fr-FR.mdx](https://github.com/aidenybai/million/blob/main/website/pages/blog.fr-FR.mdx) and make the translations from there, you will have to step into the [Blogs folder](https://github.com/aidenybai/million/tree/main/website/pages/blog) to make the translations needed to the files with the `.fr-FR` extension.

<img width="1512" alt="Screenshot 2024-01-23 at 17 05 04" src="https://github.com/aidenybai/million/assets/96334363/fea07df7-ae02-4362-b0fe-a9775e73cb7f">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by chrioniep** [comment]
I would like to work on this issue

**Comment by tobySolutions** [comment]
> I would like to work on this issue

All yours @chrioniep!
