### ISSUE TITLE
📝 Documentation(i18n): Translate the Showcase page to Spanish

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#908]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Showcase Page](https://million.dev/showcase) to Spanish; go to [showcase.es-ES.mdx](https://github.com/aidenybai/million/blob/main/website/pages/showcase.es-ES.mdx) and make the translations from there.

All you have to change is the top section though:

<img width="1512" alt="Screenshot 2024-01-23 at 16 24 51" src="https://github.com/aidenybai/million/assets/96334363/51e2f347-53d4-4479-9122-c0994727cc21">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by oliverloops** [comment]
Need a hand?. I can take this task

**Comment by tobySolutions** [comment]
> Need a hand?. I can take this task

Sure thing, please go ahead Oliver!!
