### ISSUE TITLE
📝 Documentation(i18n): Translate the AI page to Spanish

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#910]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [AI Page](https://million.dev/ai) to Spanish; go to [ai.es-ES.mdx](https://github.com/aidenybai/million/blob/main/website/pages/ai.es-ES.mdx) and make the translations from there, you will have to step into the [Components folder](https://github.com/aidenybai/million/tree/main/website/components/ai) to allow for there to be spanish version needed.

@GuiBibeau has an implementation that he has recommended to make this work.

<img width="1512" alt="Screenshot 2024-01-23 at 16 47 46" src="https://github.com/aidenybai/million/assets/96334363/dbcd2cd7-0cf4-47d9-b0e2-b92bc259a21e">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by iamfortune** [comment]
I would love to help with this issue.

**Comment by tobySolutions** [comment]
> I would love to help with this issue.


Sure thing boss, go ahead! It's all yours. You can just go through the Contributing guide

**Comment by geoffreylgv** [comment]
Hi @tobySolutions, I'm working on this as well; since I did the once for French version.
