### ISSUE TITLE
📝 Documentation(i18n): Translate the Blogs To Spanish

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#912]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Blogs](https://million.dev/blog) to Spanish; go to [blog.es-ES.mdx](https://github.com/aidenybai/million/blob/main/website/pages/blog.es-ES.mdx) and make the translations from there, you will have to step into the [Blogs folder](https://github.com/aidenybai/million/tree/main/website/pages/blog) to make the translations needed to the files with the `.es-ES` extension.

<img width="1512" alt="Screenshot 2024-01-23 at 17 05 04" src="https://github.com/aidenybai/million/assets/96334363/fea07df7-ae02-4362-b0fe-a9775e73cb7f">

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

**Comment by oliverloops** [comment]
I can do this @tobySolutions  👋, native english speaker here!

**Comment by tobySolutions** [comment]
> I can do this @tobySolutions 👋, native spanish speaker here!

Sure thing, please feel free to take this on Oliver!

**Comment by oliverloops** [comment]
@tobySolutions I already translated 3 blog posts, I am just waiting for you to merge my first PR on the Foundation section translation and open a new one just for the remaining blogs. Thanks for your comprehension.

**Comment by tobySolutions** [comment]
On it @oliverloops!
