### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by TomieAi** [aidenybai/million#942]
### What version of `million` are you using?

3.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

bun, yarn

### What operating system are you using?

wsl

### What browser are you using?

edge, chrome

### Describe the Bug

create fresh vite using bun or yarn
install millionjs using bun or yarn

followed the instructions 

```ts
export default defineConfig({
  plugins: [million.vite({ auto: true }), react()],
});
```

then I do.. bun run dev.

look at the console.
 
![image](https://github.com/aidenybai/million/assets/111332073/7ab9dce4-81d5-461d-8084-a33f40911eff)

### What's the expected result?

expected result is to show non of that error at all because its a fresh project. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-ya4ek3

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hey thanks for opening this. I'll check it out soon

**Comment by OskarEichler** [comment]
Yep we have the same issue
![Screenshot 2024-02-06 at 16 51 54](https://github.com/aidenybai/million/assets/62393985/790b5a2e-dc9f-48b3-ab72-6018081982be)

**Comment by Srlion** [comment]
This doesn't appear with production builds, only in development mode. (At least for me)

**Comment by khuezy** [comment]
I'm also getting the same issue using the latest v3, even in production.

**Comment by Aslemammad** [comment]
I think it's being tracked on #946

**Comment by tobySolutions** [comment]
> I think it's being tracked on #946 

Oh! Ok, awesome 🫡🫡

**Comment by OrionSeven** [comment]
I'm seeing the same issue.
