### ISSUE TITLE
bug: SVG not rendering correctly

### ISSUE THREAD

**Issue by Sharad-Bhat-98** [aidenybai/million#957]
I have a React component that renders an SVG. The Million JS compiler threw a warning: 'The tag <g> is unrecognized in this browser.' After browsing through the GitHub issues, I found out that the SVG component should be wrapped within a <div> tag. After doing this, the warning was not thrown; however, the images embedded in the SVG are not getting displayed.
- React version 18.2.0
- vite version 5.1.0
- million version 3.0.3
- Browser  Brave Version 1.62.162 Chromium: 121.0.6167.164
- Firefox version 122.0.1

[https://stackblitz.com/edit/vitejs-vite-baa9x1?file=src%2FApp.jsx,vite.config.js,package.json&terminal=dev](url)

**Comment by lleewwiiss** [comment]
Same problem I have with my SVG: `Warning: The tag <g> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.` 

Also it has seemed to remove my linear gradient (may be related)

**Comment by kamto7** [comment]
same question

**Comment by henrituan** [comment]
+1 for the problem `Warning: The tag <g> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.`, here is my console warning:
![image](https://github.com/aidenybai/million/assets/16315811/7c862d18-649d-4edd-9975-8b32debc6e6a)

And the SVG in DOM is indeed rendered in a `<g>` tag when using Million for some reason:
![image](https://github.com/aidenybai/million/assets/16315811/8eb26182-028c-456d-9554-08ed1f6c3834)

Thanks

**Comment by anth0ni3** [comment]
I'm experiencing this issue too. Solution???

**Comment by joshoconnor** [comment]
Also experiencing this same issue

**Comment by tomavanc** [comment]
Here too. Downgrading to v2 (2.6.4 in my case) gets rid of the message

**Comment by monicaricks** [comment]
I'm experiencing the same issue: 
![image](https://github.com/aidenybai/million/assets/14205668/e99a8902-c361-46ef-bdd2-4c9a9a73b3cb)
