### ISSUE TITLE
some errors/warnings (mostly hydration) in a remix project

### ISSUE THREAD

**Issue by halindraprakoso** [aidenybai/million#962]
### What version of `million` are you using?

3.0.3

### Are you using an SSR adapter? If so, which one?

Remix

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I noticed some warnings/errors in the console after upgrading to 3.x in my remix project, though I'm not certain what these might cause as the app was still functioning. It could be reproduced using a fresh remix project (with vite)

<img width="915" alt="image" src="https://github.com/aidenybai/million/assets/89775119/b4247264-75ef-4537-8605-7e844c698e4c">

then adding a script like so:
```
<script
          dangerouslySetInnerHTML={{
            __html: `window.ENV = ${JSON.stringify({ env1: "test"})}`,
          }}
 />
```
completely break the site  (probably not so important because I could create a component of it and `// million-ignore` it)
<img width="1165" alt="image" src="https://github.com/aidenybai/million/assets/89775119/75300839-30bd-4a2f-9c79-633e20179734">

 

### What's the expected result?

no warnings/errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ciwjgo?file=vite.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thanks for reporting @halindraprakoso, but, I wasn't able to reproduce this on my end; this is what I got:

https://stackblitz.com/edit/github-ciwjgo-klwsv5?file=vite.config.ts

<img width="1512" alt="Screenshot 2024-02-12 at 11 36 15" src="https://github.com/aidenybai/million/assets/96334363/5fe45480-696a-4402-96e8-7064f6b58093">

**Comment by halindraprakoso** [comment]
Hi @tobySolutions 
were there any hydration error in the console? 
it actually caused bugs in my app that I had to revert back to 2.6.4.

unfortunately I'm still getting the same errors even from your stackblitz
<img width="1504" alt="image" src="https://github.com/aidenybai/million/assets/89775119/b9d91c52-9d16-4e6c-990f-c4246023a12b">

**Comment by tobySolutions** [comment]
> Hi @tobySolutions were there any hydration error in the console? it actually caused bugs in my app that I had to revert back to 2.6.4.
> 
> unfortunately I'm still getting the same errors even from your stackblitz <img alt="image" width="1504" src="https://private-user-images.githubusercontent.com/89775119/304026151-b9d91c52-9d16-4e6c-990f-c4246023a12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzUxODcsIm5iZiI6MTcwNzczNDg4NywicGF0aCI6Ii84OTc3NTExOS8zMDQwMjYxNTEtYjlkOTFjNTItOWQxNi00ZTZjLTk5MGYtYzQyNDYwMjNhMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMzA4NTY4Zjg4YjhmZmQyOTM4OGY5NmRlY2RlYTQzNTBhOWIyYTVmNDM3NTlmMTc2OTI1NjRlNmZlZmY1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXyZ8uw6l5g2ejBX8ThMeBtBuTqbrRwroAyjfTXXS9Y">

Actually you're right, I'm getting it here too. Thanks for sharing this, I appreciate it.

<img width="1512" alt="Screenshot 2024-02-12 at 11 49 36" src="https://github.com/aidenybai/million/assets/96334363/e23aafe0-1235-45a4-ab53-243441d13fe9">

**Comment by tobySolutions** [comment]
I have shared with one of our engineers. Thanks!

**Comment by Aslemammad** [comment]
I'll fix this soon!

**Comment by tobySolutions** [comment]
Thanks @Aslemammad
