### ISSUE TITLE
Bug: Installer fails when installing via Bun inside a react project

### ISSUE THREAD

**Issue by ar065** [aidenybai/million#965]
### What version of `million` are you using?

3.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Bun

### What operating system are you using?

Linux (WSL2)

### What browser are you using?

Brave

### Describe the Bug

When installing MillionJS via the installer (`bunx million@latest`), the install will fail because the MillionJS installer Cli uses `performance.markResourceTiming`, which is not currently available in Bun. This results in this output when trying to install via the Cli:
```
ar06@REDACTED:~/documents/Projects/vite-project$ bunx million@latest
┌  ⚡ Million.js 3.0.3
│
◇  bun detected.
│
◇  Installed million with bun.
│
◆  Detected vite project.
│
◇  Transforming vite.config.ts ─────────╮
│                                       │
│  found existing vite.config.ts file.  │
│                                       │
├───────────────────────────────────────╯
12904 |         cacheState
12905 |       );
12906 |     }
12907 |     function markResourceTiming(timingInfo, originalURL, initiatorType, globalThis2, cacheState) {
12908 |       if (nodeMajor > 18 || nodeMajor === 18 && nodeMinor >= 2) {
12909 |         performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState);
                ^
TypeError: performance.markResourceTiming is not a function. (In 'performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState)', 'performance.markResourceTiming' is undefined)
      at markResourceTiming (/tmp/million@latest--bunx/node_modules/million/packages/cli/dist/index.js:12909:9)
      at finalizeAndReportTiming (/tmp/million@latest--bunx/node_modules/million/packages/cli/dist/index.js:12899:7)
      at processResponseEndOfBody (/tmp/million@latest--bunx/node_modules/million/packages/cli/dist/index.js:12843:79)
      at /tmp/million@latest--bunx/node_modules/million/packages/cli/dist/index.js:13222:46
│
└  ✓  You're all set!

ar06@REDACTED:~/documents/Projects/vite-project$
```

The `vite.config.ts` is not modified because of this error and a manual install needs to be performed instead.

### What's the expected result?

For the MillionJS Cli (via Bun) to install MillionJS and set it up automatically within my project.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/hidden-snow-xkj826?file=%2FREADME.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thank you very much for sharing this @ar065, let me check it out.

**Comment by tobySolutions** [comment]
Can you possibly check this out @Aslemammad? It seems there's an unavailable method that is causing the error. I can pick it up as well if you want.

**Comment by Aslemammad** [comment]
Sure, please assign me!

**Comment by Aslemammad** [comment]
#967 should fix it
