### ISSUE TITLE
Support react-native-web

### ISSUE THREAD

**Issue by Thiagolino8** [aidenybai/million#970]
### Describe the feature

React native web creates react native component aliases for components that use web elements, but million still cannot optimize components that use react-native-web
[Reproduction](https://stackblitz.com/edit/vitejs-vite-526drg?file=src%2FApp.tsx)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tobySolutions** [comment]
Could you please help with a reproduction, please? Thanks 🙌

**Comment by Thiagolino8** [comment]
Sure, @tobySolutions 
https://stackblitz.com/edit/vitejs-vite-526drg?file=src%2FApp.tsx
