### ISSUE TITLE
RsPack compiler doesn't works

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [aidenybai/million#972]
### What version of `million` are you using?

3.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm & npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

RsPack compiler doesn't do anything.

Shows the toast that million started
![image](https://github.com/aidenybai/million/assets/107539652/93c9f582-bee6-4164-ab82-516680b2cb38)

But it doesn't anything else, I configured with { auto: true }

Should say something more like, App now renders 90% faster

### What's the expected result?

App is optimized.
Is intended to work as said by Twitter/X https://twitter.com/milliondotjs/status/1727892520217309372

### Link to Minimal Reproducible Example

[App is not compiling with million virtual dom](https://codesandbox.io/p/devbox/million-rspack-z2cfhk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clste3l7l0007356hn8klj7cl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clste3l7k0002356hvy4u12fd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clste3l7k0004356h5l4wceuu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clste3l7l0006356hd63lxwmo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clste3l7k0002356hvy4u12fd%2522%253A%257B%2522id%2522%253A%2522clste3l7k0002356hvy4u12fd%2522%252C%2522activeTabId%2522%253A%2522clstea8zy00ts356hbhoq6h32%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Frspack-project%252Fpackage.json%2522%252C%2522id%2522%253A%2522clstea8zy00ts356hbhoq6h32%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clste3l7l0006356hd63lxwmo%2522%253A%257B%2522id%2522%253A%2522clste3l7l0006356hd63lxwmo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A8080%252C%2522id%2522%253A%2522clstec64t00x2356hgpjsd1v6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clstec64t00x2356hgpjsd1v6%2522%257D%252C%2522clste3l7k0004356h5l4wceuu%2522%253A%257B%2522id%2522%253A%2522clste3l7k0004356h5l4wceuu%2522%252C%2522activeTabId%2522%253A%2522clste46xy006z356h6idpuav0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clste46xy006z356h6idpuav0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clste4ary0065dcip6ely3izx%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoseBuendiaDigio** [comment]
Hi @tobySolutions

**Comment by andrew-t-james** [comment]
This tool looks awesome I am also Interested in rspack or rsbuild if possible.happy to contribute.

**Comment by JoseBuendiaDigio** [comment]
Nothing to do with this?

**Comment by vikas5914** [comment]
if anyone need help, try this: 

```
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";
import { pluginSvgr } from "@rsbuild/plugin-svgr";
import { pluginImageCompress } from "@rsbuild/plugin-image-compress";
import MillionLint from "@million/lint";

export default defineConfig({
  plugins: [
    pluginImageCompress(),
    pluginSvgr({ mixedImport: true }),
    pluginReact(),
  ],
  tools:{
    rspack: {
      plugins: [
        MillionLint.rspack()
      ]
    }
  }
});
```
