### ISSUE TITLE
Error rendering String Css custom properties (Css variables) in styles property

### ISSUE THREAD

**Issue by lcoronelp** [aidenybai/million#975]
### What version of `million` are you using?

3.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

If I define a div within a component optimized by million.js (when loads inside a `< slot >`) that contains CSS custom properties in styles, it only inserts it into the HTML if the custom property is numeric (when loads inside a <slot>).

If it is string, it does not add it.

Whereas in a component not optimized by million, it works perfectly.

### What's the expected result?

In the example https://codesandbox.io/p/devbox/cx79w2, both boxes should have a yellow background.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/cx79w2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aeyll-11** [comment]
@lcoronelp I dont know what exactly happened but removing the <p> render the yellow in your case

**Comment by tobySolutions** [comment]
Thanks for bringing this up @lcoronelp, I think @Aslemammad could be able to help here. I saw your reproduction and I was able to help with this. 

I'm guessing it could likely be a slots issue and we just so happen to have fixed that already ( we have an experimental solution).
