### ISSUE TITLE
[million] updating from 3.0.3 to 3.0.4 causes an error in gatsby.js dev

### ISSUE THREAD

**Issue by JustFly1984** [aidenybai/million#982]
### What version of `million` are you using?

3.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

After updating million@3.0.3 to 3.0.4 getting new error/warning:

```sh
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the
server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and
 the intended UI. To avoid this, useLayoutEffect should only be used in components that render
exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /Users/user/projects/gatsby-frontend/.cache/page-ssr/routes/render-page.js:60084:16
    at Html
(/Users/user/projects/gatsby-frontend/.cache/page-ssr/routes/render-page.js:8656:3)
```

reverting it back to 3.0.3 resolves an error

### What's the expected result?

No error, not using browser only APIs for SSR.

### Link to Minimal Reproducible Example

sorry

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thank you for sharing this @JustFly1984, we're looking into it. Check this out @Aslemammad

**Comment by JustFly1984** [comment]
not stale
