### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by Alberto-Arias-x64** [aidenybai/million#983]
### What version of `million` are you using?

3.0.4

### Are you using an SSR adapter? If so, which one?

Node/Express

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I'm trying to use functions about zustand store, but when i declare more of one function this don't work.

when i remove  million.vite({ auto: true }) of vite.config.ts works normally

i have this warning on console : 
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

### What's the expected result?

i will like use more than one zustand function whit million.vite({ auto: true })

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/Alberto-Arias-x64/meli-front-test

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Thank you @Alberto-Arias-x64, I can see that it is a warning thanks to the reproduction that you shared. I will share this with core team (@Aslemammad) would be happy to help here.
