### ISSUE TITLE
I see that components exported as default export getting wrapped into slot tag

### ISSUE THREAD

**Issue by JustFly1984** [aidenybai/million#985]
### What version of `million` are you using?

3.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm using gatsby integration and I have almost all components exported as `export const Component: ComponentType<Props> = memo<Props>(_Component)

but I've noticed a bug in one of my custom component, analyzing it I've found that it is wrapped in `<slot>` tag
The only difference I've found - it was `export default memo(Component)`
I've changed export to `export const` and it fixed the bug and removed the slot tag from html

I've went through whole app codebase and replaced default exports everywhere, except template files, cos I'm using createPages API instead of limited pages dir routing
Anyway, gatsby requires template files to export component as `export default`, and src/html.tsx too.
Setting disable million comments doesn't help and I see at least one slot at the top of html tree.  

### What's the expected result?

disable slot optimization for some `export default` components, or disable it at all.

### Link to Minimal Reproducible Example

sorry

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Hello @JustFly1984, thank you again. Can you please make sure to provide reproduction along with issues you report?

**Comment by JustFly1984** [comment]
not stale

**Comment by JustFly1984** [comment]
Not stale
