### ISSUE TITLE
Remix SPA fails

### ISSUE THREAD

**Issue by toyamarodrigo** [aidenybai/million#987]
### What version of `million` are you using?

3.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chromium (Arc)

### Describe the Bug

I started a project from zero using the Remix SPA Mode template

```sh
npx create-remix@latest --template remix-run/remix/templates/spa
```

installed million and added automatic mode

```sh
npx million@latest
```

```js
export default defineConfig({
  plugins: [million.vite({ auto: true }), react()],
});
```
![CleanShot 2024-03-07 at 00 08 57@2x](https://github.com/aidenybai/million/assets/41844101/87ee81df-811e-4dcb-bea8-063dda049c46)

```json
{
  "@remix-run/node": "^2.8.0",
  "@remix-run/react": "^2.8.0",
  "million": "^3.0.5",
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
}
```

### What's the expected result?

It should show the remix starter page 

![CleanShot 2024-03-07 at 00 11 33@2x](https://github.com/aidenybai/million/assets/41844101/0c40c23f-97e7-4b5d-a058-8315df4762d6)

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/toyamarodrigo/test-remix-spa

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by toyamarodrigo** [comment]
Seems to work on 3.0.3 and 3.0.2
but not
- 3.0.0
- 3.0.1
- 3.0.3
- 3.0.4
- 3.0.5

**Comment by tobySolutions** [comment]
Hey there @toyamarodrigo, can you try setting the `rsc` value in the compiler options to `true`? You should end up with something like this in Vite config:

```ts
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import million from "million/compiler";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [
    million.vite({ auto: true, rsc: true }),
    remix({
      ssr: false,
    }),
    tsconfigPaths(),
  ],
});

```

**Comment by tobySolutions** [comment]
I reported it to core team as well and work is being done to resolve the issues you're having. Thank you @toyamarodrigo

**Comment by toyamarodrigo** [comment]
> Hey there @toyamarodrigo, can you try setting the `rsc` value in the compiler options to `true`? You should end up with something like this in Vite config:
> 
> ```ts
> import { vitePlugin as remix } from "@remix-run/dev";
> import { defineConfig } from "vite";
> import million from "million/compiler";
> import tsconfigPaths from "vite-tsconfig-paths";
> 
> export default defineConfig({
>   plugins: [
>     million.vite({ auto: true, rsc: true }),
>     remix({
>       ssr: false,
>     }),
>     tsconfigPaths(),
>   ],
> });
> ```

It seems to work with `rsc: true`, but is that property supposed to be added in spa mode? 🤔
