### ISSUE TITLE
feat: Add Parcel 2 Support for Million.js

### ISSUE THREAD

**Issue by SethBurkart123** [aidenybai/million#990]
### Describe the feature

I'm a big fan of Million.js and its overall concept, which is truly wonderful. However, I'm currently working on a project that uses Parcel 2 as the bundler/compiler, and I've encountered limitations when trying to integrate Million.js with Parcel 2.

While I've managed to get Million.js partially working with Parcel 2, the limitations stem from not being able to use the Million.js compiler. This means I cannot take full advantage of Million.js's advanced features. I'd love it if some support could be added.

### Why should this be a priority

While parcel2 in itself is not too popular, the **very** popular extension framework [plasmo](https://github.com/PlasmoHQ/plasmo) is built on top of parcel. Meaning that if you add support for parcel2, then we get support for plasmo and vice-versa.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by PointSingularity** [comment]
I have the exact same use case. I am developing an extension with plasmo with react, but would love to incorporate million into it.

**Comment by victoralvelais** [comment]
I'm also missing out on integrating Million for my Chrome extension built with Parcel.

**Comment by victoralvelais** [comment]
I'm humbly begging for the Parcel crew to get some love @aidenybai 🙏🏽 I spent all day trying to get multiple vite ports working just to try Million.js out in my excitement (they all failed).
