### ISSUE TITLE
Million.js Lint Not Working

### ISSUE THREAD

**Issue by Bader975** [aidenybai/million#994]
### What version of `million` are you using?

V3.0.6

### Are you using an SSR adapter? If so, which one?

none 

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

Chrome

### Describe the Bug

Million.js Lint not working
![Screenshot 2024-03-17 072717](https://github.com/aidenybai/million/assets/80196102/83351c1b-fd32-48b0-9653-46a692d37319)

### What's the expected result?

it's should give hits to speed up my React app 

### Link to Minimal Reproducible Example

none , no error 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lucarampi** [comment]
Same problem.

**Comment by AndreiTS** [comment]
Same problem here:
![image](https://github.com/aidenybai/million/assets/13489837/a46a13d9-b487-46b2-b00b-eb60a36ffd81)

Info:
- Windows 11
- yarn: 4.1.1
- vite: 5.1.6
- @million/lint: 0.0.73

**Comment by AndreiTS** [comment]
> Same problem here: ![image](https://private-user-images.githubusercontent.com/13489837/313776323-a46a13d9-b487-46b2-b00b-eb60a36ffd81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODM2NTEsIm5iZiI6MTcxMDc4MzM1MSwicGF0aCI6Ii8xMzQ4OTgzNy8zMTM3NzYzMjMtYTQ2YTEzZDktYjQ4Ny00NmIyLWIwMGItZWI2MGEzNmZmZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE3MzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZmNlMGQ2Y2VhMTEyYzFhMzExYjA3MjYyY2EwNmEyNDgxZDIyNmJlMGVmMzdiMmExZjg0YmM2YThiNDY5ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w3VfvTWu5gb761ocxytVkqQaOgsolwws308raaTl4Lg)
> 
> Info:
> 
>     * Windows 11
> 
>     * yarn: 4.1.1
> 
>     * vite: 5.1.6
> 
>     * @million/lint: 0.0.73

Changed to million.vite({ auto: true }), and it worked.

Maybe this steps need to clarify this?
![image](https://github.com/aidenybai/million/assets/13489837/4ac97901-04dd-4690-ae0f-cd55844e659d)

**Comment by Alcas1** [comment]
Same problem here:
* Mac 14.3.1
* NextJS 13.5
* Yarn 3.3.0
* @million/lint: 0.0.73

**Comment by oskarscholander** [comment]
Same! 👋

- Mac Sonoma 14.2
- Vite v5.0.12
- Yarn 4.0.2
- @million/lint: 0.0.73

**Comment by BaileyNepe** [comment]
I get this issue as well when running in a bun workspace, however when I run on a different app using npm and not in a workspace, the linting works fine.

**Comment by cold-world** [comment]
same

Windows 11
npm: 10.5.0
vite: 5.1.6
@million/lint: 0.0.73

**Comment by N0SAFE** [comment]
same

Windows 11
npm 10.2.5
next 14.1.3
@million/lint 0.0.73

**Comment by cold-world** [comment]
and also it makes errors with react key prop all over the app

**Comment by emedeirox** [comment]
Same 

Windows 11
pnpm 8.15.5
vite 5.1.4
@million/lint: 0.0.73

**Comment by tobySolutions** [comment]
Hmm, thank you all for coming here to report this. I have reported this team and it's currently being worked on. Appreciate it:

- @Bader975 
- @lucarampi 
- @AndreiTS 
- @Alcas1 
- @oskarscholander 
- @BaileyNepe 
- @cold-world 
- @N0SAFE 
- @EliKnoph 
- @emedeirox

**Comment by giovanniincammicia** [comment]
Hi, mine is the same, but I have a vscode notification that says: "million lint is successfully installed...waiting for connection" and never disappears. I tried logging into: https://lint.million.dev, but it immediately says: "session expired, log in again".

To test the linter, I've used a client component with a useEffect that runs setState(v => v + 1) indefinitely, producing infinite re-renders. Is it a good test that million lint should be able to recognize?

**Comment by tobySolutions** [comment]
> Hi, mine is the same, but I have a vscode notification that says: "million lint is successfully installed...waiting for connection" and never disappears. I tried logging into: https://lint.million.dev, but it immediately says: "session expired, log in again".
> 
> To test the linter, I've used a client component with a useEffect that runs setState(v => v + 1) indefinitely, producing infinite re-renders. Is it a good test that million lint should be able to recognize?

We're currently working on this actually. A fix will be sent in the next patch of the Million lint release

**Comment by brendon1555** [comment]
Has there been any progress on this? Particularly with it not working in a workspace?

**Comment by sudexp** [comment]
The same issue for me (react/vite, yarn, mac os) fixed with:
1. yarn add -D million@latest
2. yarn add -D @million/lint 
3. vite.config.ts: 
...
import million from 'million/compiler';
import MillionLint from '@million/lint';

export default defineConfig({
plugins: [
    ...
    react(),
    million.vite({ auto: true }),
    MillionLint.vite(),
  ],
  ...
  });

**Comment by Alcas1** [comment]
Not stale

**Comment by J4v4Scr1pt** [comment]
Same as all the others

**Comment by cold-world** [comment]
> The same issue for me (react/vite, yarn, mac os) fixed with:
> 
> 1. yarn add -D million@latest
> 2. yarn add -D @million/lint
> 3. vite.config.ts:
>    ...
>    import million from 'million/compiler';
>    import MillionLint from '@million/lint';
> 
> export default defineConfig({ plugins: [ ... react(), million.vite({ auto: true }), MillionLint.vite(), ], ... });

this works with million lint but it gives a lot of errors in project like missing key props in react, react-hook-form and tanstack-query  not working properly.

**Comment by Bader975** [comment]
@cold-world how install Million.js lint on Next,js 14 ?

**Comment by tobySolutions** [comment]
> @cold-world how install Million.js lint on Next,js 14 ?

Hey there, just follow this: https://million.dev/docs/introduction

**Comment by jacksmethurst** [comment]
Hitting the same issue, any updates?

**Comment by aidenybai** [comment]
Please continue the thread here: #1029
