### ISSUE TITLE
Million does not connect to vscode

### ISSUE THREAD

**Issue by eurobob** [aidenybai/million#995]
### What version of `million` are you using?

3.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

My browser does not connect to vscode. I am getting an Access control check error which might be related?

I have redacted the local app URL for privacy, we do not use localhost for security and authentication reasons

<img width="340" alt="Screenshot 2024-03-17 at 12 12 07" src="https://github.com/aidenybai/million/assets/4255350/f89fb4e9-82ae-43a6-8ca4-1457737bf36b">

<img width="933" alt="Screenshot 2024-03-17 at 12 18 09" src="https://github.com/aidenybai/million/assets/4255350/75a98d08-e88e-4068-a03c-5fee3e9b3490">

### What's the expected result?

Browser application connects to vscode to log reports.

### Link to Minimal Reproducible Example

Not possible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment]
Can you review this @NisargIO. Thank you for reporting @eurobob.

**Comment by A-Shleifman** [comment]
Million is failing to connect when using an `https` url pointing to localhost, however, this issue is gone when connecting to the same app via `localhost:{port}`.

**Comment by A-Shleifman** [comment]
not sure why, but today it's working even when loading the page via an https alias pointing to localhost.
